#![allow(unused_mut, non_snake_case, dead_code, clippy::needless_return, clippy::too_many_arguments)]
// Generated by Spiral portable Rust backend.

fn backup_slot_for0(v0: i32, v1: i32) -> i32 {
    let v2: bool = v0 < 0;
    if v2 {
        v1
    } else {
        v0
    }
}

fn backup_next_count1(v0: i32, v1: i32) -> i32 {
    let v2: bool = v0 < 0;
    if v2 {
        let v3: i32 = v1 + 1;
        v3
    } else {
        v1
    }
}

fn backup_should_capture2(v0: i32, v1: i32) -> i32 {
    let v2: bool = v1 < 0;
    if v2 {
        0
    } else {
        let v3: bool = v0 < 0;
        if v3 {
            1
        } else {
            0
        }
    }
}

fn backup_binding_slot3(v0: i32, v1: i32) -> i32 {
    let v2: bool = v0 < 0;
    if v2 {
        -1
    } else {
        let v3: bool = v1 < 0;
        if v3 {
            -1
        } else {
            v0
        }
    }
}

fn capture_authorized4(v0: i32, v1: i32) -> i32 {
    let v2: bool = v0 < 0;
    if v2 {
        0
    } else {
        let v3: bool = v1 < 0;
        if v3 {
            0
        } else {
            let v4: bool = v1 < v0;
            if v4 {
                0
            } else {
                1
            }
        }
    }
}

fn capture_binding_slot5(v0: i32, v1: i32) -> i32 {
    let v2: bool = v0 < 0;
    if v2 {
        -1
    } else {
        let v3: bool = v1 < 1;
        if v3 {
            -1
        } else {
            let v4: bool = 1 < v1;
            if v4 {
                -1
            } else {
                v0
            }
        }
    }
}

fn promotion_slot_authorized6(v0: i32, v1: i32) -> i32 {
    let v2: bool = v0 < 0;
    if v2 {
        0
    } else {
        let v3: bool = v1 < 0;
        if v3 {
            0
        } else {
            let v4: bool = v0 < v1;
            if v4 {
                0
            } else {
                let v5: bool = v1 < v0;
                if v5 {
                    0
                } else {
                    1
                }
            }
        }
    }
}

fn rollback_next8(v0: i32, v1: i32) -> i32 {
    let v2: bool = v1 < v0;
    if v2 {
        let v3: i32 = v0 - v1;
        let v4: i32 = v3 - 1;
        v4
    } else {
        -1
    }
}

fn restoration_select7(v0: i32, v1: i32) -> i32 {
    rollback_next8(v0, v1)
}

fn restoration_bind9(v0: i32, v1: i32) -> i32 {
    let v2: bool = v0 < 0;
    if v2 {
        -1
    } else {
        let v3: bool = v1 < 0;
        if v3 {
            -1
        } else {
            let v4: bool = v0 < v1;
            if v4 {
                -1
            } else {
                let v5: bool = v1 < v0;
                if v5 {
                    -1
                } else {
                    v0
                }
            }
        }
    }
}

fn restoration_complete10(v0: i32, v1: i32) -> i32 {
    let v2: bool = v0 < 0;
    if v2 {
        0
    } else {
        let v3: bool = v1 < 0;
        if v3 {
            0
        } else {
            let v4: bool = v0 < v1;
            if v4 {
                0
            } else {
                let v5: bool = v1 < v0;
                if v5 {
                    0
                } else {
                    1
                }
            }
        }
    }
}

fn restoration_attempt_count11(v0: i32, v1: i32) -> i32 {
    let v2: bool = v0 < 0;
    if v2 {
        -1
    } else {
        let v3: bool = v1 < 0;
        if v3 {
            -1
        } else {
            let v4: i32 = 2147483647 - v0;
            let v5: bool = v4 < v1;
            if v5 {
                -1
            } else {
                let v6: i32 = v0 + v1;
                v6
            }
        }
    }
}

fn restoration_attempt_authorized12(v0: i32, v1: i32) -> i32 {
    let v2: bool = v0 < 0;
    if v2 {
        0
    } else {
        let v3: bool = v1 < 0;
        if v3 {
            0
        } else {
            let v4: bool = v1 < v0;
            if v4 {
                1
            } else {
                0
            }
        }
    }
}

fn restoration_counter_next13(v0: i32, v1: i32) -> i32 {
    let v2: bool = v0 < 0;
    if v2 {
        -1
    } else {
        let v3: bool = v1 < 1;
        if v3 {
            -1
        } else {
            let v4: bool = 1 < v1;
            if v4 {
                -1
            } else {
                let v5: bool = v0 < 2147483647;
                if v5 {
                    let v6: i32 = v0 + 1;
                    v6
                } else {
                    -1
                }
            }
        }
    }
}

fn restoration_accumulator_outcome14(v0: i32, v1: i32) -> i32 {
    let v2: bool = v1 < 0;
    if v2 {
        -1
    } else {
        let v3: bool = v0 < 0;
        if v3 {
            -1
        } else {
            let v4: bool = 1 < v0;
            if v4 {
                -1
            } else {
                let v5: bool = v0 < 1;
                if v5 {
                    0
                } else {
                    let v6: bool = v1 < 1;
                    if v6 {
                        1
                    } else {
                        2
                    }
                }
            }
        }
    }
}

#[must_use]
pub fn eoie_patch_backup_slot(first: i32, second: i32) -> i32 {
    backup_slot_for0(first, second)
}

#[must_use]
pub fn eoie_patch_backup_next_count(first: i32, second: i32) -> i32 {
    backup_next_count1(first, second)
}

#[must_use]
pub fn eoie_patch_backup_should_capture(first: i32, second: i32) -> i32 {
    backup_should_capture2(first, second)
}

#[must_use]
pub fn eoie_patch_backup_binding_slot(first: i32, second: i32) -> i32 {
    backup_binding_slot3(first, second)
}

#[must_use]
pub fn eoie_patch_capture_authorized(first: i32, second: i32) -> i32 {
    capture_authorized4(first, second)
}

#[must_use]
pub fn eoie_patch_capture_binding_slot(first: i32, second: i32) -> i32 {
    capture_binding_slot5(first, second)
}

#[must_use]
pub fn eoie_patch_promotion_slot_authorized(first: i32, second: i32) -> i32 {
    promotion_slot_authorized6(first, second)
}

#[must_use]
pub fn eoie_patch_restoration_select(first: i32, second: i32) -> i32 {
    restoration_select7(first, second)
}

#[must_use]
pub fn eoie_patch_restoration_bind(first: i32, second: i32) -> i32 {
    restoration_bind9(first, second)
}

#[must_use]
pub fn eoie_patch_restoration_complete(first: i32, second: i32) -> i32 {
    restoration_complete10(first, second)
}

#[must_use]
pub fn eoie_patch_restoration_attempt_count(first: i32, second: i32) -> i32 {
    restoration_attempt_count11(first, second)
}

#[must_use]
pub fn eoie_patch_restoration_attempt_authorized(first: i32, second: i32) -> i32 {
    restoration_attempt_authorized12(first, second)
}

#[must_use]
pub fn eoie_patch_restoration_counter_next(first: i32, second: i32) -> i32 {
    restoration_counter_next13(first, second)
}

#[must_use]
pub fn eoie_patch_restoration_accumulator_outcome(first: i32, second: i32) -> i32 {
    restoration_accumulator_outcome14(first, second)
}
