// Generated by Spiral portable Rust backend.
#![allow(unused_mut, non_snake_case)]

#![allow(dead_code)]

use std::cell::RefCell;
use std::rc::Rc;

type Array1 = Rc<RefCell<Vec<i32>>>;
fn ArrayCreate1(len: i32, _init_at_zero: bool) -> Array1 {
    assert!(len >= 0, "negative Spiral array length");
    Rc::new(RefCell::new(vec![0; len as usize]))
}
fn DynamicArraySet1(array: &Array1, index: i32, value: i32) {
    assert!(index >= 0, "negative Spiral array index");
    let mut data = array.borrow_mut();
    let index = index as usize;
    assert!(index < data.len(), "Spiral array index out of bounds");
    data[index] = value;
}
fn DynamicArrayGet1(array: &Array1, index: i32) -> i32 {
    assert!(index >= 0, "negative Spiral array index");
    let data = array.borrow();
    let index = index as usize;
    assert!(index < data.len(), "Spiral array index out of bounds");
    data[index]
}
fn DynamicArrayLen1(array: &Array1) -> i32 {
    let len = array.borrow().len();
    assert!(len <= i32::MAX as usize, "Spiral array length exceeds i32");
    len as i32
}
fn DynamicArrayClone1(_array: &Array1) {}
fn DynamicArrayDrop1(_array: &Array1) {}

#[derive(Clone)]
struct Tuple9000 {
    v0: i32,
    v1: Rc<str>,
    v2: Array1,
}

fn TupleCreate9000(v0: i32, v1: Rc<str>, v2: Array1) -> Tuple9000 {
    Tuple9000 { v0, v1, v2 }
}

#[derive(Clone, Copy)]
struct ClosureValue0 {
}

fn ClosureValueCreate0() -> ClosureValue0 {
    ClosureValue0 {  }
}

fn ClosureInvoke0(__x: ClosureValue0, v0: i32) -> Tuple9000 {
    let v1: bool;
    v1 = v0 == 0;
    if v1 {
        return TupleCreate9000(0, Rc::<str>::from(""), ArrayCreate1(0, false));
    } else {
        let v3: Array1;
        v3 = ArrayCreate1(2, false);
        DynamicArraySet1(&v3, 0, v0);
        let v4: i32;
        v4 = v0 + 1;
        DynamicArraySet1(&v3, 1, v4);
        let v5: Rc<str>;
        v5 = Rc::<str>::from("hi");
        return TupleCreate9000(1, v5.clone(), v3);
    }
}

fn method0(v0: ClosureValue0) -> Tuple9000 {
    return ClosureInvoke0(v0.clone(), 0);
}

fn method1(v0: ClosureValue0) -> Tuple9000 {
    return ClosureInvoke0(v0.clone(), 4);
}

fn spiral_main() -> i32 {
    let v0: ClosureValue0;
    v0 = ClosureValueCreate0();
    let v1: Tuple9000;
    v1 = method0(v0.clone());
    let mut v12: i32;
    if v1.v0 == 0 {
        v12 = 3;
    } else {
        let v2: Rc<str>;
        v2 = v1.v1.clone();
        let v3: Array1;
        v3 = v1.v2.clone();
        DynamicArrayClone1(&v3);
        let v4: i32;
        v4 = v2.len() as i32;
        let v5: i32;
        v5 = DynamicArrayLen1(&v3);
        let v6: i32;
        v6 = v4 + v5;
        let v7: i32;
        v7 = DynamicArrayGet1(&v3, 0);
        let v8: i32;
        v8 = v6 + v7;
        let v9: i32;
        v9 = DynamicArrayGet1(&v3, 1);
        drop(v3);
        let v10: i32;
        v10 = v8 + v9;
        v12 = v10;
    }
    if v1.v0 == 1 {
        drop(v1.v1);
    }
    drop(v1.v2);
    let v13: Tuple9000;
    v13 = method1(v0.clone());
    let mut v24: i32;
    if v13.v0 == 0 {
        v24 = 3;
    } else {
        let v14: Rc<str>;
        v14 = v13.v1.clone();
        let v15: Array1;
        v15 = v13.v2.clone();
        DynamicArrayClone1(&v15);
        let v16: i32;
        v16 = v14.len() as i32;
        let v17: i32;
        v17 = DynamicArrayLen1(&v15);
        let v18: i32;
        v18 = v16 + v17;
        let v19: i32;
        v19 = DynamicArrayGet1(&v15, 0);
        let v20: i32;
        v20 = v18 + v19;
        let v21: i32;
        v21 = DynamicArrayGet1(&v15, 1);
        drop(v15);
        let v22: i32;
        v22 = v20 + v21;
        v24 = v22;
    }
    if v13.v0 == 1 {
        drop(v13.v1);
    }
    drop(v13.v2);
    let v25: i32;
    v25 = v12 + v24;
    let v26: i32;
    v26 = v25 + 26;
    return v26;
}

fn main() {
    std::process::exit(spiral_main());
}
