// Generated by Spiral portable Rust backend.
#![allow(unused_mut, non_snake_case)]

fn spiral_main() -> i32 {
    let v0: i32;
    v0 = 6;
    let v1: i32;
    v1 = 7;
    let v2: i32;
    v2 = v0 + v1;
    return v2;
}

fn main() {
    std::process::exit(spiral_main());
}
