// Generated by Spiral portable Rust backend.
#![allow(unused_mut, non_snake_case)]

use std::rc::Rc;

fn SpiralStringIndex(value: &Rc<str>, index: i32) -> u8 {
    assert!(index >= 0, "negative Spiral string index");
    let bytes = value.as_bytes();
    let index = index as usize;
    assert!(index < bytes.len(), "Spiral string index out of bounds");
    bytes[index]
}

fn SpiralStringConcat(left: &Rc<str>, right: &Rc<str>) -> Rc<str> {
    let mut value = String::with_capacity(left.len() + right.len());
    value.push_str(left);
    value.push_str(right);
    Rc::<str>::from(value.into_boxed_str())
}

fn choose_left0(v0: bool) -> Rc<str> {
    if v0 {
        let v1: Rc<str>;
        v1 = Rc::<str>::from("spi");
        return v1;
    } else {
        let v2: Rc<str>;
        v2 = Rc::<str>::from("bad");
        return v2;
    }
}

fn choose_right1(v0: bool) -> Rc<str> {
    if v0 {
        let v1: Rc<str>;
        v1 = Rc::<str>::from("bad");
        return v1;
    } else {
        let v2: Rc<str>;
        v2 = Rc::<str>::from("ral");
        return v2;
    }
}

fn spiral_main() -> i32 {
    let v0: bool;
    v0 = true;
    let v1: Rc<str>;
    v1 = choose_left0(v0);
    let v2: bool;
    v2 = false;
    let v3: Rc<str>;
    v3 = choose_right1(v2);
    let v4: Rc<str>;
    v4 = SpiralStringConcat(&v1, &v3);
    let v5: i32;
    v5 = v4.len() as i32;
    let v6: bool;
    v6 = v5 == 6;
    if v6 {
        let v7: u8;
        v7 = SpiralStringIndex(&v4, 0);
        let v8: bool;
        v8 = v7 == 115;
        if v8 {
            let v9: u8;
            v9 = SpiralStringIndex(&v4, 5);
            let v10: bool;
            v10 = v9 == 108;
            if v10 {
                return 0;
            } else {
                return 1;
            }
        } else {
            return 2;
        }
    } else {
        return 3;
    }
}

fn main() {
    std::process::exit(spiral_main());
}
