#![allow(unused_mut, non_snake_case, dead_code, clippy::needless_return, clippy::too_many_arguments)]
// Generated by Spiral portable Rust backend.
use eoie_proxy_search::mnemonic_path_tag;
use std::collections::{BTreeMap, BTreeSet};

use std::fs;
use std::path::{Path, PathBuf};

#[derive(Default, Debug, Eq, PartialEq)]
struct SourceTopology {
    spiral_lines: usize,
    rust_lines: usize,
    spiral_source_files: usize,
    rust_source_files: usize,
    rust_global_sites: usize,
    rust_max_lines: usize,
    rust_max_file: String,
    cargo_crates: usize,
    spiral_packages: usize,
    package_only: usize,
    crate_max_lines: usize,
    crate_max: String,
}

#[derive(Default, Debug, Eq, PartialEq)]
struct GenericSurfaceStats {
    own_spiral_lines: usize,
    own_rust_lines: usize,
    generated_rust_lines: usize,
    vendor_spiral_lines: usize,
    vendor_rust_lines: usize,
    own_spiral_files: usize,
    own_rust_files: usize,
    generated_rust_files: usize,
    vendor_spiral_files: usize,
    vendor_rust_files: usize,
    vendor_cargo_crates: usize,
    vendor_spiral_packages: usize,
}

fn topology_arg<'a>(args: &'a [String], index: usize, name: &str) -> Result<&'a str, String> {
    args.get(index).map(String::as_str).ok_or_else(|| format!("missing argument: {name}"))
}

fn topology_skip(path: &Path) -> bool {
    matches!(path.file_name().and_then(|value| value.to_str()), Some("vendor" | "target" | ".git"))
}

fn topology_entries(path: &Path) -> Result<Vec<PathBuf>, String> {
    let mut entries = fs::read_dir(path)
        .map_err(|error| format!("read {}: {error}", path.display()))?
        .map(|entry| entry.map(|value| value.path()).map_err(|error| error.to_string()))
        .collect::<Result<Vec<_>, _>>()?;
    entries.sort();
    Ok(entries)
}

fn topology_lines(path: &Path) -> Result<usize, String> {
    let bytes = fs::read(path).map_err(|error| format!("read {}: {error}", path.display()))?;
    if bytes.is_empty() { return Ok(0); }
    Ok(bytes.iter().filter(|byte| **byte == b'\n').count() + usize::from(!bytes.ends_with(b"\n")))
}

fn topology_relative(root: &Path, path: &Path) -> String {
    path.strip_prefix(root).unwrap_or(path).to_string_lossy().replace('\\', "/")
}

#[derive(Clone, Debug, Eq, PartialEq)]
struct SourcePackageMap {
    path: String,
    cargo: bool,
    spi_files: usize,
    rust_files: usize,
    rust_lines: usize,
    main_files: usize,
    imports: usize,
    source_lines: usize,
    fingerprint: u64,
}

#[derive(Default, Debug, Eq, PartialEq)]
struct SourceDiffCounts { added: usize, removed: usize, changed: usize, unchanged: usize }

fn source_map_hash(mut hash: u64, bytes: &[u8]) -> u64 {
    for byte in bytes { hash ^= u64::from(*byte); hash = hash.wrapping_mul(1099511628211); }
    hash
}

fn source_map_package_roots(path: &Path, roots: &mut Vec<PathBuf>) -> Result<(), String> {
    if topology_skip(path) { return Ok(()); }
    if path.join("package.spiproj").is_file() { roots.push(path.to_path_buf()); }
    for child in topology_entries(path)? {
        if child.is_dir() { source_map_package_roots(&child, roots)?; }
    }
    Ok(())
}

fn source_map_owned_files(owner: &Path, path: &Path, files: &mut Vec<PathBuf>) -> Result<(), String> {
    if path != owner && path.join("package.spiproj").is_file() { return Ok(()); }
    for child in topology_entries(path)? {
        let metadata = fs::symlink_metadata(&child).map_err(|error| format!("metadata {}: {error}", child.display()))?;
        if metadata.file_type().is_symlink() { return Err(format!("spi-map rejects symlink: {}", child.display())); }
        if metadata.is_dir() {
            if !topology_skip(&child) { source_map_owned_files(owner, &child, files)?; }
        } else if metadata.is_file() && matches!(child.file_name().and_then(|value| value.to_str()), Some("Cargo.toml" | "package.spiproj")) || metadata.is_file() && matches!(child.extension().and_then(|value| value.to_str()), Some("spi" | "rs")) {
            files.push(child);
        }
    }
    Ok(())
}

fn source_map_import_count(path: &Path) -> Result<usize, String> {
    let text = fs::read_to_string(path).map_err(|error| format!("read {}: {error}", path.display()))?;
    let mut active = false;
    let mut count = 0usize;
    for line in text.lines() {
        let trimmed = line.trim();
        if trimmed == "packages:" { active = true; continue; }
        if active && !line.starts_with(' ') && !line.starts_with('\t') && !trimmed.is_empty() { active = false; }
        if active && !trimmed.is_empty() && !trimmed.starts_with("//") { count += 1; }
    }
    Ok(count)
}

fn source_map_is_cargo_crate(owner: &Path) -> Result<bool, String> {
    let manifest = owner.join("Cargo.toml");
    if !manifest.is_file() { return Ok(false); }
    let text = fs::read_to_string(&manifest).map_err(|error| format!("read {}: {error}", manifest.display()))?;
    Ok(text.lines().any(|line| line.trim() == "[package]"))
}

fn source_map_package(root: &Path, owner: &Path) -> Result<SourcePackageMap, String> {
    let mut files = Vec::new();
    source_map_owned_files(owner, owner, &mut files)?;
    files.sort();
    let mut record = SourcePackageMap {
        path: { let relative = topology_relative(&root.join("src"), owner); if relative.is_empty() { ".".to_owned() } else { relative } },
        cargo: source_map_is_cargo_crate(owner)?,
        spi_files: 0, rust_files: 0, rust_lines: 0, main_files: 0, imports: 0, source_lines: 0,
        fingerprint: 14695981039346656037,
    };
    record.imports = source_map_import_count(&owner.join("package.spiproj"))?;
    for file in files {
        let relative = topology_relative(owner, &file);
        let bytes = fs::read(&file).map_err(|error| format!("read {}: {error}", file.display()))?;
        record.fingerprint = source_map_hash(record.fingerprint, relative.as_bytes());
        record.fingerprint = source_map_hash(record.fingerprint, &[0]);
        record.fingerprint = source_map_hash(record.fingerprint, &bytes);
        match file.extension().and_then(|value| value.to_str()) {
            Some("spi") => {
                record.spi_files += 1;
                record.source_lines += topology_lines(&file)?;
                if String::from_utf8_lossy(&bytes).contains("inl main") { record.main_files += 1; }
            }
            Some("rs") => { let lines = topology_lines(&file)?; record.rust_files += 1; record.rust_lines += lines; record.source_lines += lines; }
            _ => {}
        }
    }
    if eoie_source_map_files_binding(record.spi_files as i32, record.main_files as i32) != 1 {
        return Err(format!("invalid source-map file record: {}", record.path));
    }
    if eoie_source_map_edges_binding(record.rust_files as i32, record.imports as i32) != 1 {
        return Err(format!("invalid source-map edge record: {}", record.path));
    }
    Ok(record)
}

fn source_map_collect(root: &Path) -> Result<BTreeMap<String, SourcePackageMap>, String> {
    let src = root.join("src");
    if !src.is_dir() { return Err(format!("spi-map root has no src directory: {}", root.display())); }
    let mut roots = Vec::new();
    source_map_package_roots(&src, &mut roots)?;
    roots.sort();
    roots.dedup();
    let mut map = BTreeMap::new();
    for owner in roots {
        let record = source_map_package(root, &owner)?;
        if map.insert(record.path.clone(), record).is_some() { return Err("duplicate source package path".to_owned()); }
    }
    Ok(map)
}

pub fn source_owner_rust_lines(root: &Path) -> Result<BTreeMap<String,u32>, String> {
    let map = source_map_collect(root)?;
    Ok(map.into_values().filter(|record| record.cargo && !record.path.contains('/')).map(|record| (record.path, u32::try_from(record.rust_lines).unwrap_or(u32::MAX))).collect())
}

fn source_map_diff_counts(left: &BTreeMap<String, SourcePackageMap>, right: &BTreeMap<String, SourcePackageMap>, emit: bool) -> SourceDiffCounts {
    let keys = left.keys().chain(right.keys()).cloned().collect::<BTreeSet<_>>();
    let mut counts = SourceDiffCounts::default();
    for key in keys {
        match (left.get(&key), right.get(&key)) {
            (None, Some(after)) => { counts.added += 1; if emit { println!("source-diff change=added path={} fingerprint={:016x}", key, after.fingerprint); } }
            (Some(before), None) => { counts.removed += 1; if emit { println!("source-diff change=removed path={} fingerprint={:016x}", key, before.fingerprint); } }
            (Some(before), Some(after)) if before != after => { counts.changed += 1; if emit { println!("source-diff change=changed path={} before={:016x} after={:016x}", key, before.fingerprint, after.fingerprint); } }
            (Some(_), Some(_)) => counts.unchanged += 1,
            (None, None) => {}
        }
    }
    counts
}

pub fn source_map_run(args: &[String]) -> Result<(), String> {
    let root = Path::new(topology_arg(args, 1, "root")?);
    if args.len() != 2 { return Err("spi-map expects root".to_owned()); }
    let map = source_map_collect(root)?;
    let mut cargo = 0usize;
    let mut mains = 0usize;
    let mut residuals = 0usize;
    let mut imports = 0usize;
    let mut tag_owners = BTreeMap::<String, String>::new();
    for record in map.values() {
        let tag = mnemonic_path_tag(&record.path)?;
        if let Some(previous) = tag_owners.insert(tag.clone(), record.path.clone()) {
            let collision_allowed = eoie_proxy_search::eoie_proxy_search_proxy_path_tag_collision_binding(1, i32::from(previous == record.path));
            if collision_allowed != 1 { return Err(format!("path-tag collision tag={} first={} second={}", tag, previous, record.path)); }
        }
        println!("source-tag path={} tag={}", record.path, tag);
        cargo += usize::from(record.cargo); mains += record.main_files; residuals += record.rust_files; imports += record.imports;
        println!("source-package path={} cargo={} spi_files={} rust_files={} main_files={} imports={} source_lines={} fingerprint={:016x}", record.path, record.cargo, record.spi_files, record.rust_files, record.main_files, record.imports, record.source_lines, record.fingerprint);
    }
    println!("eoie proxy spi-map ok root={} packages={} cargo_crates={} package_only={} mains={} rust_residuals={} imports={}", root.display(), map.len(), cargo, map.len().saturating_sub(cargo), mains, residuals, imports);
    Ok(())
}

pub fn source_diff_run(args: &[String]) -> Result<(), String> {
    if args.len() != 3 { return Err("spi-diff expects left-root right-root".to_owned()); }
    let left_root = Path::new(topology_arg(args, 1, "left-root")?);
    let right_root = Path::new(topology_arg(args, 2, "right-root")?);
    let left = source_map_collect(left_root)?;
    let right = source_map_collect(right_root)?;
    let counts = source_map_diff_counts(&left, &right, true);
    let total = counts.added + counts.removed + counts.changed + counts.unchanged;
    let changed = counts.added + counts.removed + counts.changed;
    if eoie_source_diff_record_binding(changed as i32, total as i32) != 1 { return Err("invalid source diff counts".to_owned()); }
    println!("eoie proxy spi-diff ok left={} right={} added={} removed={} changed={} unchanged={} total={}", left_root.display(), right_root.display(), counts.added, counts.removed, counts.changed, counts.unchanged, total);
    Ok(())
}

#[cfg(test)]
#[test]
fn source_map_and_diff_are_stable() {
    let left = topology_test_temporary("map-left");
    let right = topology_test_temporary("map-right");
    for root in [&left, &right] {
        fs::create_dir_all(root.join("src/a")).expect("create a");
        fs::write(root.join("src/a/package.spiproj"), b"modules:\n    model\n").expect("spiproj");
    }
    fs::write(left.join("src/a/model.spi"), b"inl value () : i32 = 1i32\n").expect("left model");
    fs::write(right.join("src/a/model.spi"), b"inl value () : i32 = 2i32\n").expect("right model");
    fs::create_dir_all(right.join("src/b")).expect("create b");
    fs::write(right.join("src/b/package.spiproj"), b"modules:\n    main\n").expect("b spiproj");
    fs::write(right.join("src/b/main.spi"), b"inl main () : i32 = 0i32\n").expect("b main");
    let left_map = source_map_collect(&left).expect("left map");
    let right_map = source_map_collect(&right).expect("right map");
    assert_eq!(left_map.len(), 1);
    assert_eq!(right_map.len(), 2);
    let counts = source_map_diff_counts(&left_map, &right_map, false);
    assert_eq!(counts, SourceDiffCounts { added: 1, removed: 0, changed: 1, unchanged: 0 });
    fs::remove_dir_all(left).expect("left cleanup");
    fs::remove_dir_all(right).expect("right cleanup");
}

pub fn source_generated_residual(root: &Path, path: &Path) -> Result<bool, String> {
    if path.extension().and_then(|value| value.to_str()) != Some("rs") { return Ok(false); }
    let source_root = root.join("src");
    if !path.starts_with(&source_root) { return Ok(false); }
    let Some(mut cursor) = path.parent() else { return Ok(false); };
    loop {
        if cursor.join("package.spiproj").is_file() {
            for child in topology_entries(cursor)? {
                if child.is_file() && child.extension().and_then(|value| value.to_str()) == Some("spi") { return Ok(true); }
            }
            return Ok(false);
        }
        if cursor == source_root { break; }
        let Some(parent) = cursor.parent() else { break; };
        if !parent.starts_with(&source_root) { break; }
        cursor = parent;
    }
    Ok(false)
}

pub fn source_rebuild_pairs(root: &Path) -> Result<Vec<(PathBuf,PathBuf)>, String> {
    let src = root.join("src");
    let mut roots = Vec::new();
    source_map_package_roots(&src, &mut roots)?;
    roots.sort(); roots.dedup();
    let mut pairs = Vec::new();
    let expected = source_map_collect(root)?.values().map(|record| record.rust_files).sum::<usize>();
    for owner in roots {
        if !source_map_is_cargo_crate(&owner)? { continue; }
        let manifest = fs::read_to_string(owner.join("Cargo.toml")).map_err(|e| format!("read Cargo manifest {}: {e}", owner.display()))?;
        let mut outputs = BTreeSet::new();
        let mut lib_output = None;
        let mut in_lib = false;
        for line in manifest.lines() {
            let t = line.trim();
            if t.starts_with('[') { in_lib = t == "[lib]"; }
            if let Some(rest) = t.strip_prefix("path = \"") && let Some(value) = rest.strip_suffix('\"') && value.ends_with(".rs") { let path = owner.join(value); if in_lib { lib_output = Some(path.clone()); } outputs.insert(path); }
        }
        for output in &outputs {
            let mut input = output.clone(); input.set_extension("spi");
            if input.is_file() { let text = fs::read_to_string(&input).map_err(|e| format!("read {}: {e}", input.display()))?; if !text.lines().any(|line| line.trim_start().starts_with("inl main ")) { input = PathBuf::new(); } }
            if !input.is_file() {
                let mut source_owner = output.parent().ok_or_else(|| format!("cold rebuild output has no parent: {}", output.display()))?.to_path_buf();
                while source_owner != src && !source_owner.join("package.spiproj").is_file() { source_owner = source_owner.parent().ok_or_else(|| format!("cold rebuild source owner missing: {}", output.display()))?.to_path_buf(); }
                if !source_owner.join("package.spiproj").is_file() { return Err(format!("cold rebuild package owner missing output={}", output.display())); }
                let canonical_main = source_owner.join("main.spi");
                if canonical_main.is_file() && outputs.len() == 1 && output.file_stem().and_then(|v| v.to_str()) == source_owner.file_name().and_then(|v| v.to_str()) { input = canonical_main; }
                else {
                    let mut owned_source = Vec::new(); source_map_owned_files(&source_owner, &source_owner, &mut owned_source)?;
                    let mut fallback_mains = Vec::new();
                    for file in owned_source {
                        if file.extension().and_then(|v| v.to_str()) != Some("spi") { continue; }
                        let text = fs::read_to_string(&file).map_err(|e| format!("read {}: {e}", file.display()))?;
                        if !text.lines().any(|line| line.trim_start().starts_with("inl main ")) { continue; }
                        let mut natural = file.clone(); natural.set_extension("rs");
                        if !outputs.contains(&natural) { fallback_mains.push(file); }
                    }
                    fallback_mains.sort(); fallback_mains.dedup();
                    if fallback_mains.len() == 1 { input = fallback_mains[0].clone(); }
                    else {
                        let output_stem = output.file_stem().and_then(|v| v.to_str()).ok_or_else(|| format!("cold rebuild output stem missing: {}", output.display()))?;
                        let owner_stem = source_owner.file_name().and_then(|v| v.to_str()).unwrap_or_default();
                        let output_role = if output_stem == owner_stem { "" } else if let Some(rest) = output_stem.strip_prefix(&format!("{owner_stem}_")) { rest } else { output_stem };
                        let normalize_role = |stem: &str| { let mut value = stem.to_owned(); if value == "main" { value.clear(); } for suffix in ["_main", "_probe"] { if let Some(base) = value.strip_suffix(suffix) { value = base.to_owned(); } } value };
                        let wanted = normalize_role(output_role);
                        let role_matches = fallback_mains.iter().filter(|file| file.file_stem().and_then(|v| v.to_str()).map(normalize_role).as_deref() == Some(wanted.as_str())).cloned().collect::<Vec<_>>();
                        if role_matches.len() == 1 { input = role_matches[0].clone(); }
                        else if role_matches.is_empty() && lib_output.as_ref() == Some(output) && canonical_main.is_file() { input = canonical_main; }
                        else { return Err(format!("cold rebuild source ambiguous output={} role={} fallback_mains={} role_matches={}", output.display(), wanted, fallback_mains.len(), role_matches.len())); }
                    }
                }
            }
            pairs.push((input, output.clone()));
        }
    }
    pairs.sort_by(|a,b| a.1.cmp(&b.1));
    if eoie_source_rebuild_count_binding(expected as i32, pairs.len() as i32) != 1 { return Err(format!("cold rebuild count mismatch expected={expected} observed={}", pairs.len())); }
    Ok(pairs)
}



fn source_map_files_binding0(v0: i32, v1: i32) -> i32 {
    let v2: bool = v0 < 0;
    if v2 {
        0
    } else {
        let v3: bool = v1 < 0;
        if v3 {
            0
        } else {
            let v4: bool = v0 < v1;
            if v4 {
                0
            } else {
                1
            }
        }
    }
}

fn source_map_edges_binding1(v0: i32, v1: i32) -> i32 {
    let v2: bool = v0 < 0;
    if v2 {
        0
    } else {
        let v3: bool = v1 < 0;
        if v3 {
            0
        } else {
            1
        }
    }
}

fn source_diff_record_binding2(v0: i32, v1: i32) -> i32 {
    let v2: bool = v0 < 0;
    if v2 {
        0
    } else {
        let v3: bool = v1 < 0;
        if v3 {
            0
        } else {
            let v4: bool = v1 < v0;
            if v4 {
                0
            } else {
                1
            }
        }
    }
}

fn source_rebuild_count_binding3(v0: i32, v1: i32) -> i32 {
    let v2: bool = v0 < 0;
    if v2 {
        0
    } else {
        let v3: bool = v1 < 0;
        if v3 {
            0
        } else {
            let v4: bool = v0 < v1;
            if v4 {
                0
            } else {
                let v5: bool = v1 < v0;
                if v5 {
                    0
                } else {
                    1
                }
            }
        }
    }
}

#[must_use]
pub fn eoie_source_map_files_binding(first: i32, second: i32) -> i32 {
    source_map_files_binding0(first, second)
}

#[must_use]
pub fn eoie_source_map_edges_binding(first: i32, second: i32) -> i32 {
    source_map_edges_binding1(first, second)
}

#[must_use]
pub fn eoie_source_diff_record_binding(first: i32, second: i32) -> i32 {
    source_diff_record_binding2(first, second)
}

#[must_use]
pub fn eoie_source_rebuild_count_binding(first: i32, second: i32) -> i32 {
    source_rebuild_count_binding3(first, second)
}

#[cfg(test)]
fn topology_test_temporary(label: &str) -> std::path::PathBuf { std::env::temp_dir().join(format!("eoie-source-map-{}-{}", label, std::process::id())) }
