// Generated by the Spiral compiler (TypeScript backend). Run: node --experimental-strip-types main.ts, or bun main.ts.
export function main(): number {
    let v0: number = 5;
    let v1: boolean = v0 === 5;
    if (v1) {
        return 0;
    } else {
        return 1;
    }
}
process.exitCode = main();
