// Generated by Spiral portable Rust backend.
#![allow(unused_mut, non_snake_case)]

#![allow(dead_code)]

use std::cell::RefCell;
use std::rc::Rc;

type Array0 = Rc<RefCell<Vec<i32>>>;
fn ArrayCreate0(len: i32, _init_at_zero: bool) -> Array0 {
    assert!(len >= 0, "negative Spiral array length");
    Rc::new(RefCell::new(vec![0; len as usize]))
}
fn DynamicArraySet0(array: &Array0, index: i32, value: i32) {
    assert!(index >= 0, "negative Spiral array index");
    let mut data = array.borrow_mut();
    let index = index as usize;
    assert!(index < data.len(), "Spiral array index out of bounds");
    data[index] = value;
}
fn DynamicArrayGet0(array: &Array0, index: i32) -> i32 {
    assert!(index >= 0, "negative Spiral array index");
    let data = array.borrow();
    let index = index as usize;
    assert!(index < data.len(), "Spiral array index out of bounds");
    data[index]
}
fn DynamicArrayLen0(array: &Array0) -> i32 {
    let len = array.borrow().len();
    assert!(len <= i32::MAX as usize, "Spiral array length exceeds i32");
    len as i32
}
fn DynamicArrayResize0(array: &Array0, len: i32) {
    assert!(len >= 0, "negative Spiral array length");
    array.borrow_mut().resize(len as usize, 0);
}
fn DynamicArrayReserve0(array: &Array0, capacity: i32) {
    assert!(capacity >= 0, "negative Spiral array capacity");
    let mut data = array.borrow_mut();
    let requested = capacity as usize;
    let current = data.capacity();
    if requested > current { data.reserve_exact(requested - current); }
}
fn DynamicArrayCapacity0(array: &Array0) -> i32 {
    let capacity = array.borrow().capacity();
    assert!(capacity <= i32::MAX as usize, "Spiral array capacity exceeds i32");
    capacity as i32
}
fn DynamicArrayDrop0(_array: &Array0) {}

fn method0(v0: Array0) -> () {
    let v1: i32;
    v1 = 3;
    DynamicArrayReserve0(&v0, v1);
    DynamicArrayDrop0(&v0);
    return;
}

fn method1(v0: Array0) -> i32 {
    let v1: i32;
    v1 = DynamicArrayCapacity0(&v0);
    DynamicArrayDrop0(&v0);
    return v1;
}

fn method2(v0: Array0) -> () {
    let v1: i32;
    v1 = 2;
    DynamicArrayReserve0(&v0, v1);
    DynamicArrayDrop0(&v0);
    return;
}

fn method3(v0: Array0) -> i32 {
    let v1: i32;
    v1 = DynamicArrayCapacity0(&v0);
    DynamicArrayDrop0(&v0);
    return v1;
}

fn method4(v0: Array0) -> () {
    let v1: i32;
    v1 = 3;
    DynamicArrayResize0(&v0, v1);
    DynamicArrayDrop0(&v0);
    return;
}

fn method5(v0: Array0) -> () {
    let v1: i32;
    v1 = 0;
    DynamicArrayResize0(&v0, v1);
    DynamicArrayDrop0(&v0);
    return;
}

fn method6(v0: Array0) -> () {
    let v1: i32;
    v1 = 3;
    DynamicArrayResize0(&v0, v1);
    DynamicArrayDrop0(&v0);
    return;
}

fn spiral_main() -> i32 {
    let v0: Array0;
    v0 = ArrayCreate0(0, false);
    method0(v0.clone());
    let v1: i32;
    v1 = method1(v0.clone());
    let v2: bool;
    v2 = v1 < 3;
    if v2 {
        DynamicArrayDrop0(&v0);
        return 10;
    } else {
        method2(v0.clone());
        let v3: i32;
        v3 = method3(v0.clone());
        let v4: bool;
        v4 = v3 == v1;
        if v4 {
            method4(v0.clone());
            DynamicArraySet0(&v0, 0, 4);
            DynamicArraySet0(&v0, 1, 5);
            DynamicArraySet0(&v0, 2, 6);
            method5(v0.clone());
            method6(v0.clone());
            let v5: i32;
            v5 = DynamicArrayLen0(&v0);
            let v6: i32;
            v6 = DynamicArrayGet0(&v0, 0);
            let v7: i32;
            v7 = v5 + v6;
            let v8: i32;
            v8 = DynamicArrayGet0(&v0, 1);
            let v9: i32;
            v9 = v7 + v8;
            let v10: i32;
            v10 = DynamicArrayGet0(&v0, 2);
            DynamicArrayDrop0(&v0);
            let v11: i32;
            v11 = v9 + v10;
            let v12: i32;
            v12 = v11 - 3;
            return v12;
        } else {
            DynamicArrayDrop0(&v0);
            return 11;
        }
    }
}

fn main() {
    std::process::exit(spiral_main());
}
