[package]
name = "eoie-patch-transaction-contracts"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
autotests = false

[[test]]
name = "transaction_contracts"
path = "transaction_contracts.rs"

[dependencies]
eoie-patch-compat-driver = { path = "../patch_compat_driver", features = ["test-support"] }
