#![allow(unused_mut, non_snake_case, dead_code, clippy::needless_return, clippy::too_many_arguments)]
// Generated by Spiral portable Rust backend.
use eoie_patch_compat_driver::test_support::{apply, apply_fault, bounded_read, plan, gated, gated_with_corruption, promotion_receipt_roundtrip, rehearse, restoration_receipt_paths, staged_write_mismatch, temporary};
use std::fs;

fn prepared(label: &str) -> std::path::PathBuf {
    let root = temporary(label);
    fs::create_dir_all(&root).expect("root");
    root
}

fn no_stage(root: &std::path::Path) {
    for entry in fs::read_dir(root).expect("list root") {
        let name = entry.expect("entry").file_name().to_string_lossy().into_owned();
        assert!(!name.contains(".eoie-patch-"), "residual stage: {name}");
    }
}

#[test]
fn witness_divergence_is_rejected_before_mutation() {
    let root = prepared("witness");
    fs::write(root.join("value.txt"), "old").expect("value");
    let error = apply(&root, &plan("value.txt", "old", "new"), 2).expect_err("mismatch");
    assert!(error.contains("witness mismatch"));
    assert_eq!(fs::read_to_string(root.join("value.txt")).expect("read"), "old");
    fs::remove_dir_all(root).expect("cleanup");
}

#[test]
fn empty_from_is_rejected_without_change() {
    let root = prepared("empty");
    fs::write(root.join("value.txt"), "old").expect("value");
    let error = apply(&root, &plan("value.txt", "", "new"), 1).expect_err("empty");
    assert!(error.contains("precondition failed"));
    assert_eq!(fs::read_to_string(root.join("value.txt")).expect("read"), "old");
    fs::remove_dir_all(root).expect("cleanup");
}

#[test]
fn repeated_matches_are_rejected() {
    let root = prepared("repeated");
    fs::write(root.join("value.txt"), "xxx").expect("value");
    let error = apply(&root, &plan("value.txt", "x", "y"), 1).expect_err("repeated");
    assert!(error.contains("3 matches"));
    assert_eq!(fs::read_to_string(root.join("value.txt")).expect("read"), "xxx");
    fs::remove_dir_all(root).expect("cleanup");
}

#[test]
fn overlapping_matches_are_rejected() {
    let root = prepared("overlap");
    fs::write(root.join("value.txt"), "aaa").expect("value");
    let error = apply(&root, &plan("value.txt", "aa", "b"), 1).expect_err("overlap");
    assert!(error.contains("2 matches"));
    assert_eq!(fs::read_to_string(root.join("value.txt")).expect("read"), "aaa");
    fs::remove_dir_all(root).expect("cleanup");
}

#[test]
fn late_guard_failure_preserves_all_files() {
    let root = prepared("late");
    fs::write(root.join("a.txt"), "one").expect("a");
    fs::write(root.join("b.txt"), "xx").expect("b");
    let source = format!("{}{}", plan("a.txt", "one", "changed"), plan("b.txt", "x", "y"));
    let error = apply(&root, &source, 2).expect_err("late");
    assert!(error.contains("2 matches"));
    assert_eq!(fs::read_to_string(root.join("a.txt")).expect("a"), "one");
    assert_eq!(fs::read_to_string(root.join("b.txt")).expect("b"), "xx");
    fs::remove_dir_all(root).expect("cleanup");
}

#[test]
fn parent_escape_is_rejected() {
    let root = prepared("escape");
    let error = apply(&root, &plan("../escape.txt", "old", "new"), 1).expect_err("escape");
    assert!(error.contains("unsafe relative path"));
    assert!(!root.parent().expect("parent").join("escape.txt").exists());
    fs::remove_dir_all(root).expect("cleanup");
}

#[test]
fn bounded_original_read_rejects_oversized_content() {
    let root = prepared("bounded");
    let path = root.join("value.txt");
    fs::write(&path, "four").expect("value");
    assert!(bounded_read(&path, 3).expect_err("oversized").contains("typed capture limit"));
    assert_eq!(bounded_read(&path, 4).expect("read"), "four");
    fs::remove_dir_all(root).expect("cleanup");
}

#[test]
fn typed_temporary_write_receipt_blocks_mismatch_before_promotion() {
    let root = prepared("staged");
    let error = staged_write_mismatch(&root).expect("scenario");
    assert!(error.contains("typed temporary write receipt mismatch"));
    assert_eq!(fs::read_to_string(root.join("value.txt")).expect("read"), "old");
    fs::remove_dir_all(root).expect("cleanup");
}

#[test]
fn typed_promotion_receipt_binds_stage_slot_and_target() {
    let root = prepared("promotion");
    promotion_receipt_roundtrip(&root).expect("scenario");
    assert_eq!(fs::read_to_string(root.join("target.txt")).expect("target"), "new");
    assert_eq!(fs::read_to_string(root.join("other.txt")).expect("other"), "other");
    fs::remove_dir_all(root).expect("cleanup");
}

#[test]
fn restoration_receipt_binds_selected_paths() {
    let root = prepared("restoration");
    let target = root.join("value.txt");
    assert_eq!(restoration_receipt_paths(&root).expect("restore"), vec![target.clone()]);
    assert_eq!(fs::read_to_string(target).expect("read"), "old");
    fs::remove_dir_all(root).expect("cleanup");
}

#[test]
fn injected_between_promotions_reports_successful_rollback() {
    let root = prepared("between");
    fs::write(root.join("a.txt"), "one").expect("a");
    fs::write(root.join("b.txt"), "two").expect("b");
    let source = format!("{}{}", plan("a.txt", "one", "changed-a"), plan("b.txt", "two", "changed-b"));
    let error = apply_fault(&root, &source, 2, 1).expect_err("fault");
    assert!(error.contains("rollback=restored"));
    assert!(error.contains("failed_paths=[]"));
    assert_eq!(fs::read_to_string(root.join("a.txt")).expect("a"), "one");
    no_stage(&root);
    fs::remove_dir_all(root).expect("cleanup");
}

#[test]
fn injected_restoration_failure_reports_unrestored_path() {
    let root = prepared("rollback-failure");
    fs::write(root.join("a.txt"), "one").expect("a");
    fs::write(root.join("b.txt"), "two").expect("b");
    let source = format!("{}{}", plan("a.txt", "one", "changed-a"), plan("b.txt", "two", "changed-b"));
    let error = apply_fault(&root, &source, 2, 2).expect_err("fault");
    assert!(error.contains("rollback=failed"));
    assert!(error.contains(&root.join("a.txt").display().to_string()));
    assert!(root.join("a.txt").is_dir());
    no_stage(&root);
    fs::remove_dir_all(root).expect("cleanup");
}

#[test]
fn mixed_restoration_receipt_continues_after_path_failure() {
    let root = prepared("rollback-best-effort");
    let a = root.join("a.txt");
    let b = root.join("b.txt");
    fs::write(&a, "one").expect("a");
    fs::write(&b, "two").expect("b");
    let source = format!("{}{}", plan("a.txt", "one", "changed-a"), plan("b.txt", "two", "changed-b"));
    let error = gated_with_corruption(&root, &source, 2, "b.txt").expect_err("fault");
    assert!(error.contains("rollback=failed"));
    assert!(error.contains(&format!("restored_paths=[{}]", a.display())));
    assert!(error.contains(&format!("failed_paths=[{}]", b.display())));
    assert!(error.contains(&format!("{}=>", b.display())));
    assert_eq!(fs::read_to_string(&a).expect("a restored"), "one");
    assert!(b.is_dir());
    no_stage(&root);
    fs::remove_dir_all(root).expect("cleanup");
}

#[test]
fn successful_rehearsal_restores_every_file_and_leaves_no_stage() {
    let root = prepared("rehearse");
    fs::write(root.join("a.txt"), "one").expect("a");
    fs::write(root.join("b.txt"), "two").expect("b");
    let source = format!("{}{}", plan("a.txt", "one", "changed-a"), plan("b.txt", "two", "changed-b"));
    rehearse(&root, &source, 2).expect("rehearse");
    assert_eq!(fs::read_to_string(root.join("a.txt")).expect("a"), "one");
    assert_eq!(fs::read_to_string(root.join("b.txt")).expect("b"), "two");
    no_stage(&root);
    fs::remove_dir_all(root).expect("cleanup");
}

fn rollback_contract_fnv1a(bytes: &[u8]) -> u64 { bytes.iter().fold(0xcbf29ce484222325u64, |hash, byte| (hash ^ u64::from(*byte)).wrapping_mul(0x100000001b3)) }
#[test]
fn partial_rollback_matches_restored_oracle_and_receipt() {
    let root = prepared("rollback-differential");
    let a = root.join("a.txt");
    let b = root.join("b.txt");
    let oracle = root.join("oracle-a.txt");
    fs::write(&a, "one").expect("a");
    fs::write(&b, "two").expect("b");
    fs::write(&oracle, "one").expect("oracle");
    let source = format!("{}{}", plan("a.txt", "one", "changed-a"), plan("b.txt", "two", "changed-b"));
    let error = gated_with_corruption(&root, &source, 2, "b.txt").expect_err("fault");
    assert!(error.contains("rollback=failed"));
    let oracle_bytes = fs::read(&oracle).expect("oracle bytes");
    let restored_bytes = fs::read(&a).expect("restored bytes");
    assert_eq!(restored_bytes, oracle_bytes);
    assert!(b.is_dir());
    let hash = rollback_contract_fnv1a(&oracle_bytes);
    let receipt = format!("route=partial-rollback-byte-exact\nfnv1a={hash:016x}\nbytes={}\nrestored=1\nfailed=1\n", oracle_bytes.len());
    fs::write(root.join("partial-rollback.receipt"), &receipt).expect("receipt");
    assert!(receipt.contains("bytes=3"));
    no_stage(&root);
    fs::remove_dir_all(root).expect("cleanup");
} // partial_rollback_matches_restored_oracle_and_receipt
#[test]
fn three_promotion_rollback_restores_two_and_records_one_failure() {
    let root = prepared("rollback-three-promotions");
    let a = root.join("a.txt"); let b = root.join("b.txt"); let c = root.join("c.txt");
    let oracle_a = root.join("oracle-a.txt"); let oracle_b = root.join("oracle-b.txt");
    fs::write(&a, "one").expect("a"); fs::write(&b, "two").expect("b"); fs::write(&c, "three").expect("c");
    fs::write(&oracle_a, "one").expect("oracle a"); fs::write(&oracle_b, "two").expect("oracle b");
    let source = format!("{}{}{}", plan("a.txt", "one", "changed-a"), plan("b.txt", "two", "changed-b"), plan("c.txt", "three", "changed-c"));
    let error = gated_with_corruption(&root, &source, 3, "c.txt").expect_err("fault");
    assert!(error.contains("rollback=failed"));
    let a_bytes = fs::read(&a).expect("a restored"); let b_bytes = fs::read(&b).expect("b restored");
    assert_eq!(a_bytes, fs::read(&oracle_a).expect("oracle a bytes")); assert_eq!(b_bytes, fs::read(&oracle_b).expect("oracle b bytes")); assert!(c.is_dir());
    let mut restored = a_bytes.clone(); restored.extend_from_slice(&b_bytes); let hash = rollback_contract_fnv1a(&restored);
    let receipt = format!("route=three-promotion-partial-rollback-byte-exact\nfnv1a={hash:016x}\nbytes={}\nrestored=2\nfailed=1\n", restored.len());
    fs::write(root.join("three-promotion-rollback.receipt"), &receipt).expect("receipt");
    assert!(receipt.contains("restored=2")); assert!(receipt.contains("failed=1"));
    no_stage(&root); fs::remove_dir_all(root).expect("cleanup");
} // three_promotion_rollback_restores_two_and_records_one_failure
#[test]
fn postgate_failure_after_all_promotions_restores_every_file() {
    let root = prepared("postgate-after-promotions");
    let a = root.join("a.txt"); let b = root.join("b.txt");
    fs::write(&a, "one").expect("a"); fs::write(&b, "two").expect("b");
    let source = format!("{}{}", plan("a.txt", "one", "changed-a"), plan("b.txt", "two", "changed-b"));
    let error = gated(&root, &source, 2, false).expect_err("postgate fault");
    assert!(error.contains("patch executable postgate rejected"));
    assert!(error.contains("rollback=restored"));
    assert_eq!(fs::read_to_string(&a).expect("a restored"), "one");
    assert_eq!(fs::read_to_string(&b).expect("b restored"), "two");
    no_stage(&root); fs::remove_dir_all(root).expect("cleanup");
} // postgate_failure_after_all_promotions_restores_every_file
#[test]
fn executable_gate_success_commits_every_file() {
    let root = prepared("executable-gate-success");
    let a = root.join("a.txt"); let b = root.join("b.txt");
    fs::write(&a, "one").expect("a"); fs::write(&b, "two").expect("b");
    let source = format!("{}{}", plan("a.txt", "one", "changed-a"), plan("b.txt", "two", "changed-b"));
    gated(&root, &source, 2, true).expect("gate pass");
    assert_eq!(fs::read_to_string(&a).expect("a committed"), "changed-a");
    assert_eq!(fs::read_to_string(&b).expect("b committed"), "changed-b");
    no_stage(&root); fs::remove_dir_all(root).expect("cleanup");
} // executable_gate_success_commits_every_file
#[test]
fn executable_gate_failure_restores_every_file() {
    let root = prepared("executable-gate-failure");
    let a = root.join("a.txt"); let b = root.join("b.txt");
    fs::write(&a, "one").expect("a"); fs::write(&b, "two").expect("b");
    let source = format!("{}{}", plan("a.txt", "one", "changed-a"), plan("b.txt", "two", "changed-b"));
    let error = gated(&root, &source, 2, false).expect_err("gate reject");
    assert!(error.contains("patch executable postgate rejected"));
    assert!(error.contains("rollback=restored"));
    assert_eq!(fs::read_to_string(&a).expect("a restored"), "one");
    assert_eq!(fs::read_to_string(&b).expect("b restored"), "two");
    no_stage(&root); fs::remove_dir_all(root).expect("cleanup");
} // executable_gate_failure_restores_every_file


fn spiral_main() -> i32 {
    0
}

fn main() {
    std::process::exit(spiral_main());
}
