// Generated by Spiral portable Rust backend.
#![allow(unused_mut, non_snake_case)]

use std::rc::Rc;

#[derive(Clone)]
struct Tuple0 {
    v0: Rc<str>,
    v1: i32,
}

fn TupleCreate0(v0: Rc<str>, v1: i32) -> Tuple0 {
    Tuple0 { v0, v1 }
}

fn method0(v0: Rc<str>) -> Tuple0 {
    let v1: i32;
    v1 = v0.len() as i32;
    return TupleCreate0(v0.clone(), v1);
}

fn score1(v0: i32, v1: Rc<str>) -> i32 {
    let v2: i32;
    v2 = v1.len() as i32;
    let v3: i32;
    v3 = v2 + v0;
    return v3;
}

fn spiral_main() -> i32 {
    let v0: Rc<str>;
    v0 = Rc::<str>::from("qwe");
    let v1: Rc<str>;
    let v2: i32;
    let tmp0: Tuple0;
    tmp0 = method0(v0.clone());
    v1 = tmp0.v0;
    v2 = tmp0.v1;
    let v3: i32;
    v3 = score1(v2, v1.clone());
    let v4: i32;
    v4 = score1(v2, v1.clone());
    let v5: i32;
    v5 = v3 + v4;
    let v6: i32;
    v6 = v5 - 12;
    return v6;
}

fn main() {
    std::process::exit(spiral_main());
}
