// Generated by Spiral portable Rust backend.
#![allow(unused_mut, non_snake_case)]

use std::rc::Rc;

fn spiral_main() -> i32 {
    let v0_0: Rc<str>;
    let v0_1: Rc<str>;
    let v1: Rc<str>;
    v1 = Rc::<str>::from("ab");
    v0_0 = v1;
    let v2: Rc<str>;
    v2 = Rc::<str>::from("cde");
    v0_1 = v2;
    let v3: Rc<str>;
    v3 = v0_0;
    let v4: Rc<str>;
    v4 = v0_1;
    let v5: i32;
    v5 = v3.len() as i32;
    let v6: i32;
    v6 = v4.len() as i32;
    let v7: i32;
    v7 = v5 + v6;
    let v8: i32;
    v8 = v7 - 5;
    return v8;
}

fn main() {
    std::process::exit(spiral_main());
}
