#![allow(unused_mut, non_snake_case, dead_code, clippy::needless_return, clippy::too_many_arguments)]
// Generated by Spiral portable Rust backend.

use std::rc::Rc;

fn SpiralStringIndex(value: &Rc<str>, index: i32) -> u8 {
    assert!(index >= 0, "negative Spiral string index");
    let bytes = value.as_bytes();
    let index = index as usize;
    assert!(index < bytes.len(), "Spiral string index out of bounds");
    bytes[index]
}

fn SpiralStringSlice(value: &Rc<str>, from_index: i32, to_index: i32) -> Rc<str> {
    assert!(from_index >= 0, "negative Spiral string slice start");
    let bytes = value.as_bytes();
    let length = bytes.len() as i32;
    assert!(from_index <= length, "Spiral string slice start out of bounds");
    assert!(to_index >= from_index - 1, "invalid Spiral string slice range");
    assert!(to_index < length, "Spiral string slice end out of bounds");
    if to_index < from_index { return Rc::<str>::from(""); }
    let from_index = from_index as usize;
    let to_index = to_index as usize;
    let slice = &bytes[from_index..=to_index];
    Rc::<str>::from(std::str::from_utf8(slice).expect("Spiral string slice must preserve UTF-8 boundaries"))
}

fn SpiralStringConcat(left: &Rc<str>, right: &Rc<str>) -> Rc<str> {
    let mut value = String::with_capacity(left.len() + right.len());
    value.push_str(left);
    value.push_str(right);
    Rc::<str>::from(value.into_boxed_str())
}

fn starts_with_loop2(mut v0: Rc<str>, mut v1: Rc<str>, mut v2: i32, mut v3: i32, mut v4: i32) -> bool {
    'spiral_tail: loop {
        let v5: bool = v3 == v4;
        if v5 {
            return true;
        } else {
            let v6: u8 = SpiralStringIndex(&v0, v2);
            let v7: u8 = SpiralStringIndex(&v1, v3);
            let v8: bool = v6 == v7;
            if v8 {
                let v9: i32 = v2 + 1;
                let v10: i32 = v3 + 1;
                let __spiral_tail_arg0: Rc<str> = v0.clone();
                let __spiral_tail_arg1: Rc<str> = v1.clone();
                let __spiral_tail_arg2: i32 = v9;
                let __spiral_tail_arg3: i32 = v10;
                let __spiral_tail_arg4: i32 = v4;
                v0 = __spiral_tail_arg0;
                v1 = __spiral_tail_arg1;
                v2 = __spiral_tail_arg2;
                v3 = __spiral_tail_arg3;
                v4 = __spiral_tail_arg4;
                continue 'spiral_tail;
            } else {
                return false;
            }
        }
    }
}

fn find_text_loop1(mut v0: Rc<str>, mut v1: Rc<str>, mut v2: i32, mut v3: i32, mut v4: i32) -> i32 {
    'spiral_tail: loop {
        let v5: i32 = v2 + v4;
        let v6: bool = v3 < v5;
        if v6 {
            return v3;
        } else {
            let v7: i32 = v0.len() as i32;
            let v8: i32 = v1.len() as i32;
            let v9: i32 = v2 + v8;
            let v10: bool = v7 < v9;
            let mut v13: bool;
            if v10 {
                v13 = false;
            } else {
                let v11: i32 = 0;
                v13 = starts_with_loop2(v0.clone(), v1.clone(), v2, v11, v8);
            }
            if v13 {
                return v2;
            } else {
                let v14: i32 = v2 + 1;
                let __spiral_tail_arg0: Rc<str> = v0.clone();
                let __spiral_tail_arg1: Rc<str> = v1.clone();
                let __spiral_tail_arg2: i32 = v14;
                let __spiral_tail_arg3: i32 = v3;
                let __spiral_tail_arg4: i32 = v4;
                v0 = __spiral_tail_arg0;
                v1 = __spiral_tail_arg1;
                v2 = __spiral_tail_arg2;
                v3 = __spiral_tail_arg3;
                v4 = __spiral_tail_arg4;
                continue 'spiral_tail;
            }
        }
    }
}

fn method4() -> Rc<str> {
    let v0: Rc<str> = Rc::<str>::from("");
    v0
}

fn codec_empty3() -> Rc<str> {
    method4()
}

fn codec_runtime_char5(v0: Rc<str>) -> u8 {
    let v1: u8 = SpiralStringIndex(&v0, 0);
    v1
}

fn find_char_loop6(mut v0: Rc<str>, mut v1: i32, mut v2: i32, mut v3: u8) -> i32 {
    'spiral_tail: loop {
        let v4: bool = v1 == v2;
        if v4 {
            return v2;
        } else {
            let v5: u8 = SpiralStringIndex(&v0, v1);
            let v6: bool = v5 == v3;
            if v6 {
                return v1;
            } else {
                let v7: i32 = v1 + 1;
                let __spiral_tail_arg0: Rc<str> = v0.clone();
                let __spiral_tail_arg1: i32 = v7;
                let __spiral_tail_arg2: i32 = v2;
                let __spiral_tail_arg3: u8 = v3;
                v0 = __spiral_tail_arg0;
                v1 = __spiral_tail_arg1;
                v2 = __spiral_tail_arg2;
                v3 = __spiral_tail_arg3;
                continue 'spiral_tail;
            }
        }
    }
}

fn projection_find_digit_loop7(mut v0: Rc<str>, mut v1: i32, mut v2: i32) -> i32 {
    'spiral_tail: loop {
        let v3: bool = v1 == v2;
        if v3 {
            return v2;
        } else {
            let v4: u8 = SpiralStringIndex(&v0, v1);
            let v5: bool = v4 == 48;
            let mut v24: u64;
            if v5 {
                v24 = 0;
            } else {
                let v6: bool = v4 == 49;
                if v6 {
                    v24 = 1;
                } else {
                    let v7: bool = v4 == 50;
                    if v7 {
                        v24 = 2;
                    } else {
                        let v8: bool = v4 == 51;
                        if v8 {
                            v24 = 3;
                        } else {
                            let v9: bool = v4 == 52;
                            if v9 {
                                v24 = 4;
                            } else {
                                let v10: bool = v4 == 53;
                                if v10 {
                                    v24 = 5;
                                } else {
                                    let v11: bool = v4 == 54;
                                    if v11 {
                                        v24 = 6;
                                    } else {
                                        let v12: bool = v4 == 55;
                                        if v12 {
                                            v24 = 7;
                                        } else {
                                            let v13: bool = v4 == 56;
                                            if v13 {
                                                v24 = 8;
                                            } else {
                                                let v14: bool = v4 == 57;
                                                if v14 {
                                                    v24 = 9;
                                                } else {
                                                    v24 = 10;
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
            let v25: bool = v24 < 10;
            if v25 {
                return v1;
            } else {
                let v26: i32 = v1 + 1;
                let __spiral_tail_arg0: Rc<str> = v0.clone();
                let __spiral_tail_arg1: i32 = v26;
                let __spiral_tail_arg2: i32 = v2;
                v0 = __spiral_tail_arg0;
                v1 = __spiral_tail_arg1;
                v2 = __spiral_tail_arg2;
                continue 'spiral_tail;
            }
        }
    }
}

fn codec_u64_decimal_valid_loop9(mut v0: Rc<str>, mut v1: i32, mut v2: i32, mut v3: u64) -> bool {
    'spiral_tail: loop {
        let v4: bool = v1 == v2;
        if v4 {
            return true;
        } else {
            let v5: u8 = SpiralStringIndex(&v0, v1);
            let v6: bool = v5 == 48;
            let mut v25: u64;
            if v6 {
                v25 = 0;
            } else {
                let v7: bool = v5 == 49;
                if v7 {
                    v25 = 1;
                } else {
                    let v8: bool = v5 == 50;
                    if v8 {
                        v25 = 2;
                    } else {
                        let v9: bool = v5 == 51;
                        if v9 {
                            v25 = 3;
                        } else {
                            let v10: bool = v5 == 52;
                            if v10 {
                                v25 = 4;
                            } else {
                                let v11: bool = v5 == 53;
                                if v11 {
                                    v25 = 5;
                                } else {
                                    let v12: bool = v5 == 54;
                                    if v12 {
                                        v25 = 6;
                                    } else {
                                        let v13: bool = v5 == 55;
                                        if v13 {
                                            v25 = 7;
                                        } else {
                                            let v14: bool = v5 == 56;
                                            if v14 {
                                                v25 = 8;
                                            } else {
                                                let v15: bool = v5 == 57;
                                                if v15 {
                                                    v25 = 9;
                                                } else {
                                                    v25 = 10;
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
            let v26: bool = v25 == 10;
            if v26 {
                return false;
            } else {
                let v27: bool = v3 > 1844674407370955161;
                if v27 {
                    return false;
                } else {
                    let v28: bool = v3 == 1844674407370955161;
                    if v28 {
                        let v29: bool = v25 > 5;
                        if v29 {
                            return false;
                        } else {
                            let v30: i32 = v1 + 1;
                            let v31: u64 = v3 * 10;
                            let v32: u64 = v31 + v25;
                            let __spiral_tail_arg0: Rc<str> = v0.clone();
                            let __spiral_tail_arg1: i32 = v30;
                            let __spiral_tail_arg2: i32 = v2;
                            let __spiral_tail_arg3: u64 = v32;
                            v0 = __spiral_tail_arg0;
                            v1 = __spiral_tail_arg1;
                            v2 = __spiral_tail_arg2;
                            v3 = __spiral_tail_arg3;
                            continue 'spiral_tail;
                        }
                    } else {
                        let v35: i32 = v1 + 1;
                        let v36: u64 = v3 * 10;
                        let v37: u64 = v36 + v25;
                        let __spiral_tail_arg0: Rc<str> = v0.clone();
                        let __spiral_tail_arg1: i32 = v35;
                        let __spiral_tail_arg2: i32 = v2;
                        let __spiral_tail_arg3: u64 = v37;
                        v0 = __spiral_tail_arg0;
                        v1 = __spiral_tail_arg1;
                        v2 = __spiral_tail_arg2;
                        v3 = __spiral_tail_arg3;
                        continue 'spiral_tail;
                    }
                }
            }
        }
    }
}

fn codec_u64_decimal_normalize8(v0: Rc<str>) -> Rc<str> {
    let v1: i32 = v0.len() as i32;
    let v2: bool = v1 == 0;
    if v2 {
        codec_empty3()
    } else {
        let v4: i32 = 0;
        let v5: u64 = 0;
        let v6: bool = codec_u64_decimal_valid_loop9(v0.clone(), v4, v1, v5);
        if v6 {
            v0
        } else {
            codec_empty3()
        }
    }
}

fn handoff_ratings_projection0(v0: Rc<str>) -> Rc<str> {
    let v1: i32 = v0.len() as i32;
    let v2: Rc<str> = Rc::<str>::from("inl active_codebase_readiness");
    let v3: i32 = 0;
    let v4: i32 = 29;
    let v5: i32 = find_text_loop1(v0.clone(), v2.clone(), v3, v1, v4);
    let v6: bool = v5 == v1;
    let mut v16: Rc<str>;
    if v6 {
        v16 = codec_empty3();
    } else {
        let v8: Rc<str> = Rc::<str>::from("\n");
        let v9: u8 = codec_runtime_char5(v8.clone());
        let v10: i32 = find_char_loop6(v0.clone(), v5, v1, v9);
        let v11: bool = v5 == v10;
        if v11 {
            v16 = codec_empty3();
        } else {
            let v13: i32 = v10 - 1;
            let v14: Rc<str> = SpiralStringSlice(&v0, v5, v13);
            v16 = v14;
        }
    }
    let v17: i32 = v16.len() as i32;
    let v18: bool = v17 == 0;
    let mut v43: Rc<str>;
    if v18 {
        v43 = codec_empty3();
    } else {
        let v20: i32 = 0;
        let v21: u8 = 61;
        let v22: i32 = find_char_loop6(v16.clone(), v20, v17, v21);
        let v23: bool = v22 == v17;
        if v23 {
            v43 = codec_empty3();
        } else {
            let v25: i32 = v22 + 1;
            let v26: i32 = projection_find_digit_loop7(v16.clone(), v25, v17);
            let v27: bool = v26 == v17;
            if v27 {
                v43 = codec_empty3();
            } else {
                let v29: Rc<str> = Rc::<str>::from("u32");
                let v30: i32 = 3;
                let v31: i32 = find_text_loop1(v16.clone(), v29.clone(), v26, v17, v30);
                let v32: bool = v31 == v17;
                if v32 {
                    v43 = codec_empty3();
                } else {
                    let v34: bool = v26 == v31;
                    let mut v38: Rc<str>;
                    if v34 {
                        v38 = codec_empty3();
                    } else {
                        let v36: i32 = v31 - 1;
                        let v37: Rc<str> = SpiralStringSlice(&v16, v26, v36);
                        v38 = v37;
                    }
                    v43 = codec_u64_decimal_normalize8(v38.clone());
                }
            }
        }
    }
    let v44: Rc<str> = Rc::<str>::from("inl subjective_phase_ceiling");
    let v45: i32 = 0;
    let v46: i32 = 28;
    let v47: i32 = find_text_loop1(v0.clone(), v44.clone(), v45, v1, v46);
    let v48: bool = v47 == v1;
    let mut v58: Rc<str>;
    if v48 {
        v58 = codec_empty3();
    } else {
        let v50: Rc<str> = Rc::<str>::from("\n");
        let v51: u8 = codec_runtime_char5(v50.clone());
        let v52: i32 = find_char_loop6(v0.clone(), v47, v1, v51);
        let v53: bool = v47 == v52;
        if v53 {
            v58 = codec_empty3();
        } else {
            let v55: i32 = v52 - 1;
            let v56: Rc<str> = SpiralStringSlice(&v0, v47, v55);
            v58 = v56;
        }
    }
    let v59: i32 = v58.len() as i32;
    let v60: bool = v59 == 0;
    let mut v85: Rc<str>;
    if v60 {
        v85 = codec_empty3();
    } else {
        let v62: i32 = 0;
        let v63: u8 = 61;
        let v64: i32 = find_char_loop6(v58.clone(), v62, v59, v63);
        let v65: bool = v64 == v59;
        if v65 {
            v85 = codec_empty3();
        } else {
            let v67: i32 = v64 + 1;
            let v68: i32 = projection_find_digit_loop7(v58.clone(), v67, v59);
            let v69: bool = v68 == v59;
            if v69 {
                v85 = codec_empty3();
            } else {
                let v71: Rc<str> = Rc::<str>::from("u32");
                let v72: i32 = 3;
                let v73: i32 = find_text_loop1(v58.clone(), v71.clone(), v68, v59, v72);
                let v74: bool = v73 == v59;
                if v74 {
                    v85 = codec_empty3();
                } else {
                    let v76: bool = v68 == v73;
                    let mut v80: Rc<str>;
                    if v76 {
                        v80 = codec_empty3();
                    } else {
                        let v78: i32 = v73 - 1;
                        let v79: Rc<str> = SpiralStringSlice(&v58, v68, v78);
                        v80 = v79;
                    }
                    v85 = codec_u64_decimal_normalize8(v80.clone());
                }
            }
        }
    }
    let v86: Rc<str> = Rc::<str>::from("inl active_coverage_attainment");
    let v87: i32 = 0;
    let v88: i32 = 30;
    let v89: i32 = find_text_loop1(v0.clone(), v86.clone(), v87, v1, v88);
    let v90: bool = v89 == v1;
    let mut v100: Rc<str>;
    if v90 {
        v100 = codec_empty3();
    } else {
        let v92: Rc<str> = Rc::<str>::from("\n");
        let v93: u8 = codec_runtime_char5(v92.clone());
        let v94: i32 = find_char_loop6(v0.clone(), v89, v1, v93);
        let v95: bool = v89 == v94;
        if v95 {
            v100 = codec_empty3();
        } else {
            let v97: i32 = v94 - 1;
            let v98: Rc<str> = SpiralStringSlice(&v0, v89, v97);
            v100 = v98;
        }
    }
    let v101: i32 = v100.len() as i32;
    let v102: bool = v101 == 0;
    let mut v127: Rc<str>;
    if v102 {
        v127 = codec_empty3();
    } else {
        let v104: i32 = 0;
        let v105: u8 = 61;
        let v106: i32 = find_char_loop6(v100.clone(), v104, v101, v105);
        let v107: bool = v106 == v101;
        if v107 {
            v127 = codec_empty3();
        } else {
            let v109: i32 = v106 + 1;
            let v110: i32 = projection_find_digit_loop7(v100.clone(), v109, v101);
            let v111: bool = v110 == v101;
            if v111 {
                v127 = codec_empty3();
            } else {
                let v113: Rc<str> = Rc::<str>::from("u32");
                let v114: i32 = 3;
                let v115: i32 = find_text_loop1(v100.clone(), v113.clone(), v110, v101, v114);
                let v116: bool = v115 == v101;
                if v116 {
                    v127 = codec_empty3();
                } else {
                    let v118: bool = v110 == v115;
                    let mut v122: Rc<str>;
                    if v118 {
                        v122 = codec_empty3();
                    } else {
                        let v120: i32 = v115 - 1;
                        let v121: Rc<str> = SpiralStringSlice(&v100, v110, v120);
                        v122 = v121;
                    }
                    v127 = codec_u64_decimal_normalize8(v122.clone());
                }
            }
        }
    }
    let v128: Rc<str> = Rc::<str>::from("inl phase_runtime_drift");
    let v129: i32 = 0;
    let v130: i32 = 23;
    let v131: i32 = find_text_loop1(v0.clone(), v128.clone(), v129, v1, v130);
    let v132: bool = v131 == v1;
    let mut v142: Rc<str>;
    if v132 {
        v142 = codec_empty3();
    } else {
        let v134: Rc<str> = Rc::<str>::from("\n");
        let v135: u8 = codec_runtime_char5(v134.clone());
        let v136: i32 = find_char_loop6(v0.clone(), v131, v1, v135);
        let v137: bool = v131 == v136;
        if v137 {
            v142 = codec_empty3();
        } else {
            let v139: i32 = v136 - 1;
            let v140: Rc<str> = SpiralStringSlice(&v0, v131, v139);
            v142 = v140;
        }
    }
    let v143: i32 = v142.len() as i32;
    let v144: bool = v143 == 0;
    let mut v169: Rc<str>;
    if v144 {
        v169 = codec_empty3();
    } else {
        let v146: i32 = 0;
        let v147: u8 = 61;
        let v148: i32 = find_char_loop6(v142.clone(), v146, v143, v147);
        let v149: bool = v148 == v143;
        if v149 {
            v169 = codec_empty3();
        } else {
            let v151: i32 = v148 + 1;
            let v152: i32 = projection_find_digit_loop7(v142.clone(), v151, v143);
            let v153: bool = v152 == v143;
            if v153 {
                v169 = codec_empty3();
            } else {
                let v155: Rc<str> = Rc::<str>::from("u32");
                let v156: i32 = 3;
                let v157: i32 = find_text_loop1(v142.clone(), v155.clone(), v152, v143, v156);
                let v158: bool = v157 == v143;
                if v158 {
                    v169 = codec_empty3();
                } else {
                    let v160: bool = v152 == v157;
                    let mut v164: Rc<str>;
                    if v160 {
                        v164 = codec_empty3();
                    } else {
                        let v162: i32 = v157 - 1;
                        let v163: Rc<str> = SpiralStringSlice(&v142, v152, v162);
                        v164 = v163;
                    }
                    v169 = codec_u64_decimal_normalize8(v164.clone());
                }
            }
        }
    }
    let v170: Rc<str> = Rc::<str>::from("inl phase_parallel_readiness");
    let v171: i32 = 0;
    let v172: i32 = 28;
    let v173: i32 = find_text_loop1(v0.clone(), v170.clone(), v171, v1, v172);
    let v174: bool = v173 == v1;
    let mut v184: Rc<str>;
    if v174 {
        v184 = codec_empty3();
    } else {
        let v176: Rc<str> = Rc::<str>::from("\n");
        let v177: u8 = codec_runtime_char5(v176.clone());
        let v178: i32 = find_char_loop6(v0.clone(), v173, v1, v177);
        let v179: bool = v173 == v178;
        if v179 {
            v184 = codec_empty3();
        } else {
            let v181: i32 = v178 - 1;
            let v182: Rc<str> = SpiralStringSlice(&v0, v173, v181);
            v184 = v182;
        }
    }
    let v185: i32 = v184.len() as i32;
    let v186: bool = v185 == 0;
    let mut v211: Rc<str>;
    if v186 {
        v211 = codec_empty3();
    } else {
        let v188: i32 = 0;
        let v189: u8 = 61;
        let v190: i32 = find_char_loop6(v184.clone(), v188, v185, v189);
        let v191: bool = v190 == v185;
        if v191 {
            v211 = codec_empty3();
        } else {
            let v193: i32 = v190 + 1;
            let v194: i32 = projection_find_digit_loop7(v184.clone(), v193, v185);
            let v195: bool = v194 == v185;
            if v195 {
                v211 = codec_empty3();
            } else {
                let v197: Rc<str> = Rc::<str>::from("u32");
                let v198: i32 = 3;
                let v199: i32 = find_text_loop1(v184.clone(), v197.clone(), v194, v185, v198);
                let v200: bool = v199 == v185;
                if v200 {
                    v211 = codec_empty3();
                } else {
                    let v202: bool = v194 == v199;
                    let mut v206: Rc<str>;
                    if v202 {
                        v206 = codec_empty3();
                    } else {
                        let v204: i32 = v199 - 1;
                        let v205: Rc<str> = SpiralStringSlice(&v184, v194, v204);
                        v206 = v205;
                    }
                    v211 = codec_u64_decimal_normalize8(v206.clone());
                }
            }
        }
    }
    let v212: Rc<str> = Rc::<str>::from("inl phase_plan_ir");
    let v213: i32 = 0;
    let v214: i32 = 17;
    let v215: i32 = find_text_loop1(v0.clone(), v212.clone(), v213, v1, v214);
    let v216: bool = v215 == v1;
    let mut v226: Rc<str>;
    if v216 {
        v226 = codec_empty3();
    } else {
        let v218: Rc<str> = Rc::<str>::from("\n");
        let v219: u8 = codec_runtime_char5(v218.clone());
        let v220: i32 = find_char_loop6(v0.clone(), v215, v1, v219);
        let v221: bool = v215 == v220;
        if v221 {
            v226 = codec_empty3();
        } else {
            let v223: i32 = v220 - 1;
            let v224: Rc<str> = SpiralStringSlice(&v0, v215, v223);
            v226 = v224;
        }
    }
    let v227: i32 = v226.len() as i32;
    let v228: bool = v227 == 0;
    let mut v253: Rc<str>;
    if v228 {
        v253 = codec_empty3();
    } else {
        let v230: i32 = 0;
        let v231: u8 = 61;
        let v232: i32 = find_char_loop6(v226.clone(), v230, v227, v231);
        let v233: bool = v232 == v227;
        if v233 {
            v253 = codec_empty3();
        } else {
            let v235: i32 = v232 + 1;
            let v236: i32 = projection_find_digit_loop7(v226.clone(), v235, v227);
            let v237: bool = v236 == v227;
            if v237 {
                v253 = codec_empty3();
            } else {
                let v239: Rc<str> = Rc::<str>::from("u32");
                let v240: i32 = 3;
                let v241: i32 = find_text_loop1(v226.clone(), v239.clone(), v236, v227, v240);
                let v242: bool = v241 == v227;
                if v242 {
                    v253 = codec_empty3();
                } else {
                    let v244: bool = v236 == v241;
                    let mut v248: Rc<str>;
                    if v244 {
                        v248 = codec_empty3();
                    } else {
                        let v246: i32 = v241 - 1;
                        let v247: Rc<str> = SpiralStringSlice(&v226, v236, v246);
                        v248 = v247;
                    }
                    v253 = codec_u64_decimal_normalize8(v248.clone());
                }
            }
        }
    }
    let v254: Rc<str> = Rc::<str>::from("inl migration ()");
    let v255: i32 = 0;
    let v256: i32 = 16;
    let v257: i32 = find_text_loop1(v0.clone(), v254.clone(), v255, v1, v256);
    let v258: bool = v257 == v1;
    let mut v268: Rc<str>;
    if v258 {
        v268 = codec_empty3();
    } else {
        let v260: Rc<str> = Rc::<str>::from("\n");
        let v261: u8 = codec_runtime_char5(v260.clone());
        let v262: i32 = find_char_loop6(v0.clone(), v257, v1, v261);
        let v263: bool = v257 == v262;
        if v263 {
            v268 = codec_empty3();
        } else {
            let v265: i32 = v262 - 1;
            let v266: Rc<str> = SpiralStringSlice(&v0, v257, v265);
            v268 = v266;
        }
    }
    let v269: i32 = v268.len() as i32;
    let v270: bool = v269 == 0;
    let mut v295: Rc<str>;
    if v270 {
        v295 = codec_empty3();
    } else {
        let v272: i32 = 0;
        let v273: u8 = 61;
        let v274: i32 = find_char_loop6(v268.clone(), v272, v269, v273);
        let v275: bool = v274 == v269;
        if v275 {
            v295 = codec_empty3();
        } else {
            let v277: i32 = v274 + 1;
            let v278: i32 = projection_find_digit_loop7(v268.clone(), v277, v269);
            let v279: bool = v278 == v269;
            if v279 {
                v295 = codec_empty3();
            } else {
                let v281: Rc<str> = Rc::<str>::from("u32");
                let v282: i32 = 3;
                let v283: i32 = find_text_loop1(v268.clone(), v281.clone(), v278, v269, v282);
                let v284: bool = v283 == v269;
                if v284 {
                    v295 = codec_empty3();
                } else {
                    let v286: bool = v278 == v283;
                    let mut v290: Rc<str>;
                    if v286 {
                        v290 = codec_empty3();
                    } else {
                        let v288: i32 = v283 - 1;
                        let v289: Rc<str> = SpiralStringSlice(&v268, v278, v288);
                        v290 = v289;
                    }
                    v295 = codec_u64_decimal_normalize8(v290.clone());
                }
            }
        }
    }
    let v296: Rc<str> = Rc::<str>::from("");
    let v297: bool = v43 == v296;
    if v297 {
        codec_empty3()
    } else {
        let v299: bool = v85 == v296;
        if v299 {
            codec_empty3()
        } else {
            let v301: bool = v127 == v296;
            if v301 {
                codec_empty3()
            } else {
                let v303: bool = v169 == v296;
                if v303 {
                    codec_empty3()
                } else {
                    let v305: bool = v211 == v296;
                    if v305 {
                        codec_empty3()
                    } else {
                        let v307: bool = v253 == v296;
                        if v307 {
                            codec_empty3()
                        } else {
                            let v309: bool = v295 == v296;
                            if v309 {
                                codec_empty3()
                            } else {
                                let v311: Rc<str> = SpiralStringConcat(&Rc::<str>::from("active_readiness="), &v43);
                                let v312: Rc<str> = SpiralStringConcat(&v311, &Rc::<str>::from("/1000 subjective_ceiling="));
                                let v313: Rc<str> = SpiralStringConcat(&v312, &v85);
                                let v314: Rc<str> = SpiralStringConcat(&v313, &Rc::<str>::from("/1000 coverage="));
                                let v315: Rc<str> = SpiralStringConcat(&v314, &v127);
                                let v316: Rc<str> = SpiralStringConcat(&v315, &Rc::<str>::from("/1000 runtime_drift="));
                                let v317: Rc<str> = SpiralStringConcat(&v316, &v169);
                                let v318: Rc<str> = SpiralStringConcat(&v317, &Rc::<str>::from("/1000 parallel_readiness="));
                                let v319: Rc<str> = SpiralStringConcat(&v318, &v211);
                                let v320: Rc<str> = SpiralStringConcat(&v319, &Rc::<str>::from("/1000 canonical_plan_ir="));
                                let v321: Rc<str> = SpiralStringConcat(&v320, &v253);
                                let v322: Rc<str> = SpiralStringConcat(&v321, &Rc::<str>::from("/1000 migration_historical="));
                                let v323: Rc<str> = SpiralStringConcat(&v322, &v295);
                                let v324: Rc<str> = SpiralStringConcat(&v323, &Rc::<str>::from("/1000"));
                                v324
                            }
                        }
                    }
                }
            }
        }
    }
}

fn projection_census_loop11(mut v0: Rc<str>, mut v1: i32, mut v2: i32, mut v3: i32, mut v4: Rc<str>) -> Rc<str> {
    'spiral_tail: loop {
        let v5: i32 = projection_find_digit_loop7(v0.clone(), v1, v2);
        let v6: bool = v5 == v2;
        if v6 {
            let v7: bool = v3 == 10;
            if v7 {
                return v4;
            } else {
                return codec_empty3();
            }
        } else {
            let v10: bool = v3 >= 10;
            if v10 {
                return codec_empty3();
            } else {
                let v12: Rc<str> = Rc::<str>::from("u32");
                let v13: i32 = v0.len() as i32;
                let v14: i32 = 3;
                let v15: i32 = find_text_loop1(v0.clone(), v12.clone(), v5, v13, v14);
                let v16: bool = v15 == v2;
                if v16 {
                    return codec_empty3();
                } else {
                    let v18: bool = v5 == v15;
                    let mut v22: Rc<str>;
                    if v18 {
                        v22 = codec_empty3();
                    } else {
                        let v20: i32 = v15 - 1;
                        let v21: Rc<str> = SpiralStringSlice(&v0, v5, v20);
                        v22 = v21;
                    }
                    let v23: Rc<str> = codec_u64_decimal_normalize8(v22.clone());
                    let v24: Rc<str> = Rc::<str>::from("");
                    let v25: bool = v23 == v24;
                    if v25 {
                        return codec_empty3();
                    } else {
                        let v27: bool = v3 == 0;
                        let mut v54: Rc<str>;
                        if v27 {
                            let v28: Rc<str> = Rc::<str>::from("spiral_files=");
                            v54 = v28;
                        } else {
                            let v29: bool = v3 == 1;
                            if v29 {
                                let v30: Rc<str> = Rc::<str>::from(" generated_rust_files=");
                                v54 = v30;
                            } else {
                                let v31: bool = v3 == 2;
                                if v31 {
                                    let v32: Rc<str> = Rc::<str>::from(" rust_global_sites=");
                                    v54 = v32;
                                } else {
                                    let v33: bool = v3 == 3;
                                    if v33 {
                                        let v34: Rc<str> = Rc::<str>::from(" spiral_loc=");
                                        v54 = v34;
                                    } else {
                                        let v35: bool = v3 == 4;
                                        if v35 {
                                            let v36: Rc<str> = Rc::<str>::from(" generated_rust_loc=");
                                            v54 = v36;
                                        } else {
                                            let v37: bool = v3 == 5;
                                            if v37 {
                                                let v38: Rc<str> = Rc::<str>::from(" cargo_crates=");
                                                v54 = v38;
                                            } else {
                                                let v39: bool = v3 == 6;
                                                if v39 {
                                                    let v40: Rc<str> = Rc::<str>::from(" spiral_packages=");
                                                    v54 = v40;
                                                } else {
                                                    let v41: bool = v3 == 7;
                                                    if v41 {
                                                        let v42: Rc<str> = Rc::<str>::from(" package_only=");
                                                        v54 = v42;
                                                    } else {
                                                        let v43: bool = v3 == 8;
                                                        if v43 {
                                                            let v44: Rc<str> = Rc::<str>::from(" max_crate_loc=");
                                                            v54 = v44;
                                                        } else {
                                                            let v45: Rc<str> = Rc::<str>::from(" max_rust_file_loc=");
                                                            v54 = v45;
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                        let v55: Rc<str> = SpiralStringConcat(&v54, &v23);
                        let v56: i32 = v15 + 3;
                        let v57: i32 = v3 + 1;
                        let v58: Rc<str> = SpiralStringConcat(&v4, &v55);
                        let __spiral_tail_arg0: Rc<str> = v0.clone();
                        let __spiral_tail_arg1: i32 = v56;
                        let __spiral_tail_arg2: i32 = v2;
                        let __spiral_tail_arg3: i32 = v57;
                        let __spiral_tail_arg4: Rc<str> = v58.clone();
                        v0 = __spiral_tail_arg0;
                        v1 = __spiral_tail_arg1;
                        v2 = __spiral_tail_arg2;
                        v3 = __spiral_tail_arg3;
                        v4 = __spiral_tail_arg4;
                        continue 'spiral_tail;
                    }
                }
            }
        }
    }
}

fn handoff_census_projection10(v0: Rc<str>) -> Rc<str> {
    let v1: i32 = v0.len() as i32;
    let v2: Rc<str> = Rc::<str>::from("AuthorityCensus (");
    let v3: i32 = 0;
    let v4: i32 = 17;
    let v5: i32 = find_text_loop1(v0.clone(), v2.clone(), v3, v1, v4);
    let v6: bool = v5 == v1;
    let mut v16: Rc<str>;
    if v6 {
        v16 = codec_empty3();
    } else {
        let v8: Rc<str> = Rc::<str>::from("\n");
        let v9: u8 = codec_runtime_char5(v8.clone());
        let v10: i32 = find_char_loop6(v0.clone(), v5, v1, v9);
        let v11: bool = v5 == v10;
        if v11 {
            v16 = codec_empty3();
        } else {
            let v13: i32 = v10 - 1;
            let v14: Rc<str> = SpiralStringSlice(&v0, v5, v13);
            v16 = v14;
        }
    }
    let v17: i32 = v16.len() as i32;
    let v18: bool = v17 == 0;
    if v18 {
        codec_empty3()
    } else {
        let v20: i32 = 0;
        let v21: i32 = 0;
        let v22: Rc<str> = Rc::<str>::from("");
        projection_census_loop11(v16.clone(), v20, v17, v21, v22.clone())
    }
}

#[must_use]
pub fn eoie_handoff_ratings_projection(value: &str) -> Rc<str> {
    handoff_ratings_projection0(Rc::<str>::from(value))
}

#[must_use]
pub fn eoie_handoff_census_projection(value: &str) -> Rc<str> {
    handoff_census_projection10(Rc::<str>::from(value))
}
