// Generated by Spiral portable Rust backend.
#![allow(unused_mut, non_snake_case)]

use std::rc::Rc;

#[derive(Clone, Copy)]
struct Tuple0 {
    v0: i32,
    v1: i32,
    v2: bool,
}

fn TupleCreate0(v0: i32, v1: i32, v2: bool) -> Tuple0 {
    Tuple0 { v0, v1, v2 }
}

#[derive(Clone, Copy)]
struct Tuple1 {
    v1: f32,
    v2: i32,
    v0: bool,
}

fn TupleCreate1(v0: bool, v1: f32, v2: i32) -> Tuple1 {
    Tuple1 { v1, v2, v0 }
}

fn method1(v0: i32) -> Tuple0 {
    let v1: i32;
    v1 = v0 + 2;
    let v2: bool;
    v2 = v0 > 0;
    return TupleCreate0(v0, v1, v2);
}

fn method2(v0: i32, v1: i32, v2: bool) -> i32 {
    if v2 {
        let v3: i32;
        v3 = v0 + v1;
        let v4: i32;
        v4 = v3 - 4;
        return v4;
    } else {
        return 1;
    }
}

fn method4(v0: f32) -> Tuple1 {
    let v1: bool;
    v1 = v0 >= 3.5;
    return TupleCreate1(v1, v0, 7);
}

fn method5(v0: bool, v1: f32, v2: i32) -> i32 {
    if v0 {
        let v3: bool;
        v3 = v1 >= 3.5;
        if v3 {
            let v4: i32;
            v4 = v2 - 7;
            return v4;
        } else {
            return 1;
        }
    } else {
        return 2;
    }
}

fn method7(v0: Rc<str>) -> bool {
    let v1: bool;
    v1 = v0 == v0;
    return v1;
}

fn method9(v0: u32) -> bool {
    let v1: u32;
    v1 = v0 + 5;
    let v2: u32;
    v2 = v1 % 4;
    let v3: bool;
    v3 = v2 == 0;
    return v3;
}

fn method11(v0: i32, v1: i32) -> i32 {
    let v2: i32;
    v2 = v0 * v1;
    let v3: i32;
    v3 = v2 + 5;
    let v4: i32;
    v4 = v3 / 3;
    return v4;
}

fn method10(v0: i32) -> i32 {
    let v1: i32;
    v1 = 4;
    let v2: i32;
    v2 = 4;
    let v3: i32;
    v3 = method11(v1, v2);
    let v4: i32;
    v4 = v0 + v3;
    let v5: i32;
    v5 = v4 - 7;
    return v5;
}

fn method8(v0: i32) -> i32 {
    let v1: u32;
    v1 = 7;
    let v2: bool;
    v2 = method9(v1);
    if v2 {
        return method10(v0);
    } else {
        return 1;
    }
}

fn method6(v0: i32) -> i32 {
    let v1: Rc<str>;
    v1 = Rc::<str>::from("spiral");
    let v2: bool;
    v2 = method7(v1.clone());
    if v2 {
        return method8(v0);
    } else {
        return 1;
    }
}

fn method3(v0: i32) -> i32 {
    let v1: f32;
    v1 = 4.0;
    let v2: bool;
    let v3: f32;
    let v4: i32;
    let tmp1: Tuple1;
    tmp1 = method4(v1);
    v2 = tmp1.v0;
    v3 = tmp1.v1;
    v4 = tmp1.v2;
    let v5: i32;
    v5 = method5(v2, v3, v4);
    let v6: i32;
    v6 = v0 + v5;
    return method6(v6);
}

fn method0(v0: i32) -> i32 {
    let v1: i32;
    v1 = 1;
    let v2: i32;
    let v3: i32;
    let v4: bool;
    let tmp0: Tuple0;
    tmp0 = method1(v1);
    v2 = tmp0.v0;
    v3 = tmp0.v1;
    v4 = tmp0.v2;
    let v5: i32;
    v5 = method2(v2, v3, v4);
    let v6: i32;
    v6 = v0 + v5;
    return method3(v6);
}

fn spiral_main() -> i32 {
    let v0: i32;
    v0 = 0;
    return method0(v0);
}

fn main() {
    std::process::exit(spiral_main());
}
