// Generated by Spiral portable Rust backend.
#![allow(unused_mut, non_snake_case)]

#![allow(dead_code)]

use std::cell::RefCell;
use std::rc::Rc;

type Array0 = Rc<RefCell<Vec<i32>>>;
fn ArrayCreate0(len: i32, _init_at_zero: bool) -> Array0 {
    assert!(len >= 0, "negative Spiral array length");
    Rc::new(RefCell::new(vec![0; len as usize]))
}
fn DynamicArraySet0(array: &Array0, index: i32, value: i32) {
    assert!(index >= 0, "negative Spiral array index");
    let mut data = array.borrow_mut();
    let index = index as usize;
    assert!(index < data.len(), "Spiral array index out of bounds");
    data[index] = value;
}
fn DynamicArrayGet0(array: &Array0, index: i32) -> i32 {
    assert!(index >= 0, "negative Spiral array index");
    let data = array.borrow();
    let index = index as usize;
    assert!(index < data.len(), "Spiral array index out of bounds");
    data[index]
}
fn DynamicArrayLen0(array: &Array0) -> i32 {
    let len = array.borrow().len();
    assert!(len <= i32::MAX as usize, "Spiral array length exceeds i32");
    len as i32
}
fn DynamicArrayClone0(_array: &Array0) {}
fn DynamicArrayDrop0(_array: &Array0) {}

#[derive(Clone)]
struct ClosureValue0 {
    v0: Array0,
}

fn ClosureValueCreate0(v0: Array0) -> ClosureValue0 {
    ClosureValue0 { v0 }
}

fn ClosureInvoke0(x: ClosureValue0, v1: i32) -> i32 {
    let v0: Array0;
    v0 = x.v0.clone();
    let v2: i32;
    v2 = DynamicArrayLen0(&v0);
    let v3: i32;
    v3 = v2 + v1;
    return v3;
}

fn spiral_main() -> i32 {
    let v0: Array0;
    v0 = ArrayCreate0(2, false);
    DynamicArrayClone0(&v0);
    let v1: ClosureValue0;
    v1 = ClosureValueCreate0(v0.clone());
    drop(v0);
    return ClosureInvoke0(v1.clone(), 40);
}

fn main() {
    std::process::exit(spiral_main());
}
