// Generated by the Spiral compiler (TypeScript backend). Run: node --experimental-strip-types main.ts, or bun main.ts.
function closure0(v0: Array<number>): ((a0: number) => number) {
    return (v1: number): number => {
        let v2: number = v0.length;
        let v3: number = (v2 + v1) | 0;
        return v3;
    };
}
export function main(): number {
    let v0: Array<number> = new Array<number>(2).fill(0);
    let v1: ((a0: number) => number) = closure0(v0);
    return v1(40);
}
process.exitCode = main();
