[package]
name = "cold-proof-domain"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
name = "cold_proof_domain"
path = "cold_proof.rs"

[dependencies]
eoie-proxy-search = { path = "../eoie_proxy_search" }
eoie-rust-std-fs = { path = "../rust_std_fs" }
eoie-source-topology = { path = "../eoie_source_topology" }

[lints.rust]
dead_code = "allow"

[lints.clippy]
needless_return = "allow"
