// Generated by Spiral portable Rust backend.
#![allow(unused_mut, non_snake_case)]

#![allow(dead_code)]

use std::cell::RefCell;
use std::rc::Rc;

type Array0 = Rc<RefCell<Vec<i32>>>;
fn ArrayCreate0(len: i32, _init_at_zero: bool) -> Array0 {
    assert!(len >= 0, "negative Spiral array length");
    Rc::new(RefCell::new(vec![0; len as usize]))
}
fn DynamicArraySet0(array: &Array0, index: i32, value: i32) {
    assert!(index >= 0, "negative Spiral array index");
    let mut data = array.borrow_mut();
    let index = index as usize;
    assert!(index < data.len(), "Spiral array index out of bounds");
    data[index] = value;
}
fn DynamicArrayGet0(array: &Array0, index: i32) -> i32 {
    assert!(index >= 0, "negative Spiral array index");
    let data = array.borrow();
    let index = index as usize;
    assert!(index < data.len(), "Spiral array index out of bounds");
    data[index]
}
fn DynamicArrayLen0(array: &Array0) -> i32 {
    let len = array.borrow().len();
    assert!(len <= i32::MAX as usize, "Spiral array length exceeds i32");
    len as i32
}
fn DynamicArrayResize0(array: &Array0, len: i32) {
    assert!(len >= 0, "negative Spiral array length");
    array.borrow_mut().resize(len as usize, 0);
}
fn DynamicArrayReserve0(array: &Array0, capacity: i32) {
    assert!(capacity >= 0, "negative Spiral array capacity");
    let mut data = array.borrow_mut();
    let requested = capacity as usize;
    let current = data.capacity();
    if requested > current {
        let mut target = current.max(1);
        while target < requested {
            match target.checked_mul(2) {
                Some(next) => target = next,
                None => { target = requested; break; }
            }
        }
        let additional = target.saturating_sub(data.len());
        data.reserve_exact(additional);
    }
}
fn DynamicArrayCapacity0(array: &Array0) -> i32 {
    let capacity = array.borrow().capacity();
    assert!(capacity <= i32::MAX as usize, "Spiral array capacity exceeds i32");
    capacity as i32
}
fn DynamicArrayRefCount0(array: &Array0) -> i32 {
    let count = Rc::strong_count(array);
    assert!(count <= i32::MAX as usize, "Spiral array reference count exceeds i32");
    count as i32
}
fn DynamicArrayClone0(_array: &Array0) {}
fn DynamicArrayDrop0(_array: &Array0) {}

#[derive(Clone)]
struct Tuple9000 {
    v0: i32,
    v1: Array0,
}

fn TupleCreate9000(v0: i32, v1: Array0) -> Tuple9000 {
    Tuple9000 { v0, v1 }
}

fn method1(v0: Array0) -> () {
    let v1: i32;
    v1 = 8;
    DynamicArrayReserve0(&v0, v1);
    drop(v0);
    return;
}

fn method2(v0: Array0) -> () {
    let v1: i32;
    v1 = 5;
    DynamicArrayResize0(&v0, v1);
    drop(v0);
    return;
}

fn method3(v0: Array0) -> () {
    let v1: i32;
    v1 = 2;
    DynamicArrayResize0(&v0, v1);
    drop(v0);
    return;
}

fn method4(v0: Array0) -> i32 {
    let v1: i32;
    v1 = DynamicArrayCapacity0(&v0);
    drop(v0);
    return v1;
}

fn mutate0(v0: Tuple9000) -> i32 {
    if v0.v0 == 0 {
        drop(v0);
        return 90;
    } else {
        let v1: Array0;
        v1 = v0.v1.clone();
        DynamicArrayClone0(&v1);
        DynamicArrayClone0(&v1);
        drop(v0);
        method1(v1.clone());
        DynamicArrayClone0(&v1);
        method2(v1.clone());
        DynamicArraySet0(&v1, 1, 11);
        DynamicArrayClone0(&v1);
        method3(v1.clone());
        return method4(v1);
    }
}

fn observe5(v0: Tuple9000) -> i32 {
    if v0.v0 == 0 {
        drop(v0);
        return 91;
    } else {
        let v1: Array0;
        v1 = v0.v1.clone();
        DynamicArrayClone0(&v1);
        drop(v0);
        let v2: i32;
        v2 = DynamicArrayLen0(&v1);
        let v3: i32;
        v3 = DynamicArrayGet0(&v1, 0);
        let v4: i32;
        v4 = v2 + v3;
        let v5: i32;
        v5 = DynamicArrayGet0(&v1, 1);
        drop(v1);
        let v6: i32;
        v6 = v4 + v5;
        return v6;
    }
}

fn method6(v0: Array0) -> () {
    let v1: i32;
    v1 = 0;
    DynamicArrayResize0(&v0, v1);
    drop(v0);
    return;
}

fn method7(v0: Array0) -> () {
    let v1: i32;
    v1 = 2;
    DynamicArrayResize0(&v0, v1);
    drop(v0);
    return;
}

fn spiral_main() -> i32 {
    let v0: Array0;
    v0 = ArrayCreate0(2, false);
    DynamicArraySet0(&v0, 0, 7);
    DynamicArraySet0(&v0, 1, 3);
    DynamicArrayClone0(&v0);
    let v1: Tuple9000;
    v1 = TupleCreate9000(1, v0.clone());
    if v1.v0 == 1 {
        DynamicArrayClone0(&v1.v1);
    }
    let v2: i32;
    v2 = mutate0(v1.clone());
    DynamicArrayClone0(&v0);
    drop(v1);
    let v3: Tuple9000;
    v3 = TupleCreate9000(1, v0.clone());
    if v3.v0 == 1 {
        DynamicArrayClone0(&v3.v1);
    }
    let v4: i32;
    v4 = observe5(v3.clone());
    DynamicArrayClone0(&v0);
    drop(v3);
    method6(v0.clone());
    DynamicArrayClone0(&v0);
    method7(v0.clone());
    let v5: i32;
    v5 = DynamicArrayRefCount0(&v0);
    let v6: i32;
    v6 = v4 + v2;
    let v7: i32;
    v7 = DynamicArrayLen0(&v0);
    let v8: i32;
    v8 = v6 + v7;
    let v9: i32;
    v9 = DynamicArrayGet0(&v0, 0);
    let v10: i32;
    v10 = v8 + v9;
    let v11: i32;
    v11 = DynamicArrayGet0(&v0, 1);
    drop(v0);
    let v12: i32;
    v12 = v10 + v11;
    let v13: i32;
    v13 = v12 + v5;
    let v14: i32;
    v14 = v13 - 31;
    return v14;
}

fn main() {
    std::process::exit(spiral_main());
}
