// Generated by Spiral typed stack_refs residual bridge.
use std::cell::{Cell, RefCell};

#[derive(Clone, Copy)]
struct SpiralStackRefs<'a> {
    items: &'a RefCell<Vec<i32>>,
    q: &'a Cell<i32>,
    w: &'a Cell<i32>,
}

fn spiral_main() -> i32 {
    let a_items_storage = RefCell::new(vec![1i32, 2i32]);
    let a_q_storage = Cell::new(5i32);
    let a_w_storage = Cell::new(6i32);
    let a = SpiralStackRefs {
        items: &a_items_storage,
        q: &a_q_storage,
        w: &a_w_storage,
    };
    let b = SpiralStackRefs {
        items: a.items,
        q: a.q,
        w: a.w,
    };
    if a.q.get() == 5i32 {
        {
            let next_value = vec![7i32, 8i32];
            let old_value = a.items.replace(next_value);
            drop(old_value);
        }
        b.items.borrow_mut().resize(3usize, 9i32);
    } else {
        {
            let next_value = vec![10i32];
            let old_value = a.items.replace(next_value);
            drop(old_value);
        }
        b.items.borrow_mut().resize(2usize, 11i32);
    }
    a.items.borrow_mut()[1] = 12i32;
    a.q.set(b.items.borrow().len() as i32);
    a.w.set(b.items.borrow()[2]);
    (a.q.get() + a.w.get()) as i32
}

fn main() {
    std::process::exit(spiral_main());
}
