// Generated by Spiral portable Rust backend.
#![allow(unused_mut, non_snake_case)]

#![allow(dead_code)]

use std::cell::RefCell;
use std::rc::Rc;

type Array0 = Rc<RefCell<Vec<i32>>>;
fn ArrayCreate0(len: i32, _init_at_zero: bool) -> Array0 {
    assert!(len >= 0, "negative Spiral array length");
    Rc::new(RefCell::new(vec![0; len as usize]))
}
fn DynamicArraySet0(array: &Array0, index: i32, value: i32) {
    assert!(index >= 0, "negative Spiral array index");
    let mut data = array.borrow_mut();
    let index = index as usize;
    assert!(index < data.len(), "Spiral array index out of bounds");
    data[index] = value;
}
fn DynamicArrayGet0(array: &Array0, index: i32) -> i32 {
    assert!(index >= 0, "negative Spiral array index");
    let data = array.borrow();
    let index = index as usize;
    assert!(index < data.len(), "Spiral array index out of bounds");
    data[index]
}
fn DynamicArrayLen0(array: &Array0) -> i32 {
    let len = array.borrow().len();
    assert!(len <= i32::MAX as usize, "Spiral array length exceeds i32");
    len as i32
}
fn DynamicArrayClone0(_array: &Array0) {}
fn DynamicArrayDrop0(_array: &Array0) {}

fn method1(mut v0: i32, mut v1: Array0, mut v2: Array0) -> Array0 {
    'spiral_tail: loop {
        let v3: i32;
        v3 = v0 - 1;
        let v4: bool;
        v4 = v3 == 0;
        if v4 {
            DynamicArrayDrop0(&v1);
            return v2;
        } else {
            let __spiral_tail_arg0: i32 = v3;
            let __spiral_tail_arg1: Array0 = v2.clone();
            let __spiral_tail_arg2: Array0 = v1.clone();
            v0 = __spiral_tail_arg0;
            v1 = __spiral_tail_arg1;
            v2 = __spiral_tail_arg2;
            continue 'spiral_tail;
        }
    }
}

fn method0(v0: Array0, v1: Array0) -> Array0 {
    let v2: i32;
    v2 = 1000000;
    let v3: bool;
    v3 = v2 == 0;
    if v3 {
        DynamicArrayDrop0(&v1);
        return v0;
    } else {
        return method1(v2, v0, v1);
    }
}

fn spiral_main() -> i32 {
    let v0: i32;
    v0 = 1;
    let v1: Array0;
    v1 = ArrayCreate0(v0, false);
    let v2: Array0;
    v2 = ArrayCreate0(v0, false);
    DynamicArraySet0(&v1, 0, 7);
    DynamicArraySet0(&v2, 0, 11);
    DynamicArrayClone0(&v1);
    DynamicArrayClone0(&v2);
    let v3: Array0;
    v3 = method0(v1.clone(), v2.clone());
    DynamicArraySet0(&v3, 0, 13);
    drop(v3);
    let v4: i32;
    v4 = DynamicArrayGet0(&v1, 0);
    drop(v1);
    let v5: bool;
    v5 = v4 == 13;
    if v5 {
        let v6: i32;
        v6 = DynamicArrayGet0(&v2, 0);
        DynamicArrayDrop0(&v2);
        let v7: bool;
        v7 = v6 == 11;
        if v7 {
            return 0;
        } else {
            return 2;
        }
    } else {
        drop(v2);
        return 1;
    }
}

fn main() {
    std::process::exit(spiral_main());
}
