[package]
name = "evidence-currentness-domain"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
name = "evidence_currentness_domain"
path = "evidence_currentness.rs"

[dependencies]
eoie-patch-control-domain = { path = "../patch_control_domain" }
eoie-proxy-search = { path = "../eoie_proxy_search" }
eoie-rust-std-fs = { path = "../rust_std_fs" }
