// Generated by Spiral portable Rust backend.
#![allow(unused_mut, non_snake_case)]

#![allow(dead_code)]

use std::rc::Rc;

type Recursive0 = Rc<Recursive0Node>;
#[derive(Clone)]
enum Recursive0Node {
    Case0,
    Case1 { v0: Rc<str>, v1: Recursive0, v2: Recursive0 },
}

fn RecursiveCreate0_0() -> Recursive0 {
    Rc::new(Recursive0Node::Case0)
}
fn RecursiveCreate0_1(v0: Rc<str>, v1: Recursive0, v2: Recursive0) -> Recursive0 {
    Rc::new(Recursive0Node::Case1 { v0, v1, v2 })
}
fn RecursiveTag0(value: &Recursive0) -> i32 {
    match value.as_ref() {
        Recursive0Node::Case0 => 0,
        Recursive0Node::Case1 { .. } => 1,
    }
}
fn RecursiveField0_0(value: &Recursive0) -> Rc<str> {
    match value.as_ref() {
        Recursive0Node::Case1 { v0, .. } => v0.clone(),
        _ => panic!("recursive union field 0 requested from wrong case"),
    }
}
fn RecursiveField0_1(value: &Recursive0) -> Recursive0 {
    match value.as_ref() {
        Recursive0Node::Case1 { v1, .. } => v1.clone(),
        _ => panic!("recursive union field 1 requested from wrong case"),
    }
}
fn RecursiveField0_2(value: &Recursive0) -> Recursive0 {
    match value.as_ref() {
        Recursive0Node::Case1 { v2, .. } => v2.clone(),
        _ => panic!("recursive union field 2 requested from wrong case"),
    }
}
fn RecursiveClone0(_value: &Recursive0) {}
fn RecursiveDrop0(_value: &Recursive0) {}

fn score0(v0: Recursive0) -> i32 {
    if RecursiveTag0(&v0) == 0 {
        RecursiveDrop0(&v0);
        return 0;
    } else {
        let v1: Rc<str>;
        v1 = RecursiveField0_0(&v0);
        let v2: Recursive0;
        v2 = RecursiveField0_1(&v0);
        let v3: Recursive0;
        v3 = RecursiveField0_2(&v0);
        RecursiveClone0(&v2);
        RecursiveClone0(&v3);
        drop(v0);
        let v4: i32;
        v4 = v1.len() as i32;
        RecursiveClone0(&v2);
        let v5: i32;
        v5 = score0(v2.clone());
        drop(v2);
        let v6: i32;
        v6 = v4 + v5;
        RecursiveClone0(&v3);
        let v7: i32;
        v7 = score0(v3.clone());
        drop(v3);
        let v8: i32;
        v8 = v6 + v7;
        return v8;
    }
}

fn spiral_main() -> i32 {
    let v0: Rc<str>;
    v0 = Rc::<str>::from("ab");
    let v1: Rc<str>;
    v1 = Rc::<str>::from("qwe");
    let v2: Recursive0;
    v2 = RecursiveCreate0_0();
    RecursiveClone0(&v2);
    RecursiveClone0(&v2);
    let v3: Recursive0;
    v3 = RecursiveCreate0_1(v1.clone(), v2.clone(), v2.clone());
    RecursiveClone0(&v3);
    RecursiveClone0(&v3);
    drop(v2);
    let v4: Recursive0;
    v4 = RecursiveCreate0_1(v0.clone(), v3.clone(), v3.clone());
    RecursiveClone0(&v4);
    drop(v3);
    let v5: i32;
    v5 = score0(v4.clone());
    drop(v4);
    let v6: Recursive0;
    v6 = RecursiveCreate0_0();
    RecursiveClone0(&v6);
    RecursiveClone0(&v6);
    let v7: Recursive0;
    v7 = RecursiveCreate0_1(v1.clone(), v6.clone(), v6.clone());
    RecursiveClone0(&v7);
    RecursiveClone0(&v7);
    drop(v6);
    let v8: Recursive0;
    v8 = RecursiveCreate0_1(v0.clone(), v7.clone(), v7.clone());
    RecursiveClone0(&v8);
    drop(v7);
    let v9: i32;
    v9 = score0(v8.clone());
    drop(v8);
    let v10: i32;
    v10 = v5 + v9;
    let v11: i32;
    v11 = v10 - 16;
    return v11;
}

fn main() {
    std::process::exit(spiral_main());
}
