// Generated by Spiral portable Rust backend.
#![allow(unused_mut, non_snake_case)]

#![allow(dead_code)]

use std::rc::Rc;

type Heap0 = Rc<Heap0Data>;
#[derive(Clone)]
struct Heap0Data {
    v0: i32,
    v1: i32,
}
fn HeapCreate0(v0: i32, v1: i32) -> Heap0 {
    Rc::new(Heap0Data { v0, v1 })
}
fn HeapGet0_0(value: &Heap0) -> i32 {
    value.v0
}
fn HeapGet0_1(value: &Heap0) -> i32 {
    value.v1
}
fn HeapDecref0(_value: &Heap0) {}

fn spiral_main() -> i32 {
    let v0: Heap0;
    v0 = HeapCreate0(9, 10);
    let v1: i32;
    v1 = HeapGet0_0(&v0);
    let v2: i32;
    v2 = HeapGet0_1(&v0);
    HeapDecref0(&v0);
    let v3: i32;
    v3 = v1 + v2;
    return v3;
}

fn main() {
    std::process::exit(spiral_main());
}
