// Generated by Spiral portable Rust backend.
#![allow(unused_mut, non_snake_case)]

use std::rc::Rc;

fn spiral_main() -> i32 {
    let v0: Rc<str>;
    v0 = Rc::<str>::from("qwe");
    let v1: i32;
    v1 = v0.len() as i32;
    let v2: i32;
    v2 = v1 + v1;
    let v3: i32;
    v3 = v2 - 6;
    return v3;
}

fn main() {
    std::process::exit(spiral_main());
}
