// Generated by Spiral typed stack_refs residual bridge.
use std::cell::Cell;

#[derive(Clone, Copy)]
struct SpiralStackRefs<'a> {
    q: &'a Cell<i32>,
    w: &'a Cell<i32>,
}

fn spiral_main() -> i32 {
    let a_q_storage = Cell::new(5i32);
    let a_w_storage = Cell::new(6i32);
    let a = SpiralStackRefs {
        q: &a_q_storage,
        w: &a_w_storage,
    };
    if a.q.get() > 10i32 {
        a.q.set(9i32);
    } else {
        a.q.set(7i32);
    }
    let b = SpiralStackRefs {
        q: a.q,
        w: a.w,
    };
    a.w.set(8i32);
    (b.q.get() + a.w.get()) as i32
}

fn main() {
    std::process::exit(spiral_main());
}
