// Generated by Spiral portable Rust backend.
#![allow(unused_mut, non_snake_case)]

use std::rc::Rc;

fn SpiralStringSlice(value: &Rc<str>, from_index: i32, to_index: i32) -> Rc<str> {
    assert!(from_index >= 0, "negative Spiral string slice start");
    let bytes = value.as_bytes();
    let length = bytes.len() as i32;
    assert!(from_index <= length, "Spiral string slice start out of bounds");
    assert!(to_index >= from_index - 1, "invalid Spiral string slice range");
    assert!(to_index < length, "Spiral string slice end out of bounds");
    if to_index < from_index { return Rc::<str>::from(""); }
    let from_index = from_index as usize;
    let to_index = to_index as usize;
    let slice = &bytes[from_index..=to_index];
    Rc::<str>::from(std::str::from_utf8(slice).expect("Spiral string slice must preserve UTF-8 boundaries"))
}

fn invalid_middle0(v0: Rc<str>) -> Rc<str> {
    let v1: Rc<str>;
    v1 = SpiralStringSlice(&v0, 1, 1);
    return v1;
}

fn spiral_main() -> i32 {
    let v0: Rc<str>;
    v0 = Rc::<str>::from("é");
    let v1: Rc<str>;
    v1 = invalid_middle0(v0.clone());
    let v2: i32;
    v2 = v1.len() as i32;
    return v2;
}

fn main() {
    std::process::exit(spiral_main());
}
