#![allow(unused_mut, non_snake_case, dead_code, clippy::needless_return, clippy::too_many_arguments)]
// Generated by Spiral portable Rust backend.

fn toolchain_argument_token_high_binding0(v0: i32, v1: i32) -> i32 {
    let v2: bool = v0 < 4;
    if v2 {
        -1
    } else {
        let v3: bool = 7 < v0;
        if v3 {
            -1
        } else {
            let v4: bool = v1 < 0;
            if v4 {
                -1
            } else {
                let v5: bool = v0 == 4;
                if v5 {
                    let v6: bool = v1 == 0;
                    if v6 {
                        6
                    } else {
                        let v7: bool = v1 == 1;
                        if v7 {
                            1
                        } else {
                            let v8: bool = v1 == 2;
                            if v8 {
                                7
                            } else {
                                let v9: bool = v1 == 3;
                                if v9 {
                                    3
                                } else {
                                    let v10: bool = v1 == 4;
                                    if v10 {
                                        9
                                    } else {
                                        let v11: bool = v1 == 5;
                                        if v11 {
                                            10
                                        } else {
                                            -1
                                        }
                                    }
                                }
                            }
                        }
                    }
                } else {
                    let v18: bool = v0 == 5;
                    if v18 {
                        let v19: bool = v1 == 0;
                        if v19 {
                            11
                        } else {
                            let v20: bool = v1 == 1;
                            if v20 {
                                13
                            } else {
                                let v21: bool = v1 == 2;
                                if v21 {
                                    1
                                } else {
                                    let v22: bool = v1 == 3;
                                    if v22 {
                                        7
                                    } else {
                                        -1
                                    }
                                }
                            }
                        }
                    } else {
                        let v27: bool = v1 == 0;
                        if v27 {
                            12
                        } else {
                            -1
                        }
                    }
                }
            }
        }
    }
}

#[must_use]
pub fn eoie_toolchain_argument_token_high(first: i32, second: i32) -> i32 {
    toolchain_argument_token_high_binding0(first, second)
}
