// Generated by Spiral portable Rust backend.
#![allow(unused_mut, non_snake_case)]

unsafe extern "C" {
    #[link_name = "abs"]
    fn spiral_libc_abs(value: i32) -> i32;
}

#[inline]
fn spiral_abi_libc_abs(value: i32) -> i32 {
    unsafe { spiral_libc_abs(value) }
}

fn spiral_main() -> i32 {
    let v0: i32;
    v0 = -42;
    let v1: i32;
    v1 = spiral_abi_libc_abs(v0);
    return v1;
}

fn main() {
    std::process::exit(spiral_main());
}
