// Generated by the Spiral compiler (Zig backend). Build: zig build-exe main.zig -O ReleaseSafe (or -O Debug -fno-llvm: seconds)
const std = @import("std");
var spiral_threaded: std.Io.Threaded = .init_single_threaded;
var spiral_arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
var spiral_io: std.Io = undefined;
var spiral_gpa: std.mem.Allocator = undefined;
var spiral_true: bool = true;
fn spiralPrint(s: []const u8) void {
    std.Io.File.stdout().writeStreamingAll(spiral_io, s) catch {};
}
fn spiralPrintAny(x: anytype) void {
    const T = @TypeOf(x);
    if (T == []const u8) return spiralPrint(x);
    const s = switch (@typeInfo(T)) {
        .float => std.fmt.allocPrint(spiral_gpa, "{d}", .{x}),
        .bool => std.fmt.allocPrint(spiral_gpa, "{}", .{x}),
        else => std.fmt.allocPrint(spiral_gpa, "{d}", .{x}),
    } catch @panic("out of memory");
    spiralPrint(s);
}
fn spiralFail(s: []const u8) noreturn {
    std.Io.File.stderr().writeStreamingAll(spiral_io, s) catch {};
    std.Io.File.stderr().writeStreamingAll(spiral_io, "\n") catch {};
    std.process.exit(1);
}
fn spiralConv(comptime T: type, x: anytype) T {
    const S = @TypeOf(x);
    if (@typeInfo(T) == .float) {
        if (@typeInfo(S) == .float) return @floatCast(x) else return @floatFromInt(x);
    }
    if (@typeInfo(S) == .float) return @intFromFloat(x);
    const U = @Int(.unsigned, @bitSizeOf(T));
    const wide: i128 = x;
    return @bitCast(@as(U, @truncate(@as(u128, @bitCast(wide)))));
}
fn spiralConcat(a: []const u8, b: []const u8) []const u8 {
    return std.mem.concat(spiral_gpa, u8, &.{ a, b }) catch @panic("out of memory");
}
fn spiralStringSlice(s: []const u8, from: i64, upto: i64) []const u8 {
    const len: i64 = @intCast(s.len);
    if (from < 0 or from > len or upto < from - 1 or upto >= len) std.process.exit(3);
    if (upto < from) return "";
    const a: usize = @intCast(from);
    const b: usize = @intCast(upto + 1);
    if ((s[a] & 0xC0) == 0x80 or (b < s.len and (s[b] & 0xC0) == 0x80)) std.process.exit(3);
    return s[a..b];
}
fn spiralIndex(len: usize, i: anytype) usize {
    if (i < 0 or i >= len) std.process.exit(3);
    return @intCast(i);
}
fn spiralNewArray(comptime T: type, n: anytype) []T {
    const len: usize = @intCast(n);
    const a = spiral_gpa.alloc(T, len) catch @panic("out of memory");
    switch (@typeInfo(T)) {
        .int, .float, .bool => @memset(a, std.mem.zeroes(T)),
        else => if (T == []const u8) @memset(a, ""),
    }
    return a;
}
fn spiralCreate(comptime T: type, v: T) *T {
    const p = spiral_gpa.create(T) catch @panic("out of memory");
    p.* = v;
    return p;
}
const US0 = struct { tag: i32, c1_0: []const u8 = undefined, c1_1: []i32 = undefined };
const Fun0 = struct { ctx: *anyopaque, call: *const fn (*anyopaque, i32) US0 };
const ClosureEnv0 = struct { pad: u8 = 0 };
fn US0_0() US0 {
    return US0{ .tag = 0 };
}
fn US0_1(a0: []const u8, a1: []i32) US0 {
    return US0{ .tag = 1, .c1_0 = a0, .c1_1 = a1 };
}
fn closure0(ctx: *anyopaque, p0: i32) US0 {
    const env: *ClosureEnv0 = @ptrCast(@alignCast(ctx)); _ = &env;

    var v0: i32 = p0; _ = &v0;
    var v1: bool = undefined; _ = &v1;
    var v3: []i32 = undefined; _ = &v3;
    var v4: i32 = undefined; _ = &v4;
    var v5: []const u8 = undefined; _ = &v5;
    v1 = v0 == @as(i32, 0);
    if (v1) {
        return US0_0();
    } else {
        v3 = spiralNewArray(i32, @as(i32, 2));
        v3[spiralIndex(v3.len, @as(i32, 0))] = v0;
        v4 = v0 +% @as(i32, 1);
        v3[spiralIndex(v3.len, @as(i32, 1))] = v4;
        v5 = "hi";
        return US0_1(v5, v3);
    }
}
fn closureCreate0() Fun0 {
    return .{ .ctx = spiralCreate(ClosureEnv0, .{ }), .call = &closure0 };
}
fn method0(p0: Fun0) US0 {
    var v0: Fun0 = p0; _ = &v0;
    return v0.call(v0.ctx, @as(i32, 0));
}
fn method1(p0: Fun0) US0 {
    var v0: Fun0 = p0; _ = &v0;
    return v0.call(v0.ctx, @as(i32, 4));
}
fn spiralMain() i32 {
    var v0: Fun0 = undefined; _ = &v0;
    var v1: US0 = undefined; _ = &v1;
    var v12: i32 = undefined; _ = &v12;
    var v2: []const u8 = undefined; _ = &v2;
    var v3: []i32 = undefined; _ = &v3;
    var v4: i32 = undefined; _ = &v4;
    var v5: i32 = undefined; _ = &v5;
    var v6: i32 = undefined; _ = &v6;
    var v7: i32 = undefined; _ = &v7;
    var v8: i32 = undefined; _ = &v8;
    var v9: i32 = undefined; _ = &v9;
    var v10: i32 = undefined; _ = &v10;
    var v13: US0 = undefined; _ = &v13;
    var v24: i32 = undefined; _ = &v24;
    var v14: []const u8 = undefined; _ = &v14;
    var v15: []i32 = undefined; _ = &v15;
    var v16: i32 = undefined; _ = &v16;
    var v17: i32 = undefined; _ = &v17;
    var v18: i32 = undefined; _ = &v18;
    var v19: i32 = undefined; _ = &v19;
    var v20: i32 = undefined; _ = &v20;
    var v21: i32 = undefined; _ = &v21;
    var v22: i32 = undefined; _ = &v22;
    var v25: i32 = undefined; _ = &v25;
    var v26: i32 = undefined; _ = &v26;
    v0 = closureCreate0();
    v1 = method0(v0);
    switch (v1.tag) {
        0 => { // Empty
            v12 = @as(i32, 3);
        },
        1 => { // Item
            v2 = v1.c1_0;
            v3 = v1.c1_1;
            v4 = @as(i32, @intCast(v2.len));
            v5 = @as(i32, @intCast(v3.len));
            v6 = v4 +% v5;
            v7 = v3[spiralIndex(v3.len, @as(i32, 0))];
            v8 = v6 +% v7;
            v9 = v3[spiralIndex(v3.len, @as(i32, 1))];
            v10 = v8 +% v9;
            v12 = v10;
        },
        else => unreachable,
    }
    v13 = method1(v0);
    switch (v13.tag) {
        0 => { // Empty
            v24 = @as(i32, 3);
        },
        1 => { // Item
            v14 = v13.c1_0;
            v15 = v13.c1_1;
            v16 = @as(i32, @intCast(v14.len));
            v17 = @as(i32, @intCast(v15.len));
            v18 = v16 +% v17;
            v19 = v15[spiralIndex(v15.len, @as(i32, 0))];
            v20 = v18 +% v19;
            v21 = v15[spiralIndex(v15.len, @as(i32, 1))];
            v22 = v20 +% v21;
            v24 = v22;
        },
        else => unreachable,
    }
    v25 = v12 +% v24;
    v26 = v25 +% @as(i32, 26);
    return v26;
}
pub fn main() void {
    spiral_io = spiral_threaded.io();
    spiral_gpa = spiral_arena.allocator();
    var code: i32 = 0;
    const thread = std.Thread.spawn(.{ .stack_size = 1 << 30 }, spiralMainThread, .{&code}) catch @panic("cannot start the main thread");
    thread.join();
    std.process.exit(@truncate(@as(u32, @bitCast(code))));
}
fn spiralMainThread(code: *i32) void {
    code.* = spiralMain();
}
