[package]
name = "eoie-patch-control-domain"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
name = "eoie_patch_control_domain"
path = "control.rs"

[dependencies]
canonical-plan-ir-domain = { path = "../canonical_plan_ir_domain" }
eoie-rust-std-fs = { path = "../rust_std_fs" }
