// Generated by Spiral portable Rust backend.
#![allow(unused_mut, non_snake_case)]

#![allow(dead_code)]

use std::cell::RefCell;
use std::rc::Rc;

type Mut0 = Rc<RefCell<Mut0Data>>;
#[derive(Clone)]
struct Mut0Data {
    v0: i32,
    v1: i32,
}
fn MutCreate0(v0: i32, v1: i32) -> Mut0 {
    Rc::new(RefCell::new(Mut0Data { v0, v1 }))
}
fn MutAssign0(value: &Mut0, v0: i32, v1: i32) {
    let mut value = value.borrow_mut();
    value.v0 = v0;
    value.v1 = v1;
}
fn MutGet0_0(value: &Mut0) -> i32 {
    value.borrow().v0
}
fn MutGet0_1(value: &Mut0) -> i32 {
    value.borrow().v1
}
fn MutDecref0(_value: &Mut0) {}

fn spiral_main() -> i32 {
    let v0: Mut0;
    v0 = MutCreate0(1, 2);
    MutAssign0(&v0, 3, 4);
    let v1: i32;
    let v2: i32;
    v1 = MutGet0_0(&v0);
    v2 = MutGet0_1(&v0);
    MutDecref0(&v0);
    let v3: i32;
    v3 = v1 + v2;
    return v3;
}

fn main() {
    std::process::exit(spiral_main());
}
