// Generated by the Spiral compiler (Zig backend). Build: zig build-exe main.zig -O ReleaseSafe (or -O Debug -fno-llvm: seconds)
const std = @import("std");
var spiral_threaded: std.Io.Threaded = .init_single_threaded;
var spiral_arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
var spiral_io: std.Io = undefined;
var spiral_gpa: std.mem.Allocator = undefined;
var spiral_true: bool = true;
fn spiralPrint(s: []const u8) void {
    std.Io.File.stdout().writeStreamingAll(spiral_io, s) catch {};
}
fn spiralPrintAny(x: anytype) void {
    const T = @TypeOf(x);
    if (T == []const u8) return spiralPrint(x);
    const s = switch (@typeInfo(T)) {
        .float => std.fmt.allocPrint(spiral_gpa, "{d}", .{x}),
        .bool => std.fmt.allocPrint(spiral_gpa, "{}", .{x}),
        else => std.fmt.allocPrint(spiral_gpa, "{d}", .{x}),
    } catch @panic("out of memory");
    spiralPrint(s);
}
fn spiralFail(s: []const u8) noreturn {
    std.Io.File.stderr().writeStreamingAll(spiral_io, s) catch {};
    std.Io.File.stderr().writeStreamingAll(spiral_io, "\n") catch {};
    std.process.exit(1);
}
fn spiralConv(comptime T: type, x: anytype) T {
    const S = @TypeOf(x);
    if (@typeInfo(T) == .float) {
        if (@typeInfo(S) == .float) return @floatCast(x) else return @floatFromInt(x);
    }
    if (@typeInfo(S) == .float) return @intFromFloat(x);
    const U = @Int(.unsigned, @bitSizeOf(T));
    const wide: i128 = x;
    return @bitCast(@as(U, @truncate(@as(u128, @bitCast(wide)))));
}
fn spiralConcat(a: []const u8, b: []const u8) []const u8 {
    return std.mem.concat(spiral_gpa, u8, &.{ a, b }) catch @panic("out of memory");
}
fn spiralStringSlice(s: []const u8, from: i64, upto: i64) []const u8 {
    const len: i64 = @intCast(s.len);
    if (from < 0 or from > len or upto < from - 1 or upto >= len) std.process.exit(3);
    if (upto < from) return "";
    const a: usize = @intCast(from);
    const b: usize = @intCast(upto + 1);
    if ((s[a] & 0xC0) == 0x80 or (b < s.len and (s[b] & 0xC0) == 0x80)) std.process.exit(3);
    return s[a..b];
}
fn spiralIndex(len: usize, i: anytype) usize {
    if (i < 0 or i >= len) std.process.exit(3);
    return @intCast(i);
}
fn spiralNewArray(comptime T: type, n: anytype) []T {
    const len: usize = @intCast(n);
    const a = spiral_gpa.alloc(T, len) catch @panic("out of memory");
    switch (@typeInfo(T)) {
        .int, .float, .bool => @memset(a, std.mem.zeroes(T)),
        else => if (T == []const u8) @memset(a, ""),
    }
    return a;
}
fn spiralCreate(comptime T: type, v: T) *T {
    const p = spiral_gpa.create(T) catch @panic("out of memory");
    p.* = v;
    return p;
}
const Fun1 = struct { ctx: *anyopaque, call: *const fn (*anyopaque, i32) i32 };
const Fun0 = struct { ctx: *anyopaque, call: *const fn (*anyopaque, i32) Fun1 };
const ClosureEnv0 = struct { pad: u8 = 0 };
const US0 = struct { tag: i32, c1_0: []const u8 = undefined, c1_1: []i32 = undefined };
const ClosureEnv1 = struct { v0: US0, pad: u8 = 0 };
fn US0_0() US0 {
    return US0{ .tag = 0 };
}
fn US0_1(a0: []const u8, a1: []i32) US0 {
    return US0{ .tag = 1, .c1_0 = a0, .c1_1 = a1 };
}
fn closure1(ctx: *anyopaque, p1: i32) i32 {
    const env: *ClosureEnv1 = @ptrCast(@alignCast(ctx)); _ = &env;
    var v0: US0 = env.v0; _ = &v0;
    var v1: i32 = p1; _ = &v1;
    var v12: i32 = undefined; _ = &v12;
    var v2: []const u8 = undefined; _ = &v2;
    var v3: []i32 = undefined; _ = &v3;
    var v4: i32 = undefined; _ = &v4;
    var v5: i32 = undefined; _ = &v5;
    var v6: i32 = undefined; _ = &v6;
    var v7: i32 = undefined; _ = &v7;
    var v8: i32 = undefined; _ = &v8;
    var v9: i32 = undefined; _ = &v9;
    var v10: i32 = undefined; _ = &v10;
    var v13: i32 = undefined; _ = &v13;
    switch (v0.tag) {
        0 => { // Empty
            v12 = @as(i32, 3);
        },
        1 => { // Item
            v2 = v0.c1_0;
            v3 = v0.c1_1;
            v4 = @as(i32, @intCast(v2.len));
            v5 = @as(i32, @intCast(v3.len));
            v6 = v4 +% v5;
            v7 = v3[spiralIndex(v3.len, @as(i32, 0))];
            v8 = v6 +% v7;
            v9 = v3[spiralIndex(v3.len, @as(i32, 1))];
            v10 = v8 +% v9;
            v12 = v10;
        },
        else => unreachable,
    }
    v13 = v12 +% v1;
    return v13;
}
fn closureCreate1(p0: US0) Fun1 {
    return .{ .ctx = spiralCreate(ClosureEnv1, .{ .v0 = p0, }), .call = &closure1 };
}
fn closure0(ctx: *anyopaque, p0: i32) Fun1 {
    const env: *ClosureEnv0 = @ptrCast(@alignCast(ctx)); _ = &env;

    var v0: i32 = p0; _ = &v0;
    var v1: []i32 = undefined; _ = &v1;
    var v2: i32 = undefined; _ = &v2;
    var v3: bool = undefined; _ = &v3;
    var v7: US0 = undefined; _ = &v7;
    var v5: []const u8 = undefined; _ = &v5;
    v1 = spiralNewArray(i32, @as(i32, 2));
    v1[spiralIndex(v1.len, @as(i32, 0))] = v0;
    v2 = v0 +% @as(i32, 1);
    v1[spiralIndex(v1.len, @as(i32, 1))] = v2;
    v3 = v0 == @as(i32, 0);
    if (v3) {
        v7 = US0_0();
    } else {
        v5 = "hi";
        v7 = US0_1(v5, v1);
    }
    return closureCreate1(v7);
}
fn closureCreate0() Fun0 {
    return .{ .ctx = spiralCreate(ClosureEnv0, .{ }), .call = &closure0 };
}
fn method0(p0: Fun0) Fun1 {
    var v0: Fun0 = p0; _ = &v0;
    return v0.call(v0.ctx, @as(i32, 0));
}
fn method1(p0: Fun0) Fun1 {
    var v0: Fun0 = p0; _ = &v0;
    return v0.call(v0.ctx, @as(i32, 4));
}
fn method4(p0: Fun1) i32 {
    var v0: Fun1 = p0; _ = &v0;
    var v1: i32 = undefined; _ = &v1;
    var v2: i32 = undefined; _ = &v2;
    v1 = v0.call(v0.ctx, @as(i32, 2));
    v2 = v1 +% @as(i32, 5);
    return v2;
}
fn method3(p0: Fun1) i32 {
    var v0: Fun1 = p0; _ = &v0;
    var v1: i32 = undefined; _ = &v1;
    var v2: i32 = undefined; _ = &v2;
    var v3: i32 = undefined; _ = &v3;
    v1 = v0.call(v0.ctx, @as(i32, 1));
    v2 = method4(v0);
    v3 = v1 +% v2;
    return v3;
}
fn method2(p0: Fun1, p1: Fun1) i32 {
    var v0: Fun1 = p0; _ = &v0;
    var v1: Fun1 = p1; _ = &v1;
    var v2: i32 = undefined; _ = &v2;
    var v3: i32 = undefined; _ = &v3;
    var v4: i32 = undefined; _ = &v4;
    v2 = v0.call(v0.ctx, @as(i32, 5));
    v3 = method3(v1);
    v4 = v2 +% v3;
    return v4;
}
fn spiralMain() i32 {
    var v0: Fun0 = undefined; _ = &v0;
    var v1: Fun1 = undefined; _ = &v1;
    var v2: Fun1 = undefined; _ = &v2;
    v0 = closureCreate0();
    v1 = method0(v0);
    v2 = method1(v0);
    return method2(v1, v2);
}
pub fn main() void {
    spiral_io = spiral_threaded.io();
    spiral_gpa = spiral_arena.allocator();
    var code: i32 = 0;
    const thread = std.Thread.spawn(.{ .stack_size = 1 << 30 }, spiralMainThread, .{&code}) catch @panic("cannot start the main thread");
    thread.join();
    std.process.exit(@truncate(@as(u32, @bitCast(code))));
}
fn spiralMainThread(code: *i32) void {
    code.* = spiralMain();
}
