#![allow(unused_mut, non_snake_case, dead_code, clippy::needless_return, clippy::too_many_arguments, clippy::needless_late_init)]
// Generated by Spiral portable Rust backend.


fn bundle_root_binding0(v0: i32, v1: i32) -> i32 {
    let v2: bool = v0 < 1;
    if v2 {
        0
    } else {
        let v3: bool = v1 < 1;
        if v3 {
            0
        } else {
            let v4: bool = v0 < v1;
            if v4 {
                0
            } else {
                let v5: bool = v1 < v0;
                if v5 {
                    0
                } else {
                    1
                }
            }
        }
    }
}

fn coverage_checkpoint_binding1(v0: i32, v1: i32) -> i32 {
    let v2: bool = v0 < 0;
    if v2 {
        0
    } else {
        let v3: bool = 1 < v0;
        if v3 {
            0
        } else {
            let v4: bool = v1 < 0;
            if v4 {
                0
            } else {
                let v5: bool = 2 < v1;
                if v5 {
                    0
                } else {
                    let v6: bool = v0 < 1;
                    if v6 {
                        1
                    } else {
                        let v7: bool = v1 < 2;
                        if v7 {
                            0
                        } else {
                            1
                        }
                    }
                }
            }
        }
    }
}

fn bundle_entry_binding2(v0: i32, v1: i32) -> i32 {
    bundle_root_binding0(v0, v1)
}

fn bundle_size_binding3(v0: i32, v1: i32) -> i32 {
    let v2: bool = v0 < 1;
    if v2 {
        0
    } else {
        let v3: bool = v1 < 1;
        if v3 {
            0
        } else {
            let v4: bool = v0 < v1;
            if v4 {
                0
            } else {
                1
            }
        }
    }
}

fn bundle_extract_binding4(v0: i32, v1: i32) -> i32 {
    bundle_entry_binding2(v0, v1)
}

fn bundle_payload_count_binding5(v0: i32, v1: i32) -> i32 {
    let v2: bool = v0 < 1;
    if v2 {
        0
    } else {
        let v3: bool = v1 < 0;
        if v3 {
            0
        } else {
            let v4: bool = v0 < v1;
            if v4 {
                0
            } else {
                let v5: i32 = v0 - v1;
                v5
            }
        }
    }
}

fn bundle_rehydration_binding6(v0: i32, v1: i32) -> i32 {
    let v2: bool = v0 < 1;
    if v2 {
        0
    } else {
        let v3: bool = 1 < v0;
        if v3 {
            0
        } else {
            let v4: bool = v1 < 1;
            if v4 {
                0
            } else {
                let v5: bool = 1 < v1;
                if v5 {
                    0
                } else {
                    1
                }
            }
        }
    }
}

fn bundle_complete_binding7(v0: i32, v1: i32) -> i32 {
    bundle_rehydration_binding6(v0, v1)
}

fn bundle_rehydrate_preflight_binding8(v0: i32, v1: i32) -> i32 {
    bundle_rehydration_binding6(v0, v1)
}

fn bundle_rehydrate_extract_binding9(v0: i32, v1: i32) -> i32 {
    bundle_rehydration_binding6(v0, v1)
}

fn bundle_rehydrate_validate_binding10(v0: i32, v1: i32) -> i32 {
    bundle_rehydration_binding6(v0, v1)
}

fn bundle_rehydrate_receipt_binding11(v0: i32, v1: i32) -> i32 {
    bundle_complete_binding7(v0, v1)
}

fn archive_extract_preflight_binding12(v0: i32, v1: i32) -> i32 {
    let v2: bool = v0 < 0;
    if v2 {
        0
    } else {
        let v3: bool = 1 < v0;
        if v3 {
            0
        } else {
            let v4: bool = v1 < 1;
            if v4 {
                0
            } else {
                let v5: bool = 1 < v1;
                if v5 {
                    0
                } else {
                    let v6: bool = v0 < 1;
                    if v6 {
                        1
                    } else {
                        0
                    }
                }
            }
        }
    }
}

fn archive_extract_process_binding13(v0: i32, v1: i32) -> i32 {
    let v2: bool = v0 < 1;
    if v2 {
        0
    } else {
        let v3: bool = 1 < v0;
        if v3 {
            0
        } else {
            let v4: bool = v1 < 1;
            if v4 {
                0
            } else {
                let v5: bool = 1 < v1;
                if v5 {
                    0
                } else {
                    1
                }
            }
        }
    }
}

fn archive_extract_complete_binding14(v0: i32, v1: i32) -> i32 {
    bundle_extract_binding4(v0, v1)
}

fn archive_extract_receipt_binding15(v0: i32, v1: i32) -> i32 {
    bundle_complete_binding7(v0, v1)
}

fn preflight_binding17(v0: i32, v1: i32) -> i32 {
    let v2: bool = v0 < 1;
    if v2 {
        0
    } else {
        let v3: bool = 1 < v0;
        if v3 {
            0
        } else {
            let v4: bool = v1 < 1;
            if v4 {
                0
            } else {
                let v5: bool = 1 < v1;
                if v5 {
                    0
                } else {
                    1
                }
            }
        }
    }
}

fn bundle_output_preflight_binding16(v0: i32, v1: i32) -> i32 {
    preflight_binding17(v0, v1)
}

fn complete_binding19(v0: i32, v1: i32) -> i32 {
    preflight_binding17(v0, v1)
}

fn bundle_output_complete_binding18(v0: i32, v1: i32) -> i32 {
    complete_binding19(v0, v1)
}

fn preflight_binding21(v0: i32, v1: i32) -> i32 {
    preflight_binding17(v0, v1)
}

fn bundle_verify_preflight_binding20(v0: i32, v1: i32) -> i32 {
    preflight_binding21(v0, v1)
}

fn complete_binding23(v0: i32, v1: i32) -> i32 {
    complete_binding19(v0, v1)
}

fn bundle_verify_complete_binding22(v0: i32, v1: i32) -> i32 {
    complete_binding23(v0, v1)
}

#[must_use]
pub fn eoie_bundle_root_binding(first: i32, second: i32) -> i32 {
    bundle_root_binding0(first, second)
}

#[must_use]
pub fn eoie_bundle_coverage_checkpoint_binding(first: i32, second: i32) -> i32 {
    coverage_checkpoint_binding1(first, second)
}

#[must_use]
pub fn eoie_bundle_entry_binding(first: i32, second: i32) -> i32 {
    bundle_entry_binding2(first, second)
}

#[must_use]
pub fn eoie_bundle_size_binding(first: i32, second: i32) -> i32 {
    bundle_size_binding3(first, second)
}

#[must_use]
pub fn eoie_bundle_extract_binding(first: i32, second: i32) -> i32 {
    bundle_extract_binding4(first, second)
}

#[must_use]
pub fn eoie_bundle_payload_count_binding(first: i32, second: i32) -> i32 {
    bundle_payload_count_binding5(first, second)
}

#[must_use]
pub fn eoie_bundle_rehydration_binding(first: i32, second: i32) -> i32 {
    bundle_rehydration_binding6(first, second)
}

#[must_use]
pub fn eoie_bundle_complete_binding(first: i32, second: i32) -> i32 {
    bundle_complete_binding7(first, second)
}

#[must_use]
pub fn eoie_bundle_rehydrate_preflight_binding(first: i32, second: i32) -> i32 {
    bundle_rehydrate_preflight_binding8(first, second)
}

#[must_use]
pub fn eoie_bundle_rehydrate_extract_binding(first: i32, second: i32) -> i32 {
    bundle_rehydrate_extract_binding9(first, second)
}

#[must_use]
pub fn eoie_bundle_rehydrate_validate_binding(first: i32, second: i32) -> i32 {
    bundle_rehydrate_validate_binding10(first, second)
}

#[must_use]
pub fn eoie_bundle_rehydrate_receipt_binding(first: i32, second: i32) -> i32 {
    bundle_rehydrate_receipt_binding11(first, second)
}

#[must_use]
pub fn eoie_archive_extract_preflight_binding(first: i32, second: i32) -> i32 {
    archive_extract_preflight_binding12(first, second)
}

#[must_use]
pub fn eoie_archive_extract_process_binding(first: i32, second: i32) -> i32 {
    archive_extract_process_binding13(first, second)
}

#[must_use]
pub fn eoie_archive_extract_complete_binding(first: i32, second: i32) -> i32 {
    archive_extract_complete_binding14(first, second)
}

#[must_use]
pub fn eoie_archive_extract_receipt_binding(first: i32, second: i32) -> i32 {
    archive_extract_receipt_binding15(first, second)
}

#[must_use]
pub fn eoie_bundle_output_preflight_binding(first: i32, second: i32) -> i32 {
    bundle_output_preflight_binding16(first, second)
}

#[must_use]
pub fn eoie_bundle_output_complete_binding(first: i32, second: i32) -> i32 {
    bundle_output_complete_binding18(first, second)
}

#[must_use]
pub fn eoie_bundle_verify_preflight_binding(first: i32, second: i32) -> i32 {
    bundle_verify_preflight_binding20(first, second)
}

#[must_use]
pub fn eoie_bundle_verify_complete_binding(first: i32, second: i32) -> i32 {
    bundle_verify_complete_binding22(first, second)
}
