// Generated by Spiral portable Rust backend.
#![allow(unused_mut, non_snake_case)]

fn method_while0(v0: i32) -> bool {
    let v1: bool;
    v1 = v0 < 10;
    return v1;
}

fn spiral_main() -> i32 {
    let mut v0: i32;
    v0 = 0;
    let mut v1: i32;
    v1 = 0;
    while method_while0(v0) {
        let v3: i32;
        v3 = v1 + v0;
        v1 = v3;
        let v4: i32;
        v4 = v0 + 1;
        v0 = v4;
    }
    let v5: i32;
    v5 = v1 - 45;
    return v5;
}

fn main() {
    std::process::exit(spiral_main());
}
