// Generated by the Spiral compiler (TypeScript backend). Run: node --experimental-strip-types main.ts, or bun main.ts.
export function main(): number {
    let v0: number = 6;
    let v1: number = 7;
    let v2: number = Math.imul(v0, v1);
    let v3: boolean = v2 === 42;
    if (v3) {
        return 0;
    } else {
        return 1;
    }
}
process.exitCode = main();
