// Generated by Spiral portable Rust backend.
#![allow(unused_mut, non_snake_case, dead_code, unused_variables, unused_assignments)]

fn spiral_main() -> i32 {
    let v0: i32 = 6;
    let v1: i32 = 7;
    let v2: i32 = v0 * v1;
    let v3: bool = v2 == 42;
    if v3 {
        return 0;
    } else {
        return 1;
    }
}

fn main() {
    std::process::exit(spiral_main());
}


