[package]
name = "eoie-archive-contracts"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
name = "eoie_archive_contracts"
path = "archive_contracts.rs"

[dependencies]
zip = { version = "0.6.6", default-features = false, features = ["deflate"] }
