// Generated by Spiral portable Rust backend.
#![allow(unused_mut, non_snake_case)]

#[derive(Clone, Copy)]
struct Tuple0 {
    v0: i32,
    v1: i32,
}

fn TupleCreate0(v0: i32, v1: i32) -> Tuple0 {
    Tuple0 { v0, v1 }
}

#[derive(Clone, Copy)]
struct ClosureValue0 {
    v0: i32,
}

fn ClosureValueCreate0(v0: i32) -> ClosureValue0 {
    ClosureValue0 { v0 }
}

fn ClosureInvoke0(x: ClosureValue0, v1: i32, v2: i32) -> Tuple0 {
    let v0: i32;
    v0 = x.v0;
    let v3: i32;
    v3 = v1 - 8;
    let v4: i32;
    v4 = v3 + v0;
    let v5: i32;
    v5 = v2 - 18;
    return TupleCreate0(v4, v5);
}

fn method0(v0: ClosureValue0) -> Tuple0 {
    return ClosureInvoke0(v0, 10, 20);
}

fn spiral_main() -> i32 {
    let v0: i32;
    v0 = 1;
    let v1: ClosureValue0;
    v1 = ClosureValueCreate0(v0);
    let v2: i32;
    let v3: i32;
    let tmp0: Tuple0;
    tmp0 = method0(v1);
    v2 = tmp0.v0;
    v3 = tmp0.v1;
    let v4: i32;
    v4 = 10 + v2;
    let v5: i32;
    v5 = 20 + v3;
    let v6: i32;
    v6 = v4 + v5;
    let v7: i32;
    v7 = v6 + 7;
    return v7;
}

fn main() {
    std::process::exit(spiral_main());
}
