// Generated by the Spiral compiler (TypeScript backend). Run: node --experimental-strip-types main.ts, or bun main.ts.
type US0_0 = { readonly tag: 0, readonly f0: number }; // Hit
type US0_1 = { readonly tag: 1, readonly f0: boolean }; // Flag
type US0 = US0_0 | US0_1;
function US0_0(f0: number): US0 { return { tag: 0, f0: f0 }; }
function US0_1(f0: boolean): US0 { return { tag: 1, f0: f0 }; }
function method0(v0: US0): number {
    switch (v0.tag) {
        case 1: { // Flag
            let v2: boolean = v0.f0;
            if (v2) {
                return 9;
            } else {
                return 4;
            }
            break;
        }
        case 0: { // Hit
            let v1: number = v0.f0;
            return v1;
            break;
        }
        default: throw new Error("Compiler error: unreachable union case.");
    }
}
export function main(): number {
    let v0: boolean = false;
    let v3: US0;
    if (v0) {
        v3 = US0_0(7);
    } else {
        v3 = US0_1(true);
    }
    let v4: number = method0(v3);
    let v5: number = (v4 - 9) | 0;
    return v5;
}
process.exitCode = main();
