// Generated by Spiral portable Rust backend.
#![allow(unused_mut, non_snake_case)]

#[derive(Clone, Copy)]
struct Tuple9000 {
    v0: i32,
    v1: i32,
    v2: bool,
}

fn TupleCreate9000(v0: i32, v1: i32, v2: bool) -> Tuple9000 {
    Tuple9000 { v0, v1, v2 }
}

fn score0(v0: Tuple9000) -> i32 {
    if v0.v0 == 1 {
        let v2: bool;
        v2 = v0.v2;
        if v2 {
            return 9;
        } else {
            return 4;
        }
    } else {
        let v1: i32;
        v1 = v0.v1;
        return v1;
    }
}

fn spiral_main() -> i32 {
    let v0: bool;
    v0 = false;
    let mut v3: Tuple9000;
    if v0 {
        v3 = TupleCreate9000(0, 7, false);
    } else {
        v3 = TupleCreate9000(1, 0, true);
    }
    let v4: i32;
    v4 = score0(v3);
    let v5: i32;
    v5 = v4 - 9;
    return v5;
}

fn main() {
    std::process::exit(spiral_main());
}
