// Generated by Spiral portable Rust backend.
#![allow(unused_mut, non_snake_case, dead_code, unused_variables, unused_assignments)]

fn spiral_main() -> i32 {
    let v0: i32 = 42;
    let v1: i32 = v0 - 42;
    return v1;
}

fn main() {
    std::process::exit(spiral_main());
}


