// Generated by the Spiral compiler (TypeScript backend). Run: node --experimental-strip-types main.ts, or bun main.ts.
const spiral_utf8_encoder = new TextEncoder();
const spiral_utf8_decoder = new TextDecoder("utf-8");
let spiral_utf8_last = "";
let spiral_utf8_bytes: Uint8Array = new Uint8Array(0);
function spiral_utf8(value: string): Uint8Array {
    if (value !== spiral_utf8_last) {
        spiral_utf8_bytes = spiral_utf8_encoder.encode(value);
        spiral_utf8_last = value;
    }
    return spiral_utf8_bytes;
}
function spiral_string_length(value: string): number {
    return spiral_utf8(value).length;
}
function spiral_string_index(value: string, index: number): number {
    const bytes = spiral_utf8(value);
    if (!(index >= 0 && index < bytes.length)) throw new RangeError("string index " + index + " out of bounds for length " + bytes.length);
    return bytes[index];
}
// The C backend's StringSlice: inclusive bounds, an empty slice when to = from - 1, and a failure for bounds outside
// the string or inside a code point: exit code 3, like C's abort() and the Rust/Delphi helpers (in run_main.mjs's
// worker, process.exit ends the worker with that code).
function spiral_slice_abort(message: string): never {
    console.error(message);
    process.exit(3);
}
function spiral_string_slice(value: string, from: number, to: number): string {
    const bytes = spiral_utf8(value);
    const length = bytes.length;
    if (from < 0 || from > length || to < from - 1 || to >= length) spiral_slice_abort("string slice " + from + ".." + to + " out of bounds for length " + length);
    if (to < from) return "";
    if ((bytes[from] & 0xc0) === 0x80 || (to + 1 < length && (bytes[to + 1] & 0xc0) === 0x80)) spiral_slice_abort("string slice " + from + ".." + to + " splits a code point");
    return spiral_utf8_decoder.decode(bytes.subarray(from, to + 1));
}
export function main(): number {
    let v0: string = "a \"b\" c";
    let v1: string = "";
    let v2: string = "a\\nb";
    let v3: string = "first\n(* not a comment *)\n// nor this\n\n$\"not a macro\" !x\ninl fake () = 1\n  indented";
    let v4: string = "\ntop\n\nlevel";
    let v5: number = spiral_string_length(v0);
    let v6: boolean = v5 === 7;
    let v7: boolean = v6 !== true;
    if (v7) {
        return 1;
    } else {
        let v8: number = spiral_string_index(v0, 2);
        let v9: boolean = v8 === 34;
        let v10: boolean = v9 !== true;
        if (v10) {
            return 2;
        } else {
            let v11: number = spiral_string_length(v1);
            let v12: boolean = v11 === 0;
            let v13: boolean = v12 !== true;
            if (v13) {
                return 3;
            } else {
                let v14: number = spiral_string_length(v2);
                let v15: boolean = v14 === 4;
                let v16: boolean = v15 !== true;
                if (v16) {
                    return 4;
                } else {
                    let v17: number = spiral_string_index(v2, 1);
                    let v18: boolean = v17 === 92;
                    let v19: boolean = v18 !== true;
                    if (v19) {
                        return 5;
                    } else {
                        let v20: number = spiral_string_length(v3);
                        let v21: boolean = v20 === 83;
                        let v22: boolean = v21 !== true;
                        if (v22) {
                            return 6;
                        } else {
                            let v23: number = spiral_string_index(v3, 5);
                            let v24: boolean = v23 === 10;
                            let v25: boolean = v24 !== true;
                            if (v25) {
                                return 7;
                            } else {
                                let v26: number = spiral_string_index(v3, 37);
                                let v27: boolean = v26 === 10;
                                let v28: boolean = v27 !== true;
                                if (v28) {
                                    return 8;
                                } else {
                                    let v29: number = spiral_string_index(v3, 38);
                                    let v30: boolean = v29 === 10;
                                    let v31: boolean = v30 !== true;
                                    if (v31) {
                                        return 9;
                                    } else {
                                        let v32: number = spiral_string_index(v3, 39);
                                        let v33: boolean = v32 === 36;
                                        let v34: boolean = v33 !== true;
                                        if (v34) {
                                            return 10;
                                        } else {
                                            let v35: number = spiral_string_index(v3, 57);
                                            let v36: boolean = v35 === 105;
                                            let v37: boolean = v36 !== true;
                                            if (v37) {
                                                return 11;
                                            } else {
                                                let v38: number = spiral_string_index(v3, 82);
                                                let v39: boolean = v38 === 100;
                                                let v40: boolean = v39 !== true;
                                                if (v40) {
                                                    return 12;
                                                } else {
                                                    let v41: number = spiral_string_length(v4);
                                                    let v42: boolean = v41 === 11;
                                                    let v43: boolean = v42 !== true;
                                                    if (v43) {
                                                        return 13;
                                                    } else {
                                                        let v44: number = spiral_string_index(v4, 0);
                                                        let v45: boolean = v44 === 10;
                                                        let v46: boolean = v45 !== true;
                                                        if (v46) {
                                                            return 14;
                                                        } else {
                                                            let v47: number = spiral_string_index(v4, 5);
                                                            let v48: boolean = v47 === 10;
                                                            let v49: boolean = v48 !== true;
                                                            if (v49) {
                                                                return 15;
                                                            } else {
                                                                return 0;
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
process.exitCode = main();
