// Generated by the Spiral compiler (Zig backend). Build: zig build-exe main.zig -O ReleaseSafe (or -O Debug -fno-llvm: seconds)
const std = @import("std");
var spiral_threaded: std.Io.Threaded = .init_single_threaded;
var spiral_arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
var spiral_io: std.Io = undefined;
var spiral_gpa: std.mem.Allocator = undefined;
var spiral_true: bool = true;
fn spiralPrint(s: []const u8) void {
    std.Io.File.stdout().writeStreamingAll(spiral_io, s) catch {};
}
fn spiralPrintAny(x: anytype) void {
    const T = @TypeOf(x);
    if (T == []const u8) return spiralPrint(x);
    const s = switch (@typeInfo(T)) {
        .float => std.fmt.allocPrint(spiral_gpa, "{d}", .{x}),
        .bool => std.fmt.allocPrint(spiral_gpa, "{}", .{x}),
        else => std.fmt.allocPrint(spiral_gpa, "{d}", .{x}),
    } catch @panic("out of memory");
    spiralPrint(s);
}
fn spiralFail(s: []const u8) noreturn {
    std.Io.File.stderr().writeStreamingAll(spiral_io, s) catch {};
    std.Io.File.stderr().writeStreamingAll(spiral_io, "\n") catch {};
    std.process.exit(1);
}
fn spiralConv(comptime T: type, x: anytype) T {
    const S = @TypeOf(x);
    if (@typeInfo(T) == .float) {
        if (@typeInfo(S) == .float) return @floatCast(x) else return @floatFromInt(x);
    }
    if (@typeInfo(S) == .float) return @intFromFloat(x);
    const U = @Int(.unsigned, @bitSizeOf(T));
    const wide: i128 = x;
    return @bitCast(@as(U, @truncate(@as(u128, @bitCast(wide)))));
}
fn spiralConcat(a: []const u8, b: []const u8) []const u8 {
    return std.mem.concat(spiral_gpa, u8, &.{ a, b }) catch @panic("out of memory");
}
fn spiralStringSlice(s: []const u8, from: i64, upto: i64) []const u8 {
    const len: i64 = @intCast(s.len);
    if (from < 0 or from > len or upto < from - 1 or upto >= len) std.process.exit(3);
    if (upto < from) return "";
    const a: usize = @intCast(from);
    const b: usize = @intCast(upto + 1);
    if ((s[a] & 0xC0) == 0x80 or (b < s.len and (s[b] & 0xC0) == 0x80)) std.process.exit(3);
    return s[a..b];
}
fn spiralIndex(len: usize, i: anytype) usize {
    if (i < 0 or i >= len) std.process.exit(3);
    return @intCast(i);
}
fn spiralNewArray(comptime T: type, n: anytype) []T {
    const len: usize = @intCast(n);
    const a = spiral_gpa.alloc(T, len) catch @panic("out of memory");
    switch (@typeInfo(T)) {
        .int, .float, .bool => @memset(a, std.mem.zeroes(T)),
        else => if (T == []const u8) @memset(a, ""),
    }
    return a;
}
fn spiralCreate(comptime T: type, v: T) *T {
    const p = spiral_gpa.create(T) catch @panic("out of memory");
    p.* = v;
    return p;
}
const UH0 = struct { tag: i32, c1_0: i32 = undefined, c1_1: *UH0 = undefined, c1_2: *UH0 = undefined };
fn UH0_0() *UH0 {
    return spiralCreate(UH0, UH0{ .tag = 0 });
}
fn UH0_1(a0: i32, a1: *UH0, a2: *UH0) *UH0 {
    return spiralCreate(UH0, UH0{ .tag = 1, .c1_0 = a0, .c1_1 = a1, .c1_2 = a2 });
}
fn method1(p0: *UH0) i32 {
    var v0: *UH0 = p0; _ = &v0;
    var v1: i32 = undefined; _ = &v1;
    var v2: *UH0 = undefined; _ = &v2;
    var v3: *UH0 = undefined; _ = &v3;
    var v4: i32 = undefined; _ = &v4;
    var v5: i32 = undefined; _ = &v5;
    var v6: i32 = undefined; _ = &v6;
    var v7: i32 = undefined; _ = &v7;
    switch (v0.tag) {
        0 => { // Leaf
            return @as(i32, 0);
        },
        1 => { // Node
            v1 = v0.c1_0;
            v2 = v0.c1_1;
            v3 = v0.c1_2;
            v4 = method1(v2);
            v5 = method1(v3);
            v6 = v4 +% v5;
            v7 = v1 +% v6;
            return v7;
        },
        else => unreachable,
    }
}
fn method0(p0: *UH0, p1: *UH0) i32 {
    var v0: *UH0 = p0; _ = &v0;
    var v1: *UH0 = p1; _ = &v1;
    var v2: i32 = undefined; _ = &v2;
    var v3: i32 = undefined; _ = &v3;
    var v4: i32 = undefined; _ = &v4;
    v2 = method1(v0);
    v3 = method1(v1);
    v4 = v2 +% v3;
    return v4;
}
fn spiralMain() i32 {
    var v0: i32 = undefined; _ = &v0;
    var v1: i32 = undefined; _ = &v1;
    var v2: *UH0 = undefined; _ = &v2;
    var v3: *UH0 = undefined; _ = &v3;
    var v4: *UH0 = undefined; _ = &v4;
    var v5: i32 = undefined; _ = &v5;
    var v6: i32 = undefined; _ = &v6;
    var v7: *UH0 = undefined; _ = &v7;
    var v8: *UH0 = undefined; _ = &v8;
    var v9: *UH0 = undefined; _ = &v9;
    var v10: i32 = undefined; _ = &v10;
    var v11: i32 = undefined; _ = &v11;
    v0 = @as(i32, 1);
    v1 = @as(i32, 2);
    v2 = UH0_0();
    v3 = UH0_1(v1, v2, v2);
    v4 = UH0_1(v0, v3, v3);
    v5 = @as(i32, 1);
    v6 = @as(i32, 2);
    v7 = UH0_0();
    v8 = UH0_1(v6, v7, v7);
    v9 = UH0_1(v5, v8, v8);
    v10 = method0(v4, v9);
    v11 = v10 -% @as(i32, 10);
    return v11;
}
pub fn main() void {
    spiral_io = spiral_threaded.io();
    spiral_gpa = spiral_arena.allocator();
    var code: i32 = 0;
    const thread = std.Thread.spawn(.{ .stack_size = 1 << 30 }, spiralMainThread, .{&code}) catch @panic("cannot start the main thread");
    thread.join();
    std.process.exit(@truncate(@as(u32, @bitCast(code))));
}
fn spiralMainThread(code: *i32) void {
    code.* = spiralMain();
}
