// Generated by Spiral portable Rust backend.
#![allow(unused_mut, non_snake_case)]

use std::rc::Rc;

fn SpiralStringIndex(value: &Rc<str>, index: i32) -> u8 {
    assert!(index >= 0, "negative Spiral string index");
    let bytes = value.as_bytes();
    let index = index as usize;
    assert!(index < bytes.len(), "Spiral string index out of bounds");
    bytes[index]
}

fn SpiralStringSlice(value: &Rc<str>, from_index: i32, to_index: i32) -> Rc<str> {
    assert!(from_index >= 0, "negative Spiral string slice start");
    let bytes = value.as_bytes();
    let length = bytes.len() as i32;
    assert!(from_index <= length, "Spiral string slice start out of bounds");
    assert!(to_index >= from_index - 1, "invalid Spiral string slice range");
    assert!(to_index < length, "Spiral string slice end out of bounds");
    if to_index < from_index { return Rc::<str>::from(""); }
    let from_index = from_index as usize;
    let to_index = to_index as usize;
    let slice = &bytes[from_index..=to_index];
    Rc::<str>::from(std::str::from_utf8(slice).expect("Spiral string slice must preserve UTF-8 boundaries"))
}

fn SpiralStringConcat(left: &Rc<str>, right: &Rc<str>) -> Rc<str> {
    let mut value = String::with_capacity(left.len() + right.len());
    value.push_str(left);
    value.push_str(right);
    Rc::<str>::from(value.into_boxed_str())
}

fn empty_middle0(v0: Rc<str>) -> Rc<str> {
    let v1: Rc<str>;
    v1 = SpiralStringSlice(&v0, 2, 1);
    return v1;
}

fn empty_end1(v0: Rc<str>) -> Rc<str> {
    let v1: Rc<str>;
    v1 = SpiralStringSlice(&v0, 5, 4);
    return v1;
}

fn empty_source2(v0: Rc<str>) -> Rc<str> {
    let v1: i32;
    v1 = 0 - 1;
    let v2: Rc<str>;
    v2 = SpiralStringSlice(&v0, 0, v1);
    return v2;
}

fn spiral_main() -> i32 {
    let v0: Rc<str>;
    v0 = Rc::<str>::from("alpha");
    let v1: Rc<str>;
    v1 = empty_middle0(v0.clone());
    let v2: Rc<str>;
    v2 = empty_end1(v0.clone());
    let v3: Rc<str>;
    v3 = Rc::<str>::from("");
    let v4: Rc<str>;
    v4 = empty_source2(v3.clone());
    let v5: Rc<str>;
    v5 = SpiralStringConcat(&v1, &v2);
    let v6: Rc<str>;
    v6 = SpiralStringConcat(&v4, &Rc::<str>::from("ok"));
    let v7: Rc<str>;
    v7 = SpiralStringConcat(&v5, &v6);
    let v8: i32;
    v8 = v1.len() as i32;
    let v9: bool;
    v9 = v8 == 0;
    if v9 {
        let v10: i32;
        v10 = v2.len() as i32;
        let v11: bool;
        v11 = v10 == 0;
        if v11 {
            let v12: i32;
            v12 = v4.len() as i32;
            let v13: bool;
            v13 = v12 == 0;
            if v13 {
                let v14: i32;
                v14 = v7.len() as i32;
                let v15: bool;
                v15 = v14 == 2;
                if v15 {
                    let v16: u8;
                    v16 = SpiralStringIndex(&v7, 0);
                    let v17: bool;
                    v17 = v16 == 111;
                    if v17 {
                        let v18: u8;
                        v18 = SpiralStringIndex(&v7, 1);
                        let v19: bool;
                        v19 = v18 == 107;
                        if v19 {
                            return 0;
                        } else {
                            return 1;
                        }
                    } else {
                        return 2;
                    }
                } else {
                    return 3;
                }
            } else {
                return 4;
            }
        } else {
            return 5;
        }
    } else {
        return 6;
    }
}

fn main() {
    std::process::exit(spiral_main());
}
