[package]
name = "eoie-coverage-prune"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
name = "eoie_coverage_prune"
path = "coverage.rs"

[dependencies]
eoie-process = { path = "../eoie_process" }
eoie-process-observation = { path = "../eoie_process_observation" }
eoie-coverage-smoke = { path = "../eoie_coverage_smoke" }
eoie-proxy-search = { path = "../eoie_proxy_search" }
eoie-rust-std-fs = { path = "../rust_std_fs" }
