#![allow(clippy::needless_return, clippy::needless_late_init, clippy::clone_on_copy)]
// Generated by Spiral portable Rust backend.
#![allow(unused_mut, non_snake_case)]

#![allow(dead_code)]
use crate::types_callable::*;

pub fn method0(v0: ClosureValue0) -> i32 {
    return ClosureInvoke0(v0.clone(), 39);
}
