#![allow(unused_mut, non_snake_case, dead_code, clippy::needless_return, clippy::too_many_arguments)]
// Generated by Spiral portable Rust backend.

fn spiral_main() -> i32 {
    let v0: i32 = 0;
    let v1: i32 = 0;
    let v3: i32 = process_batch_plan_domain::eoie_batch_plan_advance(v0, v1);
    let v4: i32 = 1;
    let v6: i32 = process_batch_plan_domain::eoie_batch_plan_advance(v3, v4);
    let v7: i32 = 2;
    let v9: i32 = process_batch_plan_domain::eoie_batch_plan_advance(v6, v7);
    let v10: i32 = 4;
    let v12: i32 = process_batch_plan_domain::eoie_batch_plan_advance(v9, v10);
    let v13: i32 = 0;
    let v14: i32 = 0;
    let v16: i32 = process_batch_plan_domain::eoie_batch_matrix_row_policy(v13, v14);
    let v17: i32 = 1;
    let v18: i32 = 1;
    let v20: i32 = process_batch_plan_domain::eoie_batch_matrix_row_policy(v17, v18);
    let v21: i32 = 0;
    let v22: i32 = 0;
    let v24: i32 = process_batch_plan_domain::eoie_batch_matrix_dependency(v21, v22);
    let v25: i32 = 1;
    let v26: i32 = 1;
    let v28: i32 = process_batch_plan_domain::eoie_batch_matrix_dependency(v25, v26);
    let v29: i32 = 0;
    let v30: i32 = 0;
    let v32: i32 = process_batch_plan_domain::eoie_batch_matrix_observed_accept(v29, v30);
    let v33: i32 = 1;
    let v34: i32 = 1;
    let v36: i32 = process_batch_plan_domain::eoie_batch_matrix_observed_accept(v33, v34);
    let v37: i32 = 1;
    let v38: i32 = 0;
    let v40: i32 = process_batch_plan_domain::eoie_batch_matrix_resume_action(v37, v38);
    let v41: i32 = 2;
    let v42: i32 = 1;
    let v44: i32 = process_batch_plan_domain::eoie_batch_matrix_workspace_policy(v41, v42);
    let v45: i32 = 3;
    let v46: i32 = 1;
    let v48: i32 = process_batch_plan_domain::eoie_batch_matrix_workspace_policy(v45, v46);
    let v49: i32 = 0;
    let v50: i32 = 1;
    let v52: i32 = process_batch_plan_domain::eoie_batch_matrix_workspace_policy(v49, v50);
    let v53: i32 = 4;
    let v54: i32 = 1;
    let v56: i32 = process_batch_plan_domain::eoie_batch_matrix_workspace_policy(v53, v54);
    let v57: bool = v3 == 1;
    if v57 {
        let v58: bool = v6 == 2;
        if v58 {
            let v59: bool = v9 == 3;
            if v59 {
                let v60: bool = v12 == 5;
                if v60 {
                    let v61: bool = v16 == 1;
                    if v61 {
                        let v62: bool = v20 == 1;
                        if v62 {
                            let v63: bool = v24 == 1;
                            if v63 {
                                let v64: bool = v28 == 1;
                                if v64 {
                                    let v65: bool = v32 == 1;
                                    if v65 {
                                        let v66: bool = v36 == 1;
                                        if v66 {
                                            let v67: bool = v40 == 0;
                                            if v67 {
                                                let v68: bool = v44 == 1;
                                                if v68 {
                                                    let v69: bool = v48 == 0;
                                                    if v69 {
                                                        let v70: bool = v52 == 0;
                                                        if v70 {
                                                            let v71: bool = v56 < 0;
                                                            if v71 {
                                                                0
                                                            } else {
                                                                1
                                                            }
                                                        } else {
                                                            1
                                                        }
                                                    } else {
                                                        1
                                                    }
                                                } else {
                                                    1
                                                }
                                            } else {
                                                1
                                            }
                                        } else {
                                            1
                                        }
                                    } else {
                                        1
                                    }
                                } else {
                                    1
                                }
                            } else {
                                1
                            }
                        } else {
                            1
                        }
                    } else {
                        1
                    }
                } else {
                    1
                }
            } else {
                1
            }
        } else {
            1
        }
    } else {
        1
    }
}

fn main() {
    std::process::exit(spiral_main());
}
