// Generated by the Spiral compiler (TypeScript backend). Run: node --experimental-strip-types main.ts, or bun main.ts.
type UH0_0 = { readonly tag: 0, readonly f0: bigint, readonly f1: (() => UH0) }; // Cons
type UH0_1 = { readonly tag: 1 }; // Nil
type UH0 = UH0_0 | UH0_1;
function UH0_0(f0: bigint, f1: (() => UH0)): UH0 { return { tag: 0, f0: f0, f1: f1 }; }
function UH0_1(): UH0 { return { tag: 1 }; }
function closure0(v0: bigint): (() => UH0) {
    return (): UH0 => {
        let v1: bigint = BigInt.asUintN(64, v0 - 1n);
        return method0(v1);
    };
}
function method0(v0: bigint): UH0 {
    let v1: boolean = v0 === 0n;
    if (v1) {
        return UH0_1();
    } else {
        let v3: (() => UH0) = closure0(v0);
        return UH0_0(v0, v3);
    }
}
function method1(v0: UH0, v1: bigint): bigint {
    tail: while (true) {
        switch (v0.tag) {
            case 0: { // Cons
                let v2: bigint = v0.f0;
                let v3: (() => UH0) = v0.f1;
                let v4: UH0 = v3();
                let v5: bigint = BigInt.asUintN(64, v1 + v2);
                {
                    let t0 = v4;
                    let t1 = v5;
                    v0 = t0;
                    v1 = t1;
                }
                continue tail;
                break;
            }
            case 1: { // Nil
                return v1;
                break;
            }
            default: throw new Error("Compiler error: unreachable union case.");
        }
    }
}
export function main(): number {
    let v0: bigint = 10n;
    let v1: UH0 = method0(v0);
    let v2: bigint = 0n;
    let v3: bigint = method1(v1, v2);
    let v4: number = 5;
    let v5: number = Number(BigInt.asIntN(32, v3));
    let v6: number = Math.imul(v4, 2);
    let v7: number = (v4 + v6) | 0;
    let v8: number = (v5 + v7) | 0;
    return v8;
}
process.exitCode = main();
