#![allow(unused_mut, non_snake_case, dead_code, clippy::needless_return, clippy::too_many_arguments)]
// Generated by Spiral portable Rust backend.
#[derive(Clone)]
enum BatchWriteExpectation { Create, Replace(String) }

#[derive(Clone)]
struct BatchWriteItem { relative: String, payload: String, expectation: BatchWriteExpectation }

use eoie_rust_std_fs::{read_regular_limited, read_regular_text_limited, rooted_canonical_directory, rooted_entry_exists, rooted_remove_regular};

fn remove_regular_if_present(path: &std::path::Path) -> Result<(), String> {
    if rooted_entry_exists(path)? { rooted_remove_regular(path)?; }
    Ok(())
}

fn batch_write_compiled_manifest(plan: &std::path::Path) -> Result<String, String> {
    // Canonical providers are mandatory; compile every plan to Plan IR.
    let Some(compiler) = eoie_process::resolve_spiral_compiler(None)? else { return Err("compiled batch-write provider requires a Spiral compiler".to_owned()); };
    let output = plan.with_extension(format!("eoie-plan-ir-{}.ir", std::process::id()));
    let status = eoie_process::compile_spiral_plan_ir(compiler.path.to_string_lossy().as_ref(), plan, &output, 30000)?;
    let manifest_result = if status.success() { read_regular_text_limited(&output, 2 * 1024 * 1024) } else { Err(format!("Spiral Plan IR compilation failed for {}", plan.display())) };
    let _ = remove_regular_if_present(&output);
    let _ = remove_regular_if_present(&std::path::PathBuf::from(format!("{}.spiral-entry", output.display())));
    let _ = remove_regular_if_present(&plan.with_extension("c"));
    let manifest = manifest_result?;
    canonical_plan_ir_domain::parse_plan_ir_manifest(&manifest)?;
    Ok(manifest)
}

fn batch_write_parse(manifest: &str) -> Result<Vec<BatchWriteItem>, String> {
    {
        let rows = canonical_plan_ir_domain::parse_plan_ir_manifest(manifest)?;
        let mut items = Vec::with_capacity(rows.len());
        for row in rows {
            let code = canonical_plan_ir_domain::eoie_plan_ir_decode_code(&row.op, &row.target, &row.expected, &row.payload, &row.effect);
            let item = match code {
                0 => BatchWriteItem { relative: row.target, payload: row.payload, expectation: BatchWriteExpectation::Create },
                1 => BatchWriteItem { relative: row.target, payload: row.payload, expectation: BatchWriteExpectation::Replace(row.expected) },
                _ => return Err("compiled Plan IR contains a non-batch-write operation".to_owned()),
            };
            items.push(item);
        }
        return Ok(items);
    }
}

fn batch_write_rollback(targets: &[std::path::PathBuf], originals: &[Option<Vec<u8>>], staged: &[std::path::PathBuf], promoted: usize) -> Result<(), String> {
    let mut restored = 0usize;
    let mut failures = Vec::new();
    for temporary in staged.iter().skip(promoted) {
        match eoie_rust_std_fs::discard_stage(temporary) { Ok(()) => restored += 1, Err(error) => failures.push(error) }
    }
    for index in (0..promoted).rev() {
        let target = &targets[index];
        let result = match &originals[index] {
            Some(bytes) => eoie_rust_std_fs::atomic_write(target, bytes),
            None => {
                if rooted_entry_exists(target)? { rooted_remove_regular(target) } else { Ok(()) }
            },
        };
        match result { Ok(()) => restored += 1, Err(error) => failures.push(error) }
    }
    let typed = eoie_patch_driver_batch_write_rollback_binding(targets.len() as i32, restored as i32);
    if typed != 1 || !failures.is_empty() {
        return Err(format!("batch rollback incomplete restored={restored}/{} failures={}", targets.len(), failures.join(" | ")));
    }
    Ok(())
}

pub fn filesystem_batch_write_run(args: &[String]) -> Result<(), String> {
    if args.len() != 4 { return Err("fs-batch-write expects preview|apply root plan.spi".to_owned()); }
    let mode = args.get(1).map(String::as_str).unwrap_or("");
    if mode != "preview" && mode != "apply" { return Err("fs-batch-write mode must be preview or apply".to_owned()); }
    let root_input = std::path::Path::new(args.get(2).ok_or_else(|| "missing root".to_owned())?);
    let root = rooted_canonical_directory(root_input)?;
    let plan = std::path::Path::new(args.get(3).ok_or_else(|| "missing plan.spi".to_owned())?);
    if !plan.is_absolute() || plan.extension().and_then(|value| value.to_str()) != Some("spi") {
        return Err("fs-batch-write plan must be an absolute regular .spi file".to_owned());
    }
    let manifest = batch_write_compiled_manifest(plan)?;
    let items = batch_write_parse(&manifest)?;
    let mut seen = std::collections::BTreeSet::new();
    let mut targets = Vec::with_capacity(items.len());
    let mut originals = Vec::with_capacity(items.len());
    for item in &items {
        let relative = eoie_patch_control_domain::patch_safe_relative(&item.relative)?;
        if !seen.insert(relative.clone()) { return Err(format!("duplicate batch target: {}", item.relative)); }
        let target = root.join(relative);
        let original = match &item.expectation {
            BatchWriteExpectation::Create => {
                if rooted_entry_exists(&target)? { return Err(format!("stale create target exists: {}", target.display())); }
                if eoie_patch_driver_batch_write_freshness_binding(0, 1) != 1 { return Err("typed create freshness rejected".to_owned()); }
                None
            }
            BatchWriteExpectation::Replace(expected) => {
                let original = read_regular_limited(&target, usize::MAX)?;
                let observed = eoie_proxy_search::inspection_sha256(original.clone());
                if &observed != expected { return Err(format!("stale replace target expected={expected} observed={observed} path={}", target.display())); }
                if eoie_patch_driver_batch_write_freshness_binding(1, 1) != 1 { return Err("typed replace freshness rejected".to_owned()); }
                Some(original)
            }
        };
        targets.push(target);
        originals.push(original);
    }
    if eoie_patch_driver_batch_write_shape_binding(items.len() as i32, 0) != 1 { return Err("typed batch shape rejected".to_owned()); }
    if mode == "preview" {
        println!("eoie proxy fs-batch-write preview ok rows={} mutation=false", items.len());
        for (item, target) in items.iter().zip(&targets) {
            println!("path={} bytes={} sha256={}", target.display(), item.payload.len(), eoie_proxy_search::inspection_sha256(item.payload.as_bytes().to_vec()));
        }
        return Ok(());
    }
    let mut staged = Vec::with_capacity(items.len());
    for (index, (item, target)) in items.iter().zip(&targets).enumerate() {
        let temporary = match &item.expectation {
            BatchWriteExpectation::Create => eoie_rust_std_fs::stage_new_text(target, &item.payload),
            BatchWriteExpectation::Replace(_) => eoie_rust_std_fs::stage_text(target, &item.payload),
        };
        match temporary {
            Ok(path) => staged.push(path),
            Err(error) => {
                for path in &staged { let _ = eoie_rust_std_fs::discard_stage(path); }
                return Err(format!("stage batch row {index}: {error}"));
            }
        }
    }
    if eoie_patch_driver_batch_write_stage_binding(items.len() as i32, staged.len() as i32) != 1 {
        for path in &staged { let _ = eoie_rust_std_fs::discard_stage(path); }
        return Err("typed batch stage rejected".to_owned());
    }
    let mut promoted = 0usize;
    for (temporary, target) in staged.iter().zip(&targets) {
        if let Err(error) = eoie_rust_std_fs::promote_stage(temporary, target) {
            let rollback = batch_write_rollback(&targets, &originals, &staged, promoted);
            return Err(format!("batch promotion failed: {error}; rollback={rollback:?}"));
        }
        promoted += 1;
    }
    let mut verified = 0usize;
    for (item, target) in items.iter().zip(&targets) {
        match read_regular_limited(target, usize::MAX) {
            Ok(bytes) if bytes == item.payload.as_bytes() => verified += 1,
            other => {
                let rollback = batch_write_rollback(&targets, &originals, &staged, promoted);
                return Err(format!("batch verification failed path={} observed={other:?}; rollback={rollback:?}", target.display()));
            }
        }
    }
    if eoie_patch_driver_batch_write_verify_binding(items.len() as i32, verified as i32) != 1 {
        let rollback = batch_write_rollback(&targets, &originals, &staged, promoted);
        return Err(format!("typed batch verification rejected; rollback={rollback:?}"));
    }
    for target in &targets {
        if target.extension().and_then(|value| value.to_str()) == Some("spi") {
            let source = read_regular_text_limited(target, usize::MAX)?;
            if source.lines().any(|line| line.trim_start().starts_with("inl main")) && let Err(error) = eoie_patch_driver_domain::source_authoring_typecheck(target) {
                let rollback = batch_write_rollback(&targets, &originals, &staged, promoted);
                return Err(format!("batch Spiral typecheck failed: {error}; rollback={rollback:?}"));
            }
        }
    }
    println!("eoie proxy fs-batch-write apply ok rows={} verified={} mutation=true", items.len(), verified);
    Ok(())
}



fn batch_write_shape_binding0(v0: i32, v1: i32) -> i32 {
    let v2: bool = v0 < 1;
    if v2 {
        0
    } else {
        let v3: bool = v1 < 0;
        if v3 {
            0
        } else {
            let v4: bool = 0 < v1;
            if v4 {
                0
            } else {
                1
            }
        }
    }
}

fn batch_write_freshness_binding1(v0: i32, v1: i32) -> i32 {
    let v2: bool = v0 < 0;
    if v2 {
        0
    } else {
        let v3: bool = 1 < v0;
        if v3 {
            0
        } else {
            let v4: bool = v1 < 1;
            if v4 {
                0
            } else {
                1
            }
        }
    }
}

fn batch_write_stage_binding2(v0: i32, v1: i32) -> i32 {
    let v2: bool = v0 < 1;
    if v2 {
        0
    } else {
        let v3: bool = v1 < v0;
        if v3 {
            0
        } else {
            let v4: bool = v0 < v1;
            if v4 {
                0
            } else {
                1
            }
        }
    }
}

fn batch_write_verify_binding3(v0: i32, v1: i32) -> i32 {
    let v2: bool = v0 < 1;
    if v2 {
        0
    } else {
        let v3: bool = v1 < v0;
        if v3 {
            0
        } else {
            let v4: bool = v0 < v1;
            if v4 {
                0
            } else {
                1
            }
        }
    }
}

fn batch_write_rollback_binding4(v0: i32, v1: i32) -> i32 {
    let v2: bool = v0 < 1;
    if v2 {
        0
    } else {
        let v3: bool = v1 < v0;
        if v3 {
            0
        } else {
            let v4: bool = v0 < v1;
            if v4 {
                0
            } else {
                1
            }
        }
    }
}

#[must_use]
pub fn eoie_patch_driver_batch_write_shape_binding(first: i32, second: i32) -> i32 {
    batch_write_shape_binding0(first, second)
}

#[must_use]
pub fn eoie_patch_driver_batch_write_freshness_binding(first: i32, second: i32) -> i32 {
    batch_write_freshness_binding1(first, second)
}

#[must_use]
pub fn eoie_patch_driver_batch_write_stage_binding(first: i32, second: i32) -> i32 {
    batch_write_stage_binding2(first, second)
}

#[must_use]
pub fn eoie_patch_driver_batch_write_verify_binding(first: i32, second: i32) -> i32 {
    batch_write_verify_binding3(first, second)
}

#[must_use]
pub fn eoie_patch_driver_batch_write_rollback_binding(first: i32, second: i32) -> i32 {
    batch_write_rollback_binding4(first, second)
}
