// Generated by Spiral typed stack_mut residual bridge.
#[derive(Clone, Copy)]
struct SpiralStackLayout {
    q: i32,
    w: i32,
}

fn spiral_main() -> i32 {
    let mut a = SpiralStackLayout {
        q: 5i32,
        w: 6i32,
    };
    let _ = &a;
    a.q = 7i32;
    let b = a;
    a.w = 8i32;
    let c = a;
    (b.q + c.w) as i32
}

fn main() {
    std::process::exit(spiral_main());
}
