// Generated by Spiral portable Rust backend.
#![allow(unused_mut, non_snake_case)]

#![allow(dead_code)]

use std::cell::RefCell;
use std::rc::Rc;

type Array0 = Rc<RefCell<Vec<u8>>>;
fn ArrayCreate0(len: i32, _init_at_zero: bool) -> Array0 {
    assert!(len >= 0, "negative Spiral array length");
    Rc::new(RefCell::new(vec![0; len as usize]))
}
fn DynamicArraySet0(array: &Array0, index: i32, value: u8) {
    assert!(index >= 0, "negative Spiral array index");
    let mut data = array.borrow_mut();
    let index = index as usize;
    assert!(index < data.len(), "Spiral array index out of bounds");
    data[index] = value;
}
fn DynamicArrayGet0(array: &Array0, index: i32) -> u8 {
    assert!(index >= 0, "negative Spiral array index");
    let data = array.borrow();
    let index = index as usize;
    assert!(index < data.len(), "Spiral array index out of bounds");
    data[index]
}
fn DynamicArrayLen0(array: &Array0) -> i32 {
    let len = array.borrow().len();
    assert!(len <= i32::MAX as usize, "Spiral array length exceeds i32");
    len as i32
}
fn DynamicArrayDrop0(_array: &Array0) {}

unsafe extern "C" {
    #[link_name = "memset"]
    fn spiral_libc_memset(destination: *mut std::ffi::c_void, byte_value: std::ffi::c_int, count: usize) -> *mut std::ffi::c_void;
}

#[inline]
fn spiral_abi_libc_memset(value: std::rc::Rc<std::cell::RefCell<Vec<u8>>>, byte_value: i32, count: i32) -> i32 {
    assert!(count >= 0, "portable ABI mutable buffer length cannot be negative");
    let count = count as usize;
    let mut data = value.borrow_mut();
    assert!(count <= data.len(), "portable ABI mutable buffer length exceeds buffer");
    if count != 0 {
        unsafe { spiral_libc_memset(data.as_mut_ptr().cast(), byte_value, count); }
    }
    i32::try_from(count).expect("portable ABI mutable buffer length exceeds i32")
}

fn spiral_main() -> i32 {
    let v0: i32;
    v0 = 2;
    let v1: Array0;
    v1 = ArrayCreate0(v0, false);
    DynamicArraySet0(&v1, 0, 0);
    DynamicArraySet0(&v1, 1, 0);
    let v2: i32;
    v2 = 65;
    let v3: i32;
    v3 = 3;
    let v4: i32;
    v4 = spiral_abi_libc_memset(v1.clone(), v2, v3);
    drop(v1);
    return v4;
}

fn main() {
    std::process::exit(spiral_main());
}
