// Generated by Spiral typed heap_refs residual bridge.
use std::cell::Cell;
use std::rc::Rc;

struct SpiralHeapRefs {
    q: Cell<i32>,
    w: Cell<i32>,
}

fn spiral_main() -> i32 {
    let a = Rc::new(SpiralHeapRefs {
        q: Cell::new(11i32),
        w: Cell::new(13i32),
    });
    let b = Rc::clone(&a);
    a.q.set(19i32);
    b.w.set(23i32);
    (a.q.get() + b.w.get()) as i32
}

fn main() {
    std::process::exit(spiral_main());
}
