// Generated by Spiral portable Rust backend.
#![allow(unused_mut, non_snake_case)]

use std::rc::Rc;

#[derive(Clone)]
struct ClosureValue0 {
    v0: Rc<str>,
}

fn ClosureValueCreate0(v0: Rc<str>) -> ClosureValue0 {
    ClosureValue0 { v0 }
}

fn ClosureInvoke0(x: ClosureValue0, v1: i32) -> i32 {
    let v0: Rc<str>;
    v0 = x.v0.clone();
    let v2: i32;
    v2 = v0.len() as i32;
    let v3: i32;
    v3 = v2 + v1;
    return v3;
}

fn apply1(v0: ClosureValue0, v1: i32) -> i32 {
    return ClosureInvoke0(v0.clone(), v1);
}

fn method0(v0: ClosureValue0, v1: i32) -> i32 {
    let v2: i32;
    v2 = apply1(v0.clone(), v1);
    let v3: i32;
    v3 = v2 + 1;
    return v3;
}

fn spiral_main() -> i32 {
    let v0: Rc<str>;
    v0 = Rc::<str>::from("abc");
    let v1: ClosureValue0;
    v1 = ClosureValueCreate0(v0.clone());
    let v2: i32;
    v2 = 38;
    return method0(v1, v2);
}

fn main() {
    std::process::exit(spiral_main());
}
