[package]
name = "eoie-process"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
name = "eoie_process"
path = "process.rs"

[dependencies]
eoie-compiler-discovery = { path = "../eoie_compiler_discovery" }
eoie-process-streaming = { path = "../eoie_process_streaming" }
