// Generated by the Spiral compiler (Zig backend). Build: zig build-exe main.zig -O ReleaseSafe (or -O Debug -fno-llvm: seconds)
const std = @import("std");
var spiral_threaded: std.Io.Threaded = .init_single_threaded;
var spiral_arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
var spiral_io: std.Io = undefined;
var spiral_gpa: std.mem.Allocator = undefined;
var spiral_true: bool = true;
fn spiralPrint(s: []const u8) void {
    std.Io.File.stdout().writeStreamingAll(spiral_io, s) catch {};
}
fn spiralPrintAny(x: anytype) void {
    const T = @TypeOf(x);
    if (T == []const u8) return spiralPrint(x);
    const s = switch (@typeInfo(T)) {
        .float => std.fmt.allocPrint(spiral_gpa, "{d}", .{x}),
        .bool => std.fmt.allocPrint(spiral_gpa, "{}", .{x}),
        else => std.fmt.allocPrint(spiral_gpa, "{d}", .{x}),
    } catch @panic("out of memory");
    spiralPrint(s);
}
fn spiralFail(s: []const u8) noreturn {
    std.Io.File.stderr().writeStreamingAll(spiral_io, s) catch {};
    std.Io.File.stderr().writeStreamingAll(spiral_io, "\n") catch {};
    std.process.exit(1);
}
fn spiralConv(comptime T: type, x: anytype) T {
    const S = @TypeOf(x);
    if (@typeInfo(T) == .float) {
        if (@typeInfo(S) == .float) return @floatCast(x) else return @floatFromInt(x);
    }
    if (@typeInfo(S) == .float) return @intFromFloat(x);
    const U = @Int(.unsigned, @bitSizeOf(T));
    const wide: i128 = x;
    return @bitCast(@as(U, @truncate(@as(u128, @bitCast(wide)))));
}
fn spiralConcat(a: []const u8, b: []const u8) []const u8 {
    return std.mem.concat(spiral_gpa, u8, &.{ a, b }) catch @panic("out of memory");
}
fn spiralStringSlice(s: []const u8, from: i64, upto: i64) []const u8 {
    const len: i64 = @intCast(s.len);
    if (from < 0 or from > len or upto < from - 1 or upto >= len) std.process.exit(3);
    if (upto < from) return "";
    const a: usize = @intCast(from);
    const b: usize = @intCast(upto + 1);
    if ((s[a] & 0xC0) == 0x80 or (b < s.len and (s[b] & 0xC0) == 0x80)) std.process.exit(3);
    return s[a..b];
}
fn spiralIndex(len: usize, i: anytype) usize {
    if (i < 0 or i >= len) std.process.exit(3);
    return @intCast(i);
}
fn spiralNewArray(comptime T: type, n: anytype) []T {
    const len: usize = @intCast(n);
    const a = spiral_gpa.alloc(T, len) catch @panic("out of memory");
    switch (@typeInfo(T)) {
        .int, .float, .bool => @memset(a, std.mem.zeroes(T)),
        else => if (T == []const u8) @memset(a, ""),
    }
    return a;
}
fn spiralCreate(comptime T: type, v: T) *T {
    const p = spiral_gpa.create(T) catch @panic("out of memory");
    p.* = v;
    return p;
}
fn spiralMain() i32 {
    var v0: f32 = undefined; _ = &v0;
    var v1: f32 = undefined; _ = &v1;
    var v2: f64 = undefined; _ = &v2;
    var v3: f64 = undefined; _ = &v3;
    var v4: f32 = undefined; _ = &v4;
    var v5: f64 = undefined; _ = &v5;
    var v6: f32 = undefined; _ = &v6;
    var v7: bool = undefined; _ = &v7;
    var v10: bool = undefined; _ = &v10;
    var v8: f64 = undefined; _ = &v8;
    var v9: bool = undefined; _ = &v9;
    var v12: bool = undefined; _ = &v12;
    var v11: bool = undefined; _ = &v11;
    var v14: bool = undefined; _ = &v14;
    var v13: bool = undefined; _ = &v13;
    var v16: bool = undefined; _ = &v16;
    var v15: bool = undefined; _ = &v15;
    var v18: bool = undefined; _ = &v18;
    var v17: bool = undefined; _ = &v17;
    v0 = @as(f32, 2.0);
    v1 = @as(f32, 3.0);
    v2 = @as(f64, 2.0);
    v3 = @as(f64, 3.0);
    v4 = @as(f32, 3.1415927);
    v5 = @as(f64, 3.141592653589793);
    v6 = std.math.pow(@TypeOf(v0), v0, v1);
    v7 = v6 == @as(f32, 8.0);
    if (v7) {
        v8 = std.math.pow(@TypeOf(v2), v2, v3);
        v9 = v8 == @as(f64, 8.0);
        v10 = v9;
    } else {
        v10 = false;
    }
    if (v10) {
        v11 = v4 > @as(f32, 3.0);
        v12 = v11;
    } else {
        v12 = false;
    }
    if (v12) {
        v13 = v4 < @as(f32, 4.0);
        v14 = v13;
    } else {
        v14 = false;
    }
    if (v14) {
        v15 = v5 > @as(f64, 3.0);
        v16 = v15;
    } else {
        v16 = false;
    }
    if (v16) {
        v17 = v5 < @as(f64, 4.0);
        v18 = v17;
    } else {
        v18 = false;
    }
    if (v18) {
        return @as(i32, 0);
    } else {
        return @as(i32, 1);
    }
}
pub fn main() void {
    spiral_io = spiral_threaded.io();
    spiral_gpa = spiral_arena.allocator();
    var code: i32 = 0;
    const thread = std.Thread.spawn(.{ .stack_size = 1 << 30 }, spiralMainThread, .{&code}) catch @panic("cannot start the main thread");
    thread.join();
    std.process.exit(@truncate(@as(u32, @bitCast(code))));
}
fn spiralMainThread(code: *i32) void {
    code.* = spiralMain();
}
