// Generated by Spiral portable Rust backend.
#![allow(unused_mut, non_snake_case)]

fn spiral_main() -> i32 {
    let v0: f32;
    v0 = f32::NAN;
    let v1: f64;
    v1 = f64::NAN;
    let v2: f32;
    v2 = 1.0;
    let v3: f64;
    v3 = 1.0;
    let v4: bool;
    v4 = (v0).is_nan();
    let mut v6: bool;
    if v4 {
        let v5: bool;
        v5 = (v1).is_nan();
        v6 = v5;
    } else {
        v6 = false;
    }
    if v6 {
        let v7: bool;
        v7 = (v2).is_nan();
        let mut v9: bool;
        if v7 {
            v9 = true;
        } else {
            let v8: bool;
            v8 = (v3).is_nan();
            v9 = v8;
        }
        if v9 {
            return 2;
        } else {
            return 0;
        }
    } else {
        return 1;
    }
}

fn main() {
    std::process::exit(spiral_main());
}
