// Generated by Spiral portable Rust backend.
#![allow(unused_mut, non_snake_case)]

use std::rc::Rc;

#[derive(Clone)]
struct Tuple9000 {
    v0: i32,
    v1: Rc<str>,
}

fn TupleCreate9000(v0: i32, v1: Rc<str>) -> Tuple9000 {
    Tuple9000 { v0, v1 }
}

#[derive(Clone, Copy)]
struct ClosureValue0 {
}

fn ClosureValueCreate0() -> ClosureValue0 {
    ClosureValue0 {  }
}

fn ClosureInvoke0(__x: ClosureValue0, _v0: i32) -> Tuple9000 {
    let v1: Rc<str>;
    v1 = Rc::<str>::from("managed");
    return TupleCreate9000(1, v1.clone());
}

fn method0(v0: ClosureValue0) -> Tuple9000 {
    return ClosureInvoke0(v0.clone(), 2);
}

fn spiral_main() -> i32 {
    let v0: ClosureValue0;
    v0 = ClosureValueCreate0();
    let v1: Tuple9000;
    v1 = method0(v0.clone());
    let mut v4: i32;
    if v1.v0 == 0 {
        v4 = 3;
    } else {
        v4 = 11;
    }
    if v1.v0 == 1 {
        drop(v1.v1);
    }
    let v5: i32;
    v5 = v4 + 31;
    return v5;
}

fn main() {
    std::process::exit(spiral_main());
}
