// Generated by Spiral portable Rust backend.
#![allow(unused_mut, non_snake_case)]

#[repr(C)]
struct SpiralLibcDivResult {
    quot: i32,
    rem: i32,
}

unsafe extern "C" {
    #[link_name = "div"]
    fn spiral_libc_div(numerator: i32, denominator: i32) -> SpiralLibcDivResult;
}

#[inline]
fn spiral_abi_libc_div_pack(numerator: i32, denominator: i32) -> i32 {
    assert!(denominator != 0, "portable ABI div denominator cannot be zero");
    let result = unsafe { spiral_libc_div(numerator, denominator) };
    result.quot.checked_mul(10).and_then(|value| value.checked_add(result.rem)).expect("portable ABI packed div result overflow")
}

fn spiral_main() -> i32 {
    let v0: i32;
    v0 = spiral_abi_libc_div_pack(17, 5);
    return v0;
}

fn main() {
    std::process::exit(spiral_main());
}
