// Generated by Spiral portable Rust backend.
#![allow(unused_mut, non_snake_case)]

#![allow(dead_code)]

use std::cell::RefCell;
use std::rc::Rc;

type Array0 = Rc<RefCell<Vec<i32>>>;
fn ArrayCreate0(len: i32, _init_at_zero: bool) -> Array0 {
    assert!(len >= 0, "negative Spiral array length");
    Rc::new(RefCell::new(vec![0; len as usize]))
}
fn DynamicArraySet0(array: &Array0, index: i32, value: i32) {
    assert!(index >= 0, "negative Spiral array index");
    let mut data = array.borrow_mut();
    let index = index as usize;
    assert!(index < data.len(), "Spiral array index out of bounds");
    data[index] = value;
}
fn DynamicArrayGet0(array: &Array0, index: i32) -> i32 {
    assert!(index >= 0, "negative Spiral array index");
    let data = array.borrow();
    let index = index as usize;
    assert!(index < data.len(), "Spiral array index out of bounds");
    data[index]
}
fn DynamicArrayLen0(array: &Array0) -> i32 {
    let len = array.borrow().len();
    assert!(len <= i32::MAX as usize, "Spiral array length exceeds i32");
    len as i32
}
fn DynamicArrayReserve0(array: &Array0, capacity: i32) {
    assert!(capacity >= 0, "negative Spiral array capacity");
    let mut data = array.borrow_mut();
    let requested = capacity as usize;
    let current = data.capacity();
    if requested > current {
        let mut target = current.max(1);
        while target < requested {
            match target.checked_mul(2) {
                Some(next) => target = next,
                None => { target = requested; break; }
            }
        }
        let additional = target.saturating_sub(data.len());
        data.reserve_exact(additional);
    }
}
fn DynamicArrayCapacity0(array: &Array0) -> i32 {
    let capacity = array.borrow().capacity();
    assert!(capacity <= i32::MAX as usize, "Spiral array capacity exceeds i32");
    capacity as i32
}
fn DynamicArrayRefCount0(array: &Array0) -> i32 {
    let count = Rc::strong_count(array);
    assert!(count <= i32::MAX as usize, "Spiral array reference count exceeds i32");
    count as i32
}
fn DynamicArrayClone0(_array: &Array0) {}
fn DynamicArrayDrop0(_array: &Array0) {}

#[derive(Clone)]
struct Tuple9000 {
    v0: i32,
    v1: Array0,
}

fn TupleCreate9000(v0: i32, v1: Array0) -> Tuple9000 {
    Tuple9000 { v0, v1 }
}

fn method0(v0: Array0) -> () {
    let v1: i32;
    v1 = 1;
    DynamicArrayReserve0(&v0, v1);
    drop(v0);
    return;
}

fn method1(v0: Array0) -> i32 {
    let v1: i32;
    v1 = DynamicArrayCapacity0(&v0);
    drop(v0);
    return v1;
}

fn method2(v0: Array0) -> () {
    let v1: i32;
    v1 = 2;
    DynamicArrayReserve0(&v0, v1);
    drop(v0);
    return;
}

fn method3(v0: Array0) -> i32 {
    let v1: i32;
    v1 = DynamicArrayCapacity0(&v0);
    drop(v0);
    return v1;
}

fn method4(v0: Array0) -> () {
    let v1: i32;
    v1 = 3;
    DynamicArrayReserve0(&v0, v1);
    drop(v0);
    return;
}

fn method5(v0: Array0) -> i32 {
    let v1: i32;
    v1 = DynamicArrayCapacity0(&v0);
    drop(v0);
    return v1;
}

fn method6(v0: Array0) -> () {
    let v1: i32;
    v1 = 5;
    DynamicArrayReserve0(&v0, v1);
    drop(v0);
    return;
}

fn method7(v0: Array0) -> i32 {
    let v1: i32;
    v1 = DynamicArrayCapacity0(&v0);
    drop(v0);
    return v1;
}

fn method8(v0: Array0) -> () {
    let v1: i32;
    v1 = 9;
    DynamicArrayReserve0(&v0, v1);
    drop(v0);
    return;
}

fn method9(v0: Array0) -> i32 {
    let v1: i32;
    v1 = DynamicArrayCapacity0(&v0);
    drop(v0);
    return v1;
}

fn method10(v0: Array0) -> i32 {
    let v1: i32;
    v1 = DynamicArrayRefCount0(&v0);
    drop(v0);
    return v1;
}

fn method13(v0: Array0) -> i32 {
    let v1: i32;
    v1 = DynamicArrayRefCount0(&v0);
    drop(v0);
    return v1;
}

fn method12(v0: Array0) -> i32 {
    let v1: i32;
    v1 = DynamicArrayCapacity0(&v0);
    DynamicArrayClone0(&v0);
    let v2: i32;
    v2 = method13(v0.clone());
    drop(v0);
    let v3: i32;
    v3 = v1 + v2;
    return v3;
}

fn observe11(v0: Tuple9000) -> i32 {
    if v0.v0 == 0 {
        drop(v0);
        return 70;
    } else {
        let v1: Array0;
        v1 = v0.v1.clone();
        DynamicArrayClone0(&v1);
        drop(v0);
        return method12(v1);
    }
}

fn method14(v0: Array0) -> i32 {
    let v1: i32;
    v1 = DynamicArrayRefCount0(&v0);
    drop(v0);
    return v1;
}

fn spiral_main() -> i32 {
    let v0: Array0;
    v0 = ArrayCreate0(0, false);
    DynamicArrayClone0(&v0);
    method0(v0.clone());
    DynamicArrayClone0(&v0);
    let v1: i32;
    v1 = method1(v0.clone());
    DynamicArrayClone0(&v0);
    method2(v0.clone());
    DynamicArrayClone0(&v0);
    let v2: i32;
    v2 = method3(v0.clone());
    DynamicArrayClone0(&v0);
    method4(v0.clone());
    DynamicArrayClone0(&v0);
    let v3: i32;
    v3 = method5(v0.clone());
    DynamicArrayClone0(&v0);
    method6(v0.clone());
    DynamicArrayClone0(&v0);
    let v4: i32;
    v4 = method7(v0.clone());
    DynamicArrayClone0(&v0);
    method8(v0.clone());
    DynamicArrayClone0(&v0);
    let v5: i32;
    v5 = method9(v0.clone());
    DynamicArrayClone0(&v0);
    let v6: i32;
    v6 = method10(v0.clone());
    DynamicArrayClone0(&v0);
    let v7: Tuple9000;
    v7 = TupleCreate9000(1, v0.clone());
    if v7.v0 == 1 {
        DynamicArrayClone0(&v7.v1);
    }
    let v8: i32;
    v8 = observe11(v7.clone());
    DynamicArrayClone0(&v0);
    drop(v7);
    let v9: i32;
    v9 = method14(v0.clone());
    drop(v0);
    let v10: i32;
    v10 = v1 - 1;
    let v11: i32;
    v11 = v2 - 2;
    let v12: i32;
    v12 = v10 + v11;
    let v13: i32;
    v13 = v3 - 4;
    let v14: i32;
    v14 = v12 + v13;
    let v15: i32;
    v15 = v4 - 8;
    let v16: i32;
    v16 = v14 + v15;
    let v17: i32;
    v17 = v5 - 16;
    let v18: i32;
    v18 = v16 + v17;
    let v19: i32;
    v19 = v6 - 2;
    let v20: i32;
    v20 = v18 + v19;
    let v21: i32;
    v21 = v8 - 20;
    let v22: i32;
    v22 = v20 + v21;
    let v23: i32;
    v23 = v9 - 2;
    let v24: i32;
    v24 = v22 + v23;
    return v24;
}

fn main() {
    std::process::exit(spiral_main());
}
