#![allow(unused_mut, non_snake_case, dead_code, clippy::needless_return, clippy::too_many_arguments)]
// Generated by Spiral portable Rust backend.

fn fingerprint_byte_valid_binding0(v0: i32, v1: i32) -> i32 {
    let v2: bool = v0 < 0;
    if v2 {
        0
    } else {
        let v3: bool = 255 < v0;
        if v3 {
            0
        } else {
            let v4: bool = v1 < 0;
            if v4 {
                0
            } else {
                let v5: bool = 0 < v1;
                if v5 {
                    0
                } else {
                    1
                }
            }
        }
    }
}

fn fingerprint_mix_low_binding1(v0: i32, v1: i32) -> i32 {
    let v3: i32 = v0 ^ v1;
    v3
}

fn fingerprint_low_step_binding2(v0: i32, v1: i32) -> i32 {
    let v3: i32 = if v1 == 0 { ((v0 as u32).wrapping_mul(435)) as i32 } else { v0 };
    v3
}

fn fingerprint_high_step_binding3(v0: i32, v1: i32) -> i32 {
    let v3: i32 = (((((v0 as u32 as u64) * 435) + ((v1 as u32 as u64) * 256) + (((v1 as u32 as u64) * 435) >> 32)) & 0xffff_ffff) as u32) as i32;
    v3
}

#[must_use]
pub fn eoie_state_receipt_byte_valid(first: i32, second: i32) -> i32 {
    fingerprint_byte_valid_binding0(first, second)
}

#[must_use]
pub fn eoie_state_receipt_mix_low(first: i32, second: i32) -> i32 {
    fingerprint_mix_low_binding1(first, second)
}

#[must_use]
pub fn eoie_state_receipt_low_step(first: i32, second: i32) -> i32 {
    fingerprint_low_step_binding2(first, second)
}

#[must_use]
pub fn eoie_state_receipt_high_step(first: i32, second: i32) -> i32 {
    fingerprint_high_step_binding3(first, second)
}
