// Generated by Spiral portable Rust backend.
#![allow(unused_mut, non_snake_case)]

#[derive(Clone, Copy)]
struct ClosureValue0 {
    variant: i32,
}

fn ClosureValueCreate0(variant: i32) -> ClosureValue0 {
    ClosureValue0 { variant }
}

fn ClosureInvoke0(x: ClosureValue0, v0: i32) -> i32 {
    if x.variant == 0 {
        let closure0_v1: i32;
        closure0_v1 = v0 + 2;
        return closure0_v1;
    } else {
        let closure1_v1: i32;
        closure1_v1 = v0 + 3;
        return closure1_v1;
    }
}

fn method0(v0: ClosureValue0) -> i32 {
    return ClosureInvoke0(v0, 40);
}

fn spiral_main() -> i32 {
    let v0: bool;
    v0 = true;
    let mut v3: ClosureValue0;
    if v0 {
        v3 = ClosureValueCreate0(0);
    } else {
        v3 = ClosureValueCreate0(1);
    }
    return method0(v3);
}

fn main() {
    std::process::exit(spiral_main());
}
