#![allow(unused_mut, unused_variables, unused_imports, unused_parens, unused_braces, unused_assignments, dead_code, non_snake_case, non_camel_case_types, unreachable_patterns, unreachable_code, while_true)]
use std::cell::RefCell;
use std::rc::Rc;
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Default, Debug, Eq, PartialEq)]
struct SourceTopology {
    spiral_lines: usize,
    rust_lines: usize,
    spiral_source_files: usize,
    rust_source_files: usize,
    rust_global_sites: usize,
    rust_max_lines: usize,
    rust_max_file: String,
    cargo_crates: usize,
    spiral_packages: usize,
    package_only: usize,
    crate_max_lines: usize,
    crate_max: String,
}

#[derive(Default, Debug, Eq, PartialEq)]
struct GenericSurfaceStats {
    own_spiral_lines: usize,
    own_rust_lines: usize,
    generated_rust_lines: usize,
    vendor_spiral_lines: usize,
    vendor_rust_lines: usize,
    own_spiral_files: usize,
    own_rust_files: usize,
    generated_rust_files: usize,
    vendor_spiral_files: usize,
    vendor_rust_files: usize,
    vendor_cargo_crates: usize,
    vendor_spiral_packages: usize,
}

fn topology_arg<'a>(args: &'a [String], index: usize, name: &str) -> Result<&'a str, String> {
    args.get(index).map(String::as_str).ok_or_else(|| format!("missing argument: {name}"))
}

fn topology_skip(path: &Path) -> bool {
    matches!(path.file_name().and_then(|value| value.to_str()), Some("vendor" | "target" | ".git"))
}

fn topology_entries(path: &Path) -> Result<Vec<PathBuf>, String> {
    let mut entries = fs::read_dir(path)
        .map_err(|error| format!("read {}: {error}", path.display()))?
        .map(|entry| entry.map(|value| value.path()).map_err(|error| error.to_string()))
        .collect::<Result<Vec<_>, _>>()?;
    entries.sort();
    Ok(entries)
}

fn topology_lines(path: &Path) -> Result<usize, String> {
    let bytes = fs::read(path).map_err(|error| format!("read {}: {error}", path.display()))?;
    if bytes.is_empty() { return Ok(0); }
    Ok(bytes.iter().filter(|byte| **byte == b'\n').count() + usize::from(!bytes.ends_with(b"\n")))
}

fn topology_relative(root: &Path, path: &Path) -> String {
    path.strip_prefix(root).unwrap_or(path).to_string_lossy().replace('\\', "/")
}

fn topology_generic_ignore(path: &Path) -> bool {
    match path.file_name().and_then(|value| value.to_str()) {
        Some(".git") => true,
        Some("target") => path.join("CACHEDIR.TAG").is_file(),
        _ => false,
    }
}

fn topology_generic_vendor_dir(path: &Path) -> bool {
    path.file_name().and_then(|value| value.to_str()) == Some("vendor")
}

fn topology_generated_rust(path: &Path) -> Result<bool, String> {
    let bytes = fs::read(path).map_err(|error| format!("read {}: {error}", path.display()))?;
    let marker = b"Generated by Spiral portable Rust backend.";
    Ok(bytes.windows(marker.len()).any(|window| window == marker))
}

fn topology_generic_crate_lines(path: &Path) -> Result<usize, String> {
    let metadata = fs::symlink_metadata(path).map_err(|error| format!("metadata {}: {error}", path.display()))?;
    if metadata.file_type().is_symlink() { return Err(format!("source-stats rejects symlink: {}", path.display())); }
    if metadata.is_dir() {
        if topology_generic_ignore(path) || topology_generic_vendor_dir(path) { return Ok(0); }
        let mut total = 0usize;
        for child in topology_entries(path)? { total += topology_generic_crate_lines(&child)?; }
        return Ok(total);
    }
    if metadata.is_file() && matches!(path.extension().and_then(|value| value.to_str()), Some("rs" | "spi" | "spir")) { topology_lines(path) } else { Ok(0) }
}

fn topology_generic_walk(root: &Path, path: &Path, inherited_vendor: bool, stats: &mut SourceTopology, surfaces: &mut GenericSurfaceStats) -> Result<(), String> {
    let metadata = fs::symlink_metadata(path).map_err(|error| format!("metadata {}: {error}", path.display()))?;
    if metadata.file_type().is_symlink() { return Err(format!("source-stats rejects symlink: {}", path.display())); }
    let vendor = inherited_vendor || (path != root && topology_generic_vendor_dir(path));
    if metadata.is_dir() {
        if path != root && topology_generic_ignore(path) { return Ok(()); }
        for child in topology_entries(path)? { topology_generic_walk(root, &child, vendor, stats, surfaces)?; }
        return Ok(());
    }
    if !metadata.is_file() { return Ok(()); }
    let lines = topology_lines(path)?;
    match path.extension().and_then(|value| value.to_str()) {
        Some("spi") | Some("spir") => {
            let class = eoie_source_surface_binding(i32::from(vendor), 0);
            if class == 2 { surfaces.vendor_spiral_lines += lines; surfaces.vendor_spiral_files += 1; }
            else if class == 0 {
                surfaces.own_spiral_lines += lines; surfaces.own_spiral_files += 1;
                stats.spiral_lines += lines; stats.spiral_source_files += 1;
                let text = fs::read_to_string(path).map_err(|error| format!("read {}: {error}", path.display()))?;
                stats.rust_global_sites += text.matches("rust_global \"").count();
            } else { return Err("Spiral source received invalid generated classification".to_owned()); }
        }
        Some("rs") => {
            let generated = topology_generated_rust(path)?;
            let class = eoie_source_surface_binding(i32::from(vendor), i32::from(generated));
            if class == 2 { surfaces.vendor_rust_lines += lines; surfaces.vendor_rust_files += 1; }
            else {
                if class == 1 { surfaces.generated_rust_lines += lines; surfaces.generated_rust_files += 1; }
                else if class == 0 { surfaces.own_rust_lines += lines; surfaces.own_rust_files += 1; }
                else { return Err("Rust source received invalid surface classification".to_owned()); }
                stats.rust_lines += lines; stats.rust_source_files += 1;
                let relative = topology_relative(root, path);
                if lines > stats.rust_max_lines || (lines == stats.rust_max_lines && relative < stats.rust_max_file) { stats.rust_max_lines = lines; stats.rust_max_file = relative; }
            }
        }
        _ => {}
    }
    Ok(())
}

fn topology_walk(root: &Path, path: &Path, stats: &mut SourceTopology) -> Result<(), String> {
    let metadata = fs::symlink_metadata(path).map_err(|error| format!("metadata {}: {error}", path.display()))?;
    if metadata.file_type().is_symlink() { return Err(format!("source-topology rejects symlink: {}", path.display())); }
    if metadata.is_dir() {
        if path != root && topology_skip(path) { return Ok(()); }
        for child in topology_entries(path)? { topology_walk(root, &child, stats)?; }
        return Ok(());
    }
    if !metadata.is_file() { return Ok(()); }
    let lines = topology_lines(path)?;
    match path.extension().and_then(|value| value.to_str()) {
        Some("spi") | Some("spir") => {
            stats.spiral_lines += lines;
            stats.spiral_source_files += 1;
            let text = fs::read_to_string(path).map_err(|error| format!("read {}: {error}", path.display()))?;
            stats.rust_global_sites += text.matches("rust_global \"").count();
        }
        Some("rs") => {
            stats.rust_lines += lines;
            stats.rust_source_files += 1;
            let relative = topology_relative(root, path);
            if lines > stats.rust_max_lines || (lines == stats.rust_max_lines && relative < stats.rust_max_file) {
                stats.rust_max_lines = lines;
                stats.rust_max_file = relative;
            }
        }
        _ => {}
    }
    Ok(())
}

fn topology_crate_lines(path: &Path) -> Result<usize, String> {
    let metadata = fs::symlink_metadata(path).map_err(|error| format!("metadata {}: {error}", path.display()))?;
    if metadata.file_type().is_symlink() { return Err(format!("source-topology rejects symlink: {}", path.display())); }
    if metadata.is_dir() {
        if topology_skip(path) { return Ok(0); }
        let mut total = 0usize;
        for child in topology_entries(path)? { total += topology_crate_lines(&child)?; }
        return Ok(total);
    }
    if metadata.is_file() && matches!(path.extension().and_then(|value| value.to_str()), Some("rs" | "spi" | "spir")) { topology_lines(path) } else { Ok(0) }
}

fn topology_generic_packages(root: &Path, path: &Path, inherited_vendor: bool, stats: &mut SourceTopology, surfaces: &mut GenericSurfaceStats) -> Result<(), String> {
    let metadata = fs::symlink_metadata(path).map_err(|error| format!("metadata {}: {error}", path.display()))?;
    if metadata.file_type().is_symlink() { return Err(format!("source-stats rejects symlink: {}", path.display())); }
    if !metadata.is_dir() { return Ok(()); }
    if path != root && topology_generic_ignore(path) { return Ok(()); }
    let vendor = inherited_vendor || (path != root && topology_generic_vendor_dir(path));
    let cargo_manifest = path.join("Cargo.toml");
    let cargo = if cargo_manifest.is_file() { fs::read_to_string(&cargo_manifest).map_err(|error| format!("read {}: {error}", cargo_manifest.display()))?.lines().any(|line| line.trim() == "[package]") } else { false };
    let spiral = path.join("package.spiproj").is_file();
    if vendor {
        if spiral { surfaces.vendor_spiral_packages += 1; }
        if cargo { surfaces.vendor_cargo_crates += 1; }
    } else {
        if spiral { stats.spiral_packages += 1; }
        if cargo {
            stats.cargo_crates += 1;
            let lines = topology_generic_crate_lines(path)?;
            let name = topology_relative(root, path);
            if lines > stats.crate_max_lines || (lines == stats.crate_max_lines && name < stats.crate_max) { stats.crate_max_lines = lines; stats.crate_max = name; }
        } else if spiral {
            stats.package_only += 1;
        }
    }
    for child in topology_entries(path)? { if child.is_dir() { topology_generic_packages(root, &child, vendor, stats, surfaces)?; } }
    Ok(())
}

fn topology_collect_generic(root: &Path) -> Result<(SourceTopology, GenericSurfaceStats), String> {
    if !root.is_dir() { return Err(format!("source-stats root is not a directory: {}", root.display())); }
    let mut stats = SourceTopology::default();
    let mut surfaces = GenericSurfaceStats::default();
    topology_generic_walk(root, root, false, &mut stats, &mut surfaces)?;
    topology_generic_packages(root, root, false, &mut stats, &mut surfaces)?;
    Ok((stats, surfaces))
}

pub fn source_topology_counts(root: &Path) -> Result<[usize;10], String> {
    let stats = topology_collect(root)?;
    Ok([stats.spiral_source_files, stats.rust_source_files, stats.rust_global_sites, stats.spiral_lines, stats.rust_lines, stats.cargo_crates, stats.spiral_packages, stats.package_only, stats.crate_max_lines, stats.rust_max_lines])
}

fn topology_collect(root: &Path) -> Result<SourceTopology, String> {
    if !root.is_dir() { return Err(format!("source-topology root is not a directory: {}", root.display())); }
    let mut stats = SourceTopology::default();
    topology_walk(root, root, &mut stats)?;
    let source_root = root.join("src");
    if source_root.is_dir() {
        for package_root in topology_entries(&source_root)? {
            if !package_root.is_dir() || topology_skip(&package_root) { continue; }
            let cargo = package_root.join("Cargo.toml").is_file();
            let spiral = package_root.join("package.spiproj").is_file();
            if spiral { stats.spiral_packages += 1; }
            if cargo {
                stats.cargo_crates += 1;
                let lines = topology_crate_lines(&package_root)?;
                let name = package_root.file_name().and_then(|value| value.to_str()).unwrap_or_default().to_owned();
                if lines > stats.crate_max_lines || (lines == stats.crate_max_lines && name < stats.crate_max) {
                    stats.crate_max_lines = lines;
                    stats.crate_max = name;
                }
            } else if spiral {
                stats.package_only += 1;
            }
        }
    }
    Ok(stats)
}

fn topology_census_text(stats: &SourceTopology) -> String {
    format!("union authority_census =\n    | AuthorityCensus :: u32 * u32 * u32 * u32 * u32 * u32 * u32 * u32 * u32 * u32 -> authority_census\n\ninl current_authority_census () : authority_census =\n    AuthorityCensus ({}u32, {}u32, {}u32, {}u32, {}u32, {}u32, {}u32, {}u32, {}u32, {}u32)\n\ninl census_authority () : string = \"source-topology\"\ninl main () : i32 = 0i32\n", stats.spiral_source_files, stats.rust_source_files, stats.rust_global_sites, stats.spiral_lines, stats.rust_lines, stats.cargo_crates, stats.spiral_packages, stats.package_only, stats.crate_max_lines, stats.rust_max_lines)
}

fn topology_write_census(root: &Path, relative: &str, stats: &SourceTopology) -> Result<(), String> {
    if relative != "state/authority_census.spi" { return Err("source-topology census output must be state/authority_census.spi".to_owned()); }
    let path = root.join(relative);
    let parent = path.parent().ok_or_else(|| "authority census parent missing".to_owned())?;
    fs::create_dir_all(parent).map_err(|error| format!("create {}: {error}", parent.display()))?;
    let stage = parent.join(format!(".authority-census-{}", std::process::id()));
    let body = topology_census_text(stats);
    fs::write(&stage, body.as_bytes()).map_err(|error| format!("write {}: {error}", stage.display()))?;
    fs::rename(&stage, &path).map_err(|error| format!("commit {}: {error}", path.display()))?;
    Ok(())
}

pub fn refresh_authority_census(root: &Path) -> Result<(), String> {
    let args = vec!["source-topology".to_owned(), root.to_string_lossy().into_owned(), "state/authority_census.spi".to_owned()];
    source_topology_run(&args)
}

pub fn source_stats_run(args: &[String]) -> Result<(), String> {
    if args.len() != 2 { return Err("source-stats expects root".to_owned()); }
    let root = Path::new(topology_arg(args, 1, "root")?);
    let (stats, surfaces) = topology_collect_generic(root)?;
    let limits = eoie_source_topology_limit_binding(stats.rust_max_lines as i32, stats.crate_max_lines as i32);
    let own_lines = surfaces.own_spiral_lines + surfaces.own_rust_lines;
    let product_lines = own_lines + surfaces.generated_rust_lines;
    let vendor_lines = surfaces.vendor_spiral_lines + surfaces.vendor_rust_lines;
    println!("eoie proxy source-stats ok root={} scope=classified-source package_discovery=recursive classification_policy=vendor-segment+spiral-generated-marker build_target_policy=cachedir-tag", root.display());
    println!("own_lines={} generated_lines={} vendor_lines={} product_lines={} all_source_lines={} total_growth_policy=report-only", own_lines, surfaces.generated_rust_lines, vendor_lines, product_lines, product_lines + vendor_lines);
    println!("own_spiral_lines={} own_rust_lines={} generated_rust_lines={} vendor_spiral_lines={} vendor_rust_lines={}", surfaces.own_spiral_lines, surfaces.own_rust_lines, surfaces.generated_rust_lines, surfaces.vendor_spiral_lines, surfaces.vendor_rust_lines);
    println!("own_spiral_files={} own_rust_files={} generated_rust_files={} vendor_spiral_files={} vendor_rust_files={} rust_global_site_count={} census_authority=source-stats", surfaces.own_spiral_files, surfaces.own_rust_files, surfaces.generated_rust_files, surfaces.vendor_spiral_files, surfaces.vendor_rust_files, stats.rust_global_sites);
    println!("cargo_crate_count={} vendor_cargo_crate_count={} cargo_crate_max_lines={} cargo_crate_max={} density_gate_observed={}", stats.cargo_crates, surfaces.vendor_cargo_crates, stats.crate_max_lines, stats.crate_max, if limits == 1 { "within-eoie-limit" } else { "above-eoie-limit" });
    println!("spiral_package_count={} vendor_spiral_package_count={} package_only_spiral_count={} package_classification=recursive-generic rust_max_file_lines={} rust_max_file={}", stats.spiral_packages, surfaces.vendor_spiral_packages, stats.package_only, stats.rust_max_lines, stats.rust_max_file);
    Ok(())
}

pub fn source_topology_run(args: &[String]) -> Result<(), String> {
    if args.len() != 2 && args.len() != 3 { return Err("source-topology expects root [state/authority_census.spi]".to_owned()); }
    let root = Path::new(topology_arg(args, 1, "root")?);
    let stats = topology_collect(root)?;
    let limits = eoie_source_topology_limit_binding(stats.rust_max_lines as i32, stats.crate_max_lines as i32);
    let expected_package_only = stats.spiral_packages.saturating_sub(stats.cargo_crates);
    let classified = eoie_source_topology_package_only_binding(expected_package_only as i32, stats.package_only as i32);
    if limits != 1 { return Err(format!("source topology limit exceeded: rust_file_max={} rust_file={} cargo_crate_max={} cargo_crate={} limit=1000", stats.rust_max_lines, stats.rust_max_file, stats.crate_max_lines, stats.crate_max)); }
    if classified != 1 { return Err(format!("source topology classification mismatch: cargo_crates={} spiral_packages={} package_only={}", stats.cargo_crates, stats.spiral_packages, stats.package_only)); }
    if args.len() == 3 {
        topology_write_census(root, topology_arg(args, 2, "census-relative")?, &stats)?;
        println!("census_written=true path={}", root.join(topology_arg(args, 2, "census-relative")?).display());
    }
    println!("eoie proxy source-topology ok root={}", root.display());
    println!("spiral_lines={} rust_lines={} combined_lines={} total_growth_policy=unbounded", stats.spiral_lines, stats.rust_lines, stats.spiral_lines + stats.rust_lines);
    println!("spiral_source_file_count={} rust_source_file_count={} rust_global_site_count={} census_authority=source-topology", stats.spiral_source_files, stats.rust_source_files, stats.rust_global_sites);
    println!("cargo_crate_count={} cargo_crate_count_policy=unbounded cargo_crate_max_lines={} cargo_crate_max={} cargo_crate_loc_limit=1000", stats.cargo_crates, stats.crate_max_lines, stats.crate_max);
    println!("spiral_package_count={} spiral_package_count_policy=unbounded package_only_spiral_count={} rust_max_file_lines={} rust_max_file={} rust_file_loc_limit=1000", stats.spiral_packages, stats.package_only, stats.rust_max_lines, stats.rust_max_file);
    println!("topology_limits_ok=true owner_growth_policy=report-only pruning_policy=consumer-proof");
    Ok(())
}

#[cfg(test)]
use std::sync::atomic::{AtomicU64, Ordering};
#[cfg(test)]
static TOPOLOGY_TEST_NEXT: AtomicU64 = AtomicU64::new(0);
#[cfg(test)]
fn topology_test_temporary(label: &str) -> PathBuf { std::env::temp_dir().join(format!("eoie-source-topology-{label}-{}-{}", std::process::id(), TOPOLOGY_TEST_NEXT.fetch_add(1, Ordering::Relaxed))) }
#[cfg(test)]
#[test]
fn distinguishes_cargo_crates_from_package_only_spiral() {
    let root = topology_test_temporary("counts");
    fs::create_dir_all(root.join("src/cargo")).expect("cargo");
    fs::create_dir_all(root.join("src/package-only")).expect("package-only");
    fs::write(root.join("src/cargo/Cargo.toml"), b"[package]\nname='cargo'\n").expect("cargo toml");
    fs::write(root.join("src/cargo/package.spiproj"), b"modules:\n    main\n").expect("cargo spiproj");
    fs::write(root.join("src/cargo/main.rs"), b"fn main() {}\n").expect("cargo rs");
    fs::write(root.join("src/package-only/package.spiproj"), b"modules:\n    model\n").expect("package spiproj");
    fs::write(root.join("src/package-only/model.spi"), b"inl value () : i32 = 1i32\n").expect("package spi");
    let stats = topology_collect(&root).expect("stats");
    assert_eq!(stats.cargo_crates, 1);
    assert_eq!(stats.spiral_packages, 2);
    assert_eq!(stats.package_only, 1);
    assert_eq!(stats.spiral_source_files, 1);
    assert_eq!(stats.rust_source_files, 1);
    assert_eq!(stats.rust_global_sites, 0);
    fs::remove_dir_all(root).expect("cleanup");
}

fn method0(mut v0: i32, mut v1: i32) -> i32 {
    let mut v2: bool = 1000i32 < v0;
    if v2 {
        0i32
    } else {
        let mut v3: bool = 1000i32 < v1;
        if v3 {
            0i32
        } else {
            1i32
        }
    }
}
fn method1(mut v0: i32, mut v1: i32) -> i32 {
    let mut v2: bool = v0 < 0i32;
    if v2 {
        0i32
    } else {
        let mut v3: bool = v1 < 0i32;
        if v3 {
            0i32
        } else {
            let mut v4: bool = v0 < v1;
            if v4 {
                0i32
            } else {
                let mut v5: bool = v1 < v0;
                if v5 {
                    0i32
                } else {
                    1i32
                }
            }
        }
    }
}
fn method2(mut v0: i32, mut v1: i32) -> i32 {
    let mut v2: bool = v0 < 0i32;
    if v2 {
        -1i32
    } else {
        let mut v3: bool = 1i32 < v0;
        if v3 {
            -1i32
        } else {
            let mut v4: bool = v1 < 0i32;
            if v4 {
                -1i32
            } else {
                let mut v5: bool = 1i32 < v1;
                if v5 {
                    -1i32
                } else {
                    let mut v6: bool = v0 == 1i32;
                    if v6 {
                        2i32
                    } else {
                        let mut v7: bool = v1 == 1i32;
                        if v7 {
                            1i32
                        } else {
                            0i32
                        }
                    }
                }
            }
        }
    }
}
fn closure0() -> Rc<dyn Fn(i32, i32) -> i32> {
    Rc::new(move |mut v0: i32, mut v1: i32| -> i32 {
        method0(v0, v1)
    })
}
fn closure1() -> Rc<dyn Fn(i32, i32) -> i32> {
    Rc::new(move |mut v0: i32, mut v1: i32| -> i32 {
        method1(v0, v1)
    })
}
fn closure2() -> Rc<dyn Fn(i32, i32) -> i32> {
    Rc::new(move |mut v0: i32, mut v1: i32| -> i32 {
        method2(v0, v1)
    })
}
pub fn eoie_source_topology_limit_binding(v0: i32, v1: i32) -> i32 {
    closure0()(v0, v1)
}
pub fn eoie_source_topology_package_only_binding(v0: i32, v1: i32) -> i32 {
    closure1()(v0, v1)
}
pub fn eoie_source_surface_binding(v0: i32, v1: i32) -> i32 {
    closure2()(v0, v1)
}
