// Generated by Spiral portable Rust backend.
#![allow(unused_mut, non_snake_case)]

unsafe extern "C" {
    #[link_name = "llabs"]
    fn spiral_libc_llabs(value: std::ffi::c_longlong) -> std::ffi::c_longlong;
}

#[inline]
fn spiral_abi_libc_llabs(value: i64) -> i64 {
    unsafe { spiral_libc_llabs(value) }
}

fn spiral_main() -> i32 {
    let v0: i64;
    v0 = -5000000000;
    let v1: i64;
    v1 = spiral_abi_libc_llabs(v0);
    let v2: bool;
    v2 = v1 == 5000000000;
    if v2 {
        return 0;
    } else {
        return 1;
    }
}

fn main() {
    std::process::exit(spiral_main());
}
