// Generated by the Spiral compiler (Zig backend). Build: zig build-exe main.zig -O ReleaseSafe (or -O Debug -fno-llvm: seconds)
const std = @import("std");
var spiral_threaded: std.Io.Threaded = .init_single_threaded;
var spiral_arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
var spiral_io: std.Io = undefined;
var spiral_gpa: std.mem.Allocator = undefined;
var spiral_true: bool = true;
fn spiralPrint(s: []const u8) void {
    std.Io.File.stdout().writeStreamingAll(spiral_io, s) catch {};
}
fn spiralPrintAny(x: anytype) void {
    const T = @TypeOf(x);
    if (T == []const u8) return spiralPrint(x);
    const s = switch (@typeInfo(T)) {
        .float => std.fmt.allocPrint(spiral_gpa, "{d}", .{x}),
        .bool => std.fmt.allocPrint(spiral_gpa, "{}", .{x}),
        else => std.fmt.allocPrint(spiral_gpa, "{d}", .{x}),
    } catch @panic("out of memory");
    spiralPrint(s);
}
fn spiralFail(s: []const u8) noreturn {
    std.Io.File.stderr().writeStreamingAll(spiral_io, s) catch {};
    std.Io.File.stderr().writeStreamingAll(spiral_io, "\n") catch {};
    std.process.exit(1);
}
fn spiralConv(comptime T: type, x: anytype) T {
    const S = @TypeOf(x);
    if (@typeInfo(T) == .float) {
        if (@typeInfo(S) == .float) return @floatCast(x) else return @floatFromInt(x);
    }
    if (@typeInfo(S) == .float) return @intFromFloat(x);
    const U = @Int(.unsigned, @bitSizeOf(T));
    const wide: i128 = x;
    return @bitCast(@as(U, @truncate(@as(u128, @bitCast(wide)))));
}
fn spiralConcat(a: []const u8, b: []const u8) []const u8 {
    return std.mem.concat(spiral_gpa, u8, &.{ a, b }) catch @panic("out of memory");
}
fn spiralStringSlice(s: []const u8, from: i64, upto: i64) []const u8 {
    const len: i64 = @intCast(s.len);
    if (from < 0 or from > len or upto < from - 1 or upto >= len) std.process.exit(3);
    if (upto < from) return "";
    const a: usize = @intCast(from);
    const b: usize = @intCast(upto + 1);
    if ((s[a] & 0xC0) == 0x80 or (b < s.len and (s[b] & 0xC0) == 0x80)) std.process.exit(3);
    return s[a..b];
}
fn spiralIndex(len: usize, i: anytype) usize {
    if (i < 0 or i >= len) std.process.exit(3);
    return @intCast(i);
}
fn spiralNewArray(comptime T: type, n: anytype) []T {
    const len: usize = @intCast(n);
    const a = spiral_gpa.alloc(T, len) catch @panic("out of memory");
    switch (@typeInfo(T)) {
        .int, .float, .bool => @memset(a, std.mem.zeroes(T)),
        else => if (T == []const u8) @memset(a, ""),
    }
    return a;
}
fn spiralCreate(comptime T: type, v: T) *T {
    const p = spiral_gpa.create(T) catch @panic("out of memory");
    p.* = v;
    return p;
}
const UH0 = struct { tag: i32, c1_0: i32 = undefined, c1_1: *UH0 = undefined };
fn UH0_0() *UH0 {
    return spiralCreate(UH0, UH0{ .tag = 0 });
}
fn UH0_1(a0: i32, a1: *UH0) *UH0 {
    return spiralCreate(UH0, UH0{ .tag = 1, .c1_0 = a0, .c1_1 = a1 });
}
fn method2(p0: i32) *UH0 {
    var v0: i32 = p0; _ = &v0;
    var v1: i32 = undefined; _ = &v1;
    var v2: bool = undefined; _ = &v2;
    var v3: *UH0 = undefined; _ = &v3;
    v1 = v0 -% @as(i32, 1);
    v2 = v1 == @as(i32, 0);
    if (v2) {
        v3 = UH0_0();
        return UH0_1(@as(i32, 7), v3);
    } else {
        return method1(v1);
    }
}
fn method1(p0: i32) *UH0 {
    var v0: i32 = p0; _ = &v0;
    var v1: i32 = undefined; _ = &v1;
    var v2: bool = undefined; _ = &v2;
    var v3: *UH0 = undefined; _ = &v3;
    v1 = v0 -% @as(i32, 1);
    v2 = v1 == @as(i32, 0);
    if (v2) {
        v3 = UH0_0();
        return UH0_1(@as(i32, 11), v3);
    } else {
        return method2(v1);
    }
}
fn method0() *UH0 {
    var v0: i32 = undefined; _ = &v0;
    var v1: bool = undefined; _ = &v1;
    var v2: *UH0 = undefined; _ = &v2;
    v0 = @as(i32, 1000000);
    v1 = v0 == @as(i32, 0);
    if (v1) {
        v2 = UH0_0();
        return UH0_1(@as(i32, 7), v2);
    } else {
        return method1(v0);
    }
}
fn spiralMain() i32 {
    var v0: *UH0 = undefined; _ = &v0;
    var v1: i32 = undefined; _ = &v1;
    var v2: *UH0 = undefined; _ = &v2;
    var v3: bool = undefined; _ = &v3;
    v0 = method0();
    switch (v0.tag) {
        1 => { // Box
            v1 = v0.c1_0;
            v2 = v0.c1_1;
            v3 = v1 == @as(i32, 7);
            if (v3) {
                return @as(i32, 0);
            } else {
                return @as(i32, 3);
            }
        },
        0 => { // Empty
            return @as(i32, 1);
        },
        else => unreachable,
    }
}
pub fn main() void {
    spiral_io = spiral_threaded.io();
    spiral_gpa = spiral_arena.allocator();
    var code: i32 = 0;
    const thread = std.Thread.spawn(.{ .stack_size = 1 << 30 }, spiralMainThread, .{&code}) catch @panic("cannot start the main thread");
    thread.join();
    std.process.exit(@truncate(@as(u32, @bitCast(code))));
}
fn spiralMainThread(code: *i32) void {
    code.* = spiralMain();
}
