// Generated by Spiral portable Rust backend.
#![allow(unused_mut, non_snake_case)]

#![allow(dead_code)]

use std::cell::RefCell;
use std::rc::Rc;

type Array0 = Rc<RefCell<Vec<i32>>>;
fn ArrayCreate0(len: i32, _init_at_zero: bool) -> Array0 {
    assert!(len >= 0, "negative Spiral array length");
    Rc::new(RefCell::new(vec![0; len as usize]))
}
fn DynamicArraySet0(array: &Array0, index: i32, value: i32) {
    assert!(index >= 0, "negative Spiral array index");
    let mut data = array.borrow_mut();
    let index = index as usize;
    assert!(index < data.len(), "Spiral array index out of bounds");
    data[index] = value;
}
fn DynamicArrayGet0(array: &Array0, index: i32) -> i32 {
    assert!(index >= 0, "negative Spiral array index");
    let data = array.borrow();
    let index = index as usize;
    assert!(index < data.len(), "Spiral array index out of bounds");
    data[index]
}
fn DynamicArrayLen0(array: &Array0) -> i32 {
    let len = array.borrow().len();
    assert!(len <= i32::MAX as usize, "Spiral array length exceeds i32");
    len as i32
}
fn DynamicArrayClone0(_array: &Array0) {}
fn DynamicArrayDrop0(_array: &Array0) {}

#[derive(Clone)]
struct Tuple9000 {
    v0: i32,
    v1: Rc<str>,
    v2: Array0,
}

fn TupleCreate9000(v0: i32, v1: Rc<str>, v2: Array0) -> Tuple9000 {
    Tuple9000 { v0, v1, v2 }
}

#[derive(Clone)]
struct ClosureValue1 {
    v0: Tuple9000,
}

fn ClosureValueCreate1(v0: Tuple9000) -> ClosureValue1 {
    ClosureValue1 { v0 }
}

#[derive(Clone, Copy)]
struct ClosureValue0 {
}

fn ClosureValueCreate0() -> ClosureValue0 {
    ClosureValue0 {  }
}

fn ClosureInvoke1(x: ClosureValue1, v1: i32) -> i32 {
    let v0: Tuple9000;
    v0 = x.v0.clone();
    let mut v12: i32;
    if v0.v0 == 0 {
        v12 = 3;
    } else {
        let v2: Rc<str>;
        v2 = v0.v1;
        let v3: Array0;
        v3 = v0.v2.clone();
        DynamicArrayClone0(&v3);
        let v4: i32;
        v4 = v2.len() as i32;
        let v5: i32;
        v5 = DynamicArrayLen0(&v3);
        let v6: i32;
        v6 = v4 + v5;
        let v7: i32;
        v7 = DynamicArrayGet0(&v3, 0);
        let v8: i32;
        v8 = v6 + v7;
        let v9: i32;
        v9 = DynamicArrayGet0(&v3, 1);
        drop(v3);
        let v10: i32;
        v10 = v8 + v9;
        v12 = v10;
    }
    let v13: i32;
    v13 = v12 + v1;
    return v13;
}

fn ClosureInvoke0(__x: ClosureValue0, v0: i32) -> ClosureValue1 {
    let v1: Array0;
    v1 = ArrayCreate0(2, false);
    DynamicArraySet0(&v1, 0, v0);
    let v2: i32;
    v2 = v0 + 1;
    DynamicArraySet0(&v1, 1, v2);
    let v3: bool;
    v3 = v0 == 0;
    let mut v7: Tuple9000;
    if v3 {
        v7 = TupleCreate9000(0, Rc::<str>::from(""), ArrayCreate0(0, false));
    } else {
        let v5: Rc<str>;
        v5 = Rc::<str>::from("hi");
        DynamicArrayClone0(&v1);
        v7 = TupleCreate9000(1, v5.clone(), v1.clone());
    }
    drop(v1);
    return ClosureValueCreate1(v7);
}

fn method0(v0: ClosureValue0) -> ClosureValue1 {
    return ClosureInvoke0(v0.clone(), 0);
}

fn method1(v0: ClosureValue0) -> ClosureValue1 {
    return ClosureInvoke0(v0.clone(), 4);
}

fn method4(v0: ClosureValue1) -> i32 {
    let v1: i32;
    v1 = ClosureInvoke1(v0.clone(), 2);
    let v2: i32;
    v2 = v1 + 5;
    return v2;
}

fn method3(v0: ClosureValue1) -> i32 {
    let v1: i32;
    v1 = ClosureInvoke1(v0.clone(), 1);
    let v2: i32;
    v2 = method4(v0.clone());
    let v3: i32;
    v3 = v1 + v2;
    return v3;
}

fn method2(v0: ClosureValue1, v1: ClosureValue1) -> i32 {
    let v2: i32;
    v2 = ClosureInvoke1(v0.clone(), 5);
    let v3: i32;
    v3 = method3(v1.clone());
    let v4: i32;
    v4 = v2 + v3;
    return v4;
}

fn spiral_main() -> i32 {
    let v0: ClosureValue0;
    v0 = ClosureValueCreate0();
    let v1: ClosureValue1;
    v1 = method0(v0.clone());
    let v2: ClosureValue1;
    v2 = method1(v0.clone());
    return method2(v1, v2);
}

fn main() {
    std::process::exit(spiral_main());
}
