// Generated by the Spiral compiler (TypeScript backend). Run: node --experimental-strip-types main.ts, or bun main.ts.
export function main(): number {
    let v0: number = 20;
    let v1: number = 2;
    let v2: number = Math.imul(v0, v1);
    let v3: number = (v2 + 3) | 0;
    return v3;
}
process.exitCode = main();
