// Generated by Spiral portable Rust backend.
#![allow(unused_mut, non_snake_case)]

fn spiral_main() -> i32 {
    let v0: i32;
    let v1: i32;
    let v2: i32;
    v0 = 20;
    v1 = 2;
    v2 = v0.wrapping_mul(v1).wrapping_add(3);
    return v2;
}

fn main() {
    std::process::exit(spiral_main());
}
