// Generated by Spiral portable Rust backend.
#![allow(unused_mut, non_snake_case)]

fn spiral_main() -> i32 {
    let v0: f32;
    v0 = 0.0;
    let v1: f32;
    v1 = 1.0;
    let v2: f64;
    v2 = 0.0;
    let v3: f64;
    v3 = 1.0;
    let v4: f32;
    v4 = (v1).ln();
    let v5: bool;
    v5 = v4 == v0;
    let mut v8: bool;
    if v5 {
        let v6: f64;
        v6 = (v3).ln();
        let v7: bool;
        v7 = v6 == v2;
        v8 = v7;
    } else {
        v8 = false;
    }
    let mut v11: bool;
    if v8 {
        let v9: f32;
        v9 = (v0).exp();
        let v10: bool;
        v10 = v9 == v1;
        v11 = v10;
    } else {
        v11 = false;
    }
    let mut v14: bool;
    if v11 {
        let v12: f64;
        v12 = (v2).exp();
        let v13: bool;
        v13 = v12 == v3;
        v14 = v13;
    } else {
        v14 = false;
    }
    let mut v17: bool;
    if v14 {
        let v15: f32;
        v15 = (v0).tanh();
        let v16: bool;
        v16 = v15 == v0;
        v17 = v16;
    } else {
        v17 = false;
    }
    let mut v20: bool;
    if v17 {
        let v18: f64;
        v18 = (v2).tanh();
        let v19: bool;
        v19 = v18 == v2;
        v20 = v19;
    } else {
        v20 = false;
    }
    let mut v23: bool;
    if v20 {
        let v21: f32;
        v21 = (v0).sin();
        let v22: bool;
        v22 = v21 == v0;
        v23 = v22;
    } else {
        v23 = false;
    }
    let mut v26: bool;
    if v23 {
        let v24: f64;
        v24 = (v2).sin();
        let v25: bool;
        v25 = v24 == v2;
        v26 = v25;
    } else {
        v26 = false;
    }
    let mut v29: bool;
    if v26 {
        let v27: f32;
        v27 = (v0).cos();
        let v28: bool;
        v28 = v27 == v1;
        v29 = v28;
    } else {
        v29 = false;
    }
    let mut v32: bool;
    if v29 {
        let v30: f64;
        v30 = (v2).cos();
        let v31: bool;
        v31 = v30 == v3;
        v32 = v31;
    } else {
        v32 = false;
    }
    if v32 {
        return 0;
    } else {
        return 1;
    }
}

fn main() {
    std::process::exit(spiral_main());
}
