[package]
name = "spiral-split-build"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[lib]
path = "src/layer_builder.rs"

[dependencies]
rayon.workspace = true
spiral-split-build-gap.workspace = true
spiral-split-build-checkpoint.workspace = true
