// Generated by Spiral portable Rust backend.
#![allow(unused_mut, non_snake_case)]

#[derive(Clone, Copy)]
struct Tuple0 {
    v0: i32,
    v1: i32,
}

fn TupleCreate0(v0: i32, v1: i32) -> Tuple0 {
    Tuple0 { v0, v1 }
}

fn method0(v0: i32, v1: i32) -> Tuple0 {
    return TupleCreate0(v0, v1);
}

fn method1(v0: i32, v1: i32) -> i32 {
    let v2: i32;
    v2 = v0 + v1;
    return v2;
}

fn spiral_main() -> i32 {
    let v0: i32;
    v0 = 20;
    let v1: i32;
    v1 = 22;
    let v2: i32;
    let v3: i32;
    let tmp0: Tuple0;
    tmp0 = method0(v0, v1);
    v2 = tmp0.v0;
    v3 = tmp0.v1;
    let v4: i32;
    v4 = method1(v2, v3);
    let v5: i32;
    v5 = v4 - 42;
    return v5;
}

fn main() {
    std::process::exit(spiral_main());
}
