[package]
name = "spiral-split-value-body"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[lib]
path = "src/value_body.rs"

[dependencies]
spiral-split-binding-header.workspace = true
spiral-split-capture-parameter.workspace = true
spiral-split-lift.workspace = true
spiral-split-lift-rewrite.workspace = true
spiral-split-model.workspace = true
