#![allow(unused_mut, non_snake_case, dead_code, clippy::needless_return, clippy::too_many_arguments)]
// Generated by Spiral portable Rust backend.
pub fn active_rating_receipt_check(root: &std::path::Path) -> Result<(), String> {
    let path = root.join("state/ratings.spi");
    let source = std::fs::read_to_string(&path).map_err(|error| format!("read {}: {error}", path.display()))?;
    let mut observed = 0usize;
    for line in source.lines().filter(|line| line.contains("// active_rating")) {
        let score_text = line.split(',').nth(1).map(str::trim).ok_or_else(|| format!("malformed active rating row: {line}"))?;
        let score = score_text.trim_end_matches("u32").parse::<i32>().map_err(|_| format!("invalid active rating score: {score_text}"))?;
        if rating_guard_active_rating_ceiling_binding(score, 620) != 1 { return Err(format!("active rating ceiling rejected score={score} ceiling=620 row={line}")); }
        observed += 1;
    }
    if observed != 14 { return Err(format!("active rating marker count mismatch observed={observed} expected=14")); }
    Ok(())
}



fn active_rating_ceiling_binding0(v0: i32, v1: i32) -> i32 {
    let v2: bool = v0 < 0;
    if v2 {
        0
    } else {
        let v3: bool = v1 < v0;
        if v3 {
            0
        } else {
            1
        }
    }
}

#[must_use]
pub fn rating_guard_active_rating_ceiling_binding(first: i32, second: i32) -> i32 {
    active_rating_ceiling_binding0(first, second)
}
