// Generated by Spiral portable Rust backend.
#![allow(unused_mut, non_snake_case)]

#![allow(dead_code)]

use std::rc::Rc;

type Recursive0 = Rc<Recursive0Node>;
#[derive(Clone)]
enum Recursive0Node {
    Case0,
    Case1 { v0: i32, v1: Recursive0 },
}

fn RecursiveCreate0_0() -> Recursive0 {
    Rc::new(Recursive0Node::Case0)
}
fn RecursiveCreate0_1(v0: i32, v1: Recursive0) -> Recursive0 {
    Rc::new(Recursive0Node::Case1 { v0, v1 })
}
fn RecursiveTag0(value: &Recursive0) -> i32 {
    match value.as_ref() {
        Recursive0Node::Case0 => 0,
        Recursive0Node::Case1 { .. } => 1,
    }
}
fn RecursiveField0_0(value: &Recursive0) -> i32 {
    match value.as_ref() {
        Recursive0Node::Case1 { v0, .. } => *v0,
        _ => panic!("recursive union field 0 requested from wrong case"),
    }
}
fn RecursiveField0_1(value: &Recursive0) -> Recursive0 {
    match value.as_ref() {
        Recursive0Node::Case1 { v1, .. } => v1.clone(),
        _ => panic!("recursive union field 1 requested from wrong case"),
    }
}
fn RecursiveClone0(_value: &Recursive0) {}
fn RecursiveDrop0(_value: &Recursive0) {}

fn sum0(v0: Recursive0) -> i32 {
    if RecursiveTag0(&v0) == 1 {
        let v1: i32;
        v1 = RecursiveField0_0(&v0);
        let v2: Recursive0;
        v2 = RecursiveField0_1(&v0);
        RecursiveClone0(&v2);
        RecursiveClone0(&v2);
        RecursiveDrop0(&v0);
        let v3: i32;
        v3 = sum0(v2.clone());
        drop(v2);
        let v4: i32;
        v4 = v1 + v3;
        return v4;
    } else {
        drop(v0);
        return 0;
    }
}

fn spiral_main() -> i32 {
    let v0: i32;
    v0 = 1;
    let v1: i32;
    v1 = 2;
    let v2: i32;
    v2 = 3;
    let v3: Recursive0;
    v3 = RecursiveCreate0_0();
    RecursiveClone0(&v3);
    let v4: Recursive0;
    v4 = RecursiveCreate0_1(v2.clone(), v3.clone());
    RecursiveClone0(&v4);
    drop(v3);
    let v5: Recursive0;
    v5 = RecursiveCreate0_1(v1, v4.clone());
    RecursiveClone0(&v5);
    drop(v4);
    let v6: Recursive0;
    v6 = RecursiveCreate0_1(v0.clone(), v5.clone());
    RecursiveClone0(&v6);
    drop(v5);
    let v7: i32;
    v7 = sum0(v6.clone());
    drop(v6);
    let v8: i32;
    v8 = v7 - 6;
    return v8;
}

fn main() {
    std::process::exit(spiral_main());
}
