// Generated by Spiral portable Rust backend.
#![allow(unused_mut, non_snake_case, dead_code, unused_variables, unused_assignments)]

#[derive(Clone, Copy)]
struct Tuple9000 {
    v0: i32,
    v1: i32,
}

fn TupleCreate9000(v0: i32, v1: i32) -> Tuple9000 {
    Tuple9000 { v0, v1 }
}

fn score0(v0: Tuple9000) -> i32 {
    if v0.v0 == 0 {
        let v1: i32 = v0.v1;
        return v1;
    } else {
        let v2: i32 = v0.v1;
        let v3: i32 = 0 - v2;
        return v3;
    }
}

fn spiral_main() -> i32 {
    let v0: bool = true;
    let mut v3: Tuple9000;
    if v0 {
        v3 = TupleCreate9000(0, 7);
    } else {
        v3 = TupleCreate9000(1, 3);
    }
    let v4: i32 = score0(v3);
    let v5: i32 = v4 - 7;
    return v5;
}

fn main() {
    std::process::exit(spiral_main());
}


