[package]
name = "eoie-fs-actions"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
name = "eoie_fs_actions"
path = "fs_actions.rs"

[dependencies]
canonical-plan-ir-domain = { path = "../canonical_plan_ir_domain" }
eoie-rust-std-fs = { path = "../rust_std_fs" }
eoie-patch-control-domain = { path = "../patch_control_domain" }
eoie-patch-driver-domain = { path = "../patch_driver_domain" }
eoie-proxy-search = { path = "../eoie_proxy_search" }
eoie-process = { path = "../eoie_process" }

[lints.clippy]
needless_return = "allow"
needless_late_init = "allow"
