// Generated by Spiral portable Rust backend.
#![allow(unused_mut, non_snake_case)]

fn method0(v0: &'static str) -> bool {
    let v1: bool;
    v1 = v0 == v0;
    return v1;
}

fn spiral_main() -> i32 {
    let v0: &'static str;
    v0 = "spiral";
    let v1: bool;
    v1 = method0(v0);
    if v1 {
        return 0;
    } else {
        return 1;
    }
}

fn main() {
    std::process::exit(spiral_main());
}
