// Generated by Spiral portable Rust backend.
#![allow(unused_mut, non_snake_case)]

#![allow(dead_code)]

use std::cell::RefCell;
use std::rc::Rc;

type Array0 = Rc<RefCell<Vec<i32>>>;
fn ArrayCreate0(len: i32, _init_at_zero: bool) -> Array0 {
    assert!(len >= 0, "negative Spiral array length");
    Rc::new(RefCell::new(vec![0; len as usize]))
}
fn DynamicArraySet0(array: &Array0, index: i32, value: i32) {
    assert!(index >= 0, "negative Spiral array index");
    let mut data = array.borrow_mut();
    let index = index as usize;
    assert!(index < data.len(), "Spiral array index out of bounds");
    data[index] = value;
}
fn DynamicArrayGet0(array: &Array0, index: i32) -> i32 {
    assert!(index >= 0, "negative Spiral array index");
    let data = array.borrow();
    let index = index as usize;
    assert!(index < data.len(), "Spiral array index out of bounds");
    data[index]
}
fn DynamicArrayLen0(array: &Array0) -> i32 {
    let len = array.borrow().len();
    assert!(len <= i32::MAX as usize, "Spiral array length exceeds i32");
    len as i32
}
fn DynamicArrayClone0(_array: &Array0) {}
fn DynamicArrayDrop0(_array: &Array0) {}

#[derive(Clone)]
struct Tuple9000 {
    v0: i32,
    v1: Array0,
}

fn TupleCreate9000(v0: i32, v1: Array0) -> Tuple9000 {
    Tuple9000 { v0, v1 }
}

#[derive(Clone, Copy)]
struct ClosureValue0 {
}

fn ClosureValueCreate0() -> ClosureValue0 {
    ClosureValue0 {  }
}

fn ClosureInvoke0(__x: ClosureValue0, v0: i32) -> Tuple9000 {
    let v1: bool;
    v1 = v0 == 0;
    if v1 {
        return TupleCreate9000(0, ArrayCreate0(0, false));
    } else {
        let v3: Array0;
        v3 = ArrayCreate0(2, false);
        DynamicArraySet0(&v3, 0, v0);
        let v4: i32;
        v4 = v0 + 1;
        DynamicArraySet0(&v3, 1, v4);
        return TupleCreate9000(1, v3);
    }
}

fn method0(v0: ClosureValue0) -> Tuple9000 {
    return ClosureInvoke0(v0.clone(), 0);
}

fn score1(v0: Tuple9000) -> i32 {
    if v0.v0 == 0 {
        drop(v0);
        return 3;
    } else {
        let v1: Array0;
        v1 = v0.v1.clone();
        DynamicArrayClone0(&v1);
        drop(v0);
        let v2: i32;
        v2 = DynamicArrayLen0(&v1);
        let v3: i32;
        v3 = DynamicArrayGet0(&v1, 0);
        let v4: i32;
        v4 = v2 + v3;
        let v5: i32;
        v5 = DynamicArrayGet0(&v1, 1);
        drop(v1);
        let v6: i32;
        v6 = v4 + v5;
        return v6;
    }
}

fn method2(v0: ClosureValue0) -> Tuple9000 {
    return ClosureInvoke0(v0.clone(), 4);
}

fn spiral_main() -> i32 {
    let v0: ClosureValue0;
    v0 = ClosureValueCreate0();
    let v1: Tuple9000;
    v1 = method0(v0.clone());
    if v1.v0 == 1 {
        DynamicArrayClone0(&v1.v1);
    }
    let v2: i32;
    v2 = score1(v1.clone());
    drop(v1);
    let v3: Tuple9000;
    v3 = method2(v0.clone());
    if v3.v0 == 1 {
        DynamicArrayClone0(&v3.v1);
    }
    let v4: i32;
    v4 = score1(v3.clone());
    drop(v3);
    let v5: i32;
    v5 = v2 + v4;
    let v6: i32;
    v6 = v5 + 28;
    return v6;
}

fn main() {
    std::process::exit(spiral_main());
}
