// Generated by Spiral portable Rust backend.
#![allow(unused_mut, non_snake_case)]

#![allow(dead_code)]

use std::cell::RefCell;
use std::rc::Rc;

type Array0 = Rc<RefCell<Vec<i32>>>;
fn ArrayCreate0(len: i32, _init_at_zero: bool) -> Array0 {
    assert!(len >= 0, "negative Spiral array length");
    Rc::new(RefCell::new(vec![0; len as usize]))
}
fn DynamicArraySet0(array: &Array0, index: i32, value: i32) {
    assert!(index >= 0, "negative Spiral array index");
    let mut data = array.borrow_mut();
    let index = index as usize;
    assert!(index < data.len(), "Spiral array index out of bounds");
    data[index] = value;
}
fn DynamicArrayGet0(array: &Array0, index: i32) -> i32 {
    assert!(index >= 0, "negative Spiral array index");
    let data = array.borrow();
    let index = index as usize;
    assert!(index < data.len(), "Spiral array index out of bounds");
    data[index]
}
fn DynamicArrayLen0(array: &Array0) -> i32 {
    let len = array.borrow().len();
    assert!(len <= i32::MAX as usize, "Spiral array length exceeds i32");
    len as i32
}
fn DynamicArrayReserve0(array: &Array0, capacity: i32) {
    assert!(capacity >= 0, "negative Spiral array capacity");
    let mut data = array.borrow_mut();
    let requested = capacity as usize;
    let current = data.capacity();
    if requested > current {
        let mut target = current.max(1);
        while target < requested {
            match target.checked_mul(2) {
                Some(next) => target = next,
                None => { target = requested; break; }
            }
        }
        let additional = target.saturating_sub(data.len());
        data.reserve_exact(additional);
    }
}
fn DynamicArrayClone0(_array: &Array0) {}
fn DynamicArrayDrop0(_array: &Array0) {}

fn method0(v0: Array0) -> () {
    let v1: i32;
    v1 = 4;
    DynamicArrayReserve0(&v0, v1);
    drop(v0);
    return;
}

fn __spiral_scc_method4_method3_method2(mut __spiral_tail_state: i32, mut v0: i32, mut v1: Array0) -> i32 {
    loop {
        if __spiral_tail_state == 0 {
            let mut v2: i32;
            v2 = v0 - 1;
            let mut v3: bool;
            v3 = v2 == 0;
            if v3 {
                let mut v4: bool;
                v4 = 7 == 7;
                if v4 {
                    let mut v5: i32;
                    v5 = DynamicArrayGet0(&v1, 0);
                    DynamicArrayDrop0(&v1);
                    return v5;
                } else {
                    DynamicArrayDrop0(&v1);
                    return 99;
                }
            } else {
                let mut __spiral_scc_arg0: i32;
                __spiral_scc_arg0 = v2;
                let mut __spiral_scc_arg1: Array0;
                __spiral_scc_arg1 = v1.clone();
                v0 = __spiral_scc_arg0;
                DynamicArrayClone0(&__spiral_scc_arg1);
                DynamicArrayDrop0(&v1);
                v1 = __spiral_scc_arg1;
                __spiral_tail_state = 2;
                continue;
            }
        } else {
            if __spiral_tail_state == 1 {
                let mut v2: i32;
                v2 = v0 - 1;
                let mut v3: bool;
                v3 = v2 == 0;
                if v3 {
                    let mut v4: bool;
                    v4 = 13 == 7;
                    if v4 {
                        let mut v5: i32;
                        v5 = DynamicArrayGet0(&v1, 0);
                        DynamicArrayDrop0(&v1);
                        return v5;
                    } else {
                        DynamicArrayDrop0(&v1);
                        return 99;
                    }
                } else {
                    let mut __spiral_scc_arg0: i32;
                    __spiral_scc_arg0 = v2;
                    let mut __spiral_scc_arg1: Array0;
                    __spiral_scc_arg1 = v1.clone();
                    v0 = __spiral_scc_arg0;
                    DynamicArrayClone0(&__spiral_scc_arg1);
                    DynamicArrayDrop0(&v1);
                    v1 = __spiral_scc_arg1;
                    __spiral_tail_state = 0;
                    continue;
                }
            } else {
                let mut v2: i32;
                v2 = v0 - 1;
                let mut v3: bool;
                v3 = v2 == 0;
                if v3 {
                    let mut v4: bool;
                    v4 = 11 == 7;
                    if v4 {
                        let mut v5: i32;
                        v5 = DynamicArrayGet0(&v1, 0);
                        DynamicArrayDrop0(&v1);
                        return v5;
                    } else {
                        DynamicArrayDrop0(&v1);
                        return 99;
                    }
                } else {
                    let mut __spiral_scc_arg0: i32;
                    __spiral_scc_arg0 = v2;
                    let mut __spiral_scc_arg1: Array0;
                    __spiral_scc_arg1 = v1.clone();
                    v0 = __spiral_scc_arg0;
                    DynamicArrayClone0(&__spiral_scc_arg1);
                    DynamicArrayDrop0(&v1);
                    v1 = __spiral_scc_arg1;
                    __spiral_tail_state = 1;
                    continue;
                }
            }
        }
    }
}

fn method4(v0: i32, v1: Array0) -> i32 {
    return __spiral_scc_method4_method3_method2(0, v0, v1);
}

fn method3(v0: i32, v1: Array0) -> i32 {
    return __spiral_scc_method4_method3_method2(1, v0, v1);
}

fn method2(v0: i32, v1: Array0) -> i32 {
    return __spiral_scc_method4_method3_method2(2, v0, v1);
}

fn method1(v0: Array0) -> i32 {
    let v1: i32;
    v1 = 1000002;
    let v2: bool;
    v2 = v1 == 0;
    if v2 {
        let v3: bool;
        v3 = 7 == 7;
        if v3 {
            let v4: i32;
            v4 = DynamicArrayGet0(&v0, 0);
            DynamicArrayDrop0(&v0);
            return v4;
        } else {
            DynamicArrayDrop0(&v0);
            return 99;
        }
    } else {
        return method2(v1, v0);
    }
}

fn spiral_main() -> i32 {
    let v0: i32;
    v0 = 1;
    let v1: Array0;
    v1 = ArrayCreate0(v0, false);
    DynamicArraySet0(&v1, 0, 7);
    DynamicArrayClone0(&v1);
    method0(v1.clone());
    DynamicArrayClone0(&v1);
    let v2: i32;
    v2 = method1(v1.clone());
    DynamicArraySet0(&v1, 0, 17);
    let v3: bool;
    v3 = v2 == 7;
    if v3 {
        let v4: i32;
        v4 = DynamicArrayGet0(&v1, 0);
        DynamicArrayDrop0(&v1);
        let v5: bool;
        v5 = v4 == 17;
        if v5 {
            return 0;
        } else {
            return 2;
        }
    } else {
        drop(v1);
        return 1;
    }
}

fn main() {
    std::process::exit(spiral_main());
}
