#![allow(unused_mut, non_snake_case, dead_code, clippy::needless_return, clippy::too_many_arguments)]
// Generated by Spiral portable Rust backend.
#[cfg(windows)] mod windows;
#[cfg(windows)] pub use windows::WindowsJob;
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum ProcessTermination {
    Exited(i32),
    Signaled(i32),
    TimedOut,
    Unknown,
}

#[derive(Debug)]
pub struct ProcessCapture {
    pub status: std::process::ExitStatus,
    pub termination: ProcessTermination,
    pub stdout: Vec<u8>,
    pub stderr: Vec<u8>,
}

fn classify_process_termination(status: &std::process::ExitStatus) -> ProcessTermination {
    if let Some(code) = status.code() { return ProcessTermination::Exited(code); }
    #[cfg(unix)] { use std::os::unix::process::ExitStatusExt as _; if let Some(signal) = status.signal() { return ProcessTermination::Signaled(signal); } }
    ProcessTermination::Unknown
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ProcessStreamKind {
    Stdout,
    Stderr,
}

fn process_output_max_bytes() -> Result<usize, String> {
    let (policy_code, requested) = match std::env::var("EOIE_PROCESS_OUTPUT_MAX_BYTES").ok().as_deref() { Some(text) => (2, text.parse::<i32>().map_err(|_| "EOIE_PROCESS_OUTPUT_MAX_BYTES must be an integer".to_owned())?), None => (1, 0) };
    let resolved = eoie_process_streaming_policy_binding(policy_code, requested);
    if resolved < 1 { return Err(format!("EOIE_PROCESS_OUTPUT_MAX_BYTES rejected by Spiral policy: {requested}")); }
    usize::try_from(resolved).map_err(|_| "resolved process output limit does not fit usize".to_owned())
}

fn spawn_process_chunk_reader<T>(
    mut stream: T,
    kind: ProcessStreamKind,
    sender: std::sync::mpsc::Sender<(ProcessStreamKind, Vec<u8>)>,
) -> std::thread::JoinHandle<Result<(), String>>
where
    T: std::io::Read + Send + 'static,
{
    std::thread::spawn(move || {
        let mut buffer = [0u8; 8192];
        loop {
            let count = stream
                .read(&mut buffer)
                .map_err(|error| format!("read process stream: {error}"))?;
            if count == 0 {
                break;
            }
            sender
                .send((kind, buffer[..count].to_vec()))
                .map_err(|_| "process stream receiver was dropped".to_owned())?;
        }
        Ok(())
    })
}

fn spawn_process_input_writer(
    mut stdin: std::process::ChildStdin,
    bytes: Vec<u8>,
) -> std::thread::JoinHandle<Result<(), String>> {
    std::thread::spawn(move || {
        match std::io::Write::write_all(&mut stdin, &bytes) {
            Err(error) if error.kind() != std::io::ErrorKind::BrokenPipe => {
                return Err(format!("write process stdin: {error}"));
            }
            _ => {}
        }
        std::io::Write::flush(&mut stdin)
            .or_else(|error| {
                if error.kind() == std::io::ErrorKind::BrokenPipe {
                    Ok(())
                } else {
                    Err(error)
                }
            })
            .map_err(|error| format!("flush process stdin: {error}"))
    })
}

fn join_process_chunk_reader(reader: std::thread::JoinHandle<Result<(), String>>, stream: &str) -> Result<(), String> {
    reader.join().map_err(|_| format!("{stream} chunk reader panicked"))?
}

fn join_process_input_writer(writer: std::thread::JoinHandle<Result<(), String>>) -> Result<(), String> {
    writer.join().map_err(|_| "stdin writer panicked".to_owned())?
}

fn append_process_chunk<F>(
    kind: ProcessStreamKind,
    bytes: Vec<u8>,
    stdout: &mut Vec<u8>,
    stderr: &mut Vec<u8>,
    limit: usize,
    on_chunk: &mut F,
) -> Result<(), String>
where
    F: FnMut(ProcessStreamKind, &[u8]) -> Result<(), String>,
{
    let current = match kind {
        ProcessStreamKind::Stdout => stdout.len(),
        ProcessStreamKind::Stderr => stderr.len(),
    };
    let projected = current.checked_add(bytes.len()).ok_or_else(|| "process output size overflow".to_owned())?;
    if projected > limit {
        return Err(format!("process output limit exceeded stream={kind:?} projected={projected} limit={limit}"));
    }
    on_chunk(kind, &bytes)?;
    match kind {
        ProcessStreamKind::Stdout => stdout.extend_from_slice(&bytes),
        ProcessStreamKind::Stderr => stderr.extend_from_slice(&bytes),
    }
    Ok(())
}

fn drain_process_chunks<F>(
    receiver: &std::sync::mpsc::Receiver<(ProcessStreamKind, Vec<u8>)>,
    stdout: &mut Vec<u8>,
    stderr: &mut Vec<u8>,
    limit: usize,
    on_chunk: &mut F,
) -> Result<(), String>
where
    F: FnMut(ProcessStreamKind, &[u8]) -> Result<(), String>,
{
    while let Ok((kind, bytes)) = receiver.try_recv() {
        append_process_chunk(kind, bytes, stdout, stderr, limit, on_chunk)?;
    }
    Ok(())
}

#[cfg(unix)]
unsafe extern "C" {
    fn kill(pid: i32, signal: i32) -> i32;
}

#[cfg(unix)]
fn signal_process_tree(pid: i32, signal: i32) -> Result<(), String> {
    let group = unsafe { kill(-pid, signal) }; let direct = unsafe { kill(pid, signal) };
    if group != 0 && direct != 0 { let error = std::io::Error::last_os_error(); if error.raw_os_error() != Some(3) { return Err(format!("signal process tree {pid}: {error}")); } }
    Ok(())
}

fn terminate_bounded_process(child: &mut std::process::Child) -> Result<std::process::ExitStatus, String> {
    #[cfg(unix)]
    {
        let pid = i32::try_from(child.id()).map_err(|_| "process id does not fit i32".to_owned())?;
        signal_process_tree(pid, 9)?;
    }
    #[cfg(not(unix))]
    {
        child.kill().map_err(|error| format!("kill process: {error}"))?;
    }
    child.wait().map_err(|error| format!("reap process: {error}"))
}

pub fn bounded_process_tree_capability() -> &'static str {
    #[cfg(unix)] { return "process-group-tree-signal"; }
    #[cfg(windows)] { return "windows-job-object-tree"; }
    #[cfg(not(any(unix, windows)))] { "direct-child-only" }
}

pub fn run_bounded_streaming<F>(
    command: &mut std::process::Command,
    timeout_ms: u64,
    input: Option<&[u8]>,
    mut on_chunk: F,
) -> Result<ProcessCapture, String>
where
    F: FnMut(ProcessStreamKind, &[u8]) -> Result<(), String>,
{
    if eoie_process_streaming_policy_binding(0, i32::from(timeout_ms > 0)) != 1 {
        return Err("timeout must be positive".to_owned());
    }
    let unix_flag = {
        #[cfg(any(unix, windows))] { 1i32 }
        #[cfg(not(any(unix, windows)))] { 0i32 }
    };
    if eoie_process_streaming_policy_binding(0, unix_flag) != 1 {
        return Err(format!("bounded process tree supervision unavailable: {}", bounded_process_tree_capability()));
    }
    let output_limit = process_output_max_bytes()?;
    #[cfg(unix)]
    {
        use std::os::unix::process::CommandExt;
        command.process_group(0);
    }
    command
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped());
    if input.is_some() {
        command.stdin(std::process::Stdio::piped());
    } else {
        command.stdin(std::process::Stdio::null());
    }
    #[cfg(windows)] let (mut child, windows_job) = WindowsJob::spawn(command)?;
    #[cfg(not(windows))] let mut child = command.spawn().map_err(|error| format!("spawn process: {error}"))?;
    let stdout = child
        .stdout
        .take()
        .ok_or_else(|| "process stdout was not piped".to_owned())?;
    let stderr = child
        .stderr
        .take()
        .ok_or_else(|| "process stderr was not piped".to_owned())?;
    let (sender, receiver) = std::sync::mpsc::channel();
    let stdout_reader = spawn_process_chunk_reader(stdout, ProcessStreamKind::Stdout, sender.clone());
    let stderr_reader = spawn_process_chunk_reader(stderr, ProcessStreamKind::Stderr, sender.clone());
    drop(sender);
    let stdin_writer = input
        .map(|bytes| {
            let stdin = child
                .stdin
                .take()
                .ok_or_else(|| "process stdin was not piped".to_owned())?;
            Ok::<_, String>(spawn_process_input_writer(stdin, bytes.to_vec()))
        })
        .transpose()?;
    let deadline = std::time::Instant::now() + std::time::Duration::from_millis(timeout_ms);
    let mut stdout_bytes = Vec::new();
    let mut stderr_bytes = Vec::new();
    let (status, timed_out) = loop {
        if let Err(error) = drain_process_chunks(
            &receiver,
            &mut stdout_bytes,
            &mut stderr_bytes,
            output_limit,
            &mut on_chunk,
        ) {
            #[cfg(windows)] windows_job.terminate();
            let _ = terminate_bounded_process(&mut child);
            return Err(error);
        }
        if let Some(status) = child
            .try_wait()
            .map_err(|error| format!("wait process: {error}"))?
        {
            break (status, false);
        }
        if std::time::Instant::now() >= deadline {
            #[cfg(windows)] windows_job.terminate();
            let status = terminate_bounded_process(&mut child)?;
            break (status, true);
        }
        match receiver.recv_timeout(std::time::Duration::from_millis(10)) {
            Ok((kind, bytes)) => {
                if let Err(error) = append_process_chunk(
                    kind,
                    bytes,
                    &mut stdout_bytes,
                    &mut stderr_bytes,
                    output_limit,
                    &mut on_chunk,
                ) {
                    #[cfg(windows)] windows_job.terminate();
            let _ = terminate_bounded_process(&mut child);
                    return Err(error);
                }
            }
            Err(std::sync::mpsc::RecvTimeoutError::Timeout) => {}
            Err(std::sync::mpsc::RecvTimeoutError::Disconnected) => {
                std::thread::sleep(std::time::Duration::from_millis(1));
            }
        }
    };
    // Close descendant pipe handles even when the immediate child exited first.
    #[cfg(windows)] windows_job.terminate();
    if let Some(writer) = stdin_writer {
        join_process_input_writer(writer)?;
    }
    join_process_chunk_reader(stdout_reader, "stdout")?;
    join_process_chunk_reader(stderr_reader, "stderr")?;
    drain_process_chunks(
        &receiver,
        &mut stdout_bytes,
        &mut stderr_bytes,
        output_limit,
        &mut on_chunk,
    )?;
    let termination = if timed_out {
        ProcessTermination::TimedOut
    } else {
        classify_process_termination(&status)
    };
    Ok(ProcessCapture {
        status,
        termination,
        stdout: stdout_bytes,
        stderr: stderr_bytes,
    })
}

pub fn run_bounded_capture_with_input(
    command: &mut std::process::Command,
    timeout_ms: u64,
    input: Option<&[u8]>,
) -> Result<ProcessCapture, String> {
    run_bounded_streaming(command, timeout_ms, input, |_, _| Ok(()))
}



fn streaming_policy_export0(v0: i32, v1: i32) -> i32 {
    let v2: bool = v0 == 0;
    if v2 {
        v1
    } else {
        let v3: bool = v0 == 1;
        if v3 {
            16777216
        } else {
            let v4: bool = v0 == 2;
            if v4 {
                let v5: bool = v1 < 1;
                if v5 {
                    -1
                } else {
                    let v6: bool = 67108864 < v1;
                    if v6 {
                        -1
                    } else {
                        v1
                    }
                }
            } else {
                -1
            }
        }
    }
}

#[must_use]
pub fn eoie_process_streaming_policy_binding(first: i32, second: i32) -> i32 {
    streaming_policy_export0(first, second)
}
