#![allow(unused_mut, non_snake_case, dead_code, clippy::needless_return, clippy::too_many_arguments)]
// Generated by Spiral portable Rust backend.

fn toolchain_argument_count_binding0(v0: i32, v1: i32) -> i32 {
    let v2: bool = v0 < 0;
    if v2 {
        -1
    } else {
        let v3: bool = 7 < v0;
        if v3 {
            -1
        } else {
            let v4: bool = v1 < 0;
            if v4 {
                -1
            } else {
                let v5: bool = 0 < v1;
                if v5 {
                    -1
                } else {
                    let v6: bool = v0 == 0;
                    if v6 {
                        2
                    } else {
                        let v7: bool = v0 == 1;
                        if v7 {
                            3
                        } else {
                            let v8: bool = v0 == 2;
                            if v8 {
                                4
                            } else {
                                let v9: bool = v0 == 3;
                                if v9 {
                                    3
                                } else {
                                    let v10: bool = v0 == 4;
                                    if v10 {
                                        6
                                    } else {
                                        let v11: bool = v0 == 5;
                                        if v11 {
                                            4
                                        } else {
                                            1
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

fn toolchain_argument_token_low_binding1(v0: i32, v1: i32) -> i32 {
    let v2: bool = v0 < 0;
    if v2 {
        -1
    } else {
        let v3: bool = 3 < v0;
        if v3 {
            -1
        } else {
            let v4: bool = v1 < 0;
            if v4 {
                -1
            } else {
                let v5: bool = v0 == 0;
                if v5 {
                    let v6: bool = v1 == 0;
                    if v6 {
                        0
                    } else {
                        let v7: bool = v1 == 1;
                        if v7 {
                            1
                        } else {
                            -1
                        }
                    }
                } else {
                    let v10: bool = v0 == 1;
                    if v10 {
                        let v11: bool = v1 == 0;
                        if v11 {
                            2
                        } else {
                            let v12: bool = v1 == 1;
                            if v12 {
                                3
                            } else {
                                let v13: bool = v1 == 2;
                                if v13 {
                                    4
                                } else {
                                    -1
                                }
                            }
                        }
                    } else {
                        let v17: bool = v0 == 2;
                        if v17 {
                            let v18: bool = v1 == 0;
                            if v18 {
                                5
                            } else {
                                let v19: bool = v1 == 1;
                                if v19 {
                                    6
                                } else {
                                    let v20: bool = v1 == 2;
                                    if v20 {
                                        1
                                    } else {
                                        let v21: bool = v1 == 3;
                                        if v21 {
                                            7
                                        } else {
                                            -1
                                        }
                                    }
                                }
                            }
                        } else {
                            let v26: bool = v1 == 0;
                            if v26 {
                                8
                            } else {
                                let v27: bool = v1 == 1;
                                if v27 {
                                    1
                                } else {
                                    let v28: bool = v1 == 2;
                                    if v28 {
                                        7
                                    } else {
                                        -1
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

fn toolchain_argument_token_chunk_binding2(v0: i32, v1: i32) -> i32 {
    let v2: bool = v0 < 0;
    if v2 {
        -1
    } else {
        let v3: bool = 13 < v0;
        if v3 {
            -1
        } else {
            let v4: bool = v1 < 0;
            if v4 {
                -1
            } else {
                let v5: bool = 2 < v1;
                if v5 {
                    -1
                } else {
                    let v6: bool = v0 == 0;
                    if v6 {
                        let v7: bool = v1 == 0;
                        if v7 {
                            17970310
                        } else {
                            let v8: bool = v1 == 1;
                            if v8 {
                                82176147
                            } else {
                                1044750506
                            }
                        }
                    } else {
                        let v11: bool = v0 == 1;
                        if v11 {
                            let v12: bool = v1 == 0;
                            if v12 {
                                374520666
                            } else {
                                let v13: bool = v1 == 1;
                                if v13 {
                                    1073713576
                                } else {
                                    1073741823
                                }
                            }
                        } else {
                            let v16: bool = v0 == 2;
                            if v16 {
                                let v17: bool = v1 == 0;
                                if v17 {
                                    1052083034
                                } else {
                                    1073741823
                                }
                            } else {
                                let v19: bool = v0 == 3;
                                if v19 {
                                    let v20: bool = v1 == 0;
                                    if v20 {
                                        1073741658
                                    } else {
                                        1073741823
                                    }
                                } else {
                                    let v22: bool = v0 == 4;
                                    if v22 {
                                        let v23: bool = v1 == 0;
                                        if v23 {
                                            71535450
                                        } else {
                                            let v24: bool = v1 == 1;
                                            if v24 {
                                                1073741802
                                            } else {
                                                1073741823
                                            }
                                        }
                                    } else {
                                        let v27: bool = v0 == 5;
                                        if v27 {
                                            let v28: bool = v1 == 0;
                                            if v28 {
                                                1050743010
                                            } else {
                                                1073741823
                                            }
                                        } else {
                                            let v30: bool = v0 == 6;
                                            if v30 {
                                                let v31: bool = v1 == 0;
                                                if v31 {
                                                    884310874
                                                } else {
                                                    let v32: bool = v1 == 1;
                                                    if v32 {
                                                        641942547
                                                    } else {
                                                        1073741810
                                                    }
                                                }
                                            } else {
                                                let v35: bool = v0 == 7;
                                                if v35 {
                                                    let v36: bool = v1 == 0;
                                                    if v36 {
                                                        338112346
                                                    } else {
                                                        let v37: bool = v1 == 1;
                                                        if v37 {
                                                            1073740900
                                                        } else {
                                                            1073741823
                                                        }
                                                    }
                                                } else {
                                                    let v40: bool = v0 == 8;
                                                    if v40 {
                                                        let v41: bool = v1 == 0;
                                                        if v41 {
                                                            1073334419
                                                        } else {
                                                            1073741823
                                                        }
                                                    } else {
                                                        let v43: bool = v0 == 9;
                                                        if v43 {
                                                            let v44: bool = v1 == 0;
                                                            if v44 {
                                                                1073741690
                                                            } else {
                                                                1073741823
                                                            }
                                                        } else {
                                                            let v46: bool = v0 == 10;
                                                            if v46 {
                                                                let v47: bool = v1 == 0;
                                                                if v47 {
                                                                    445039638
                                                                } else {
                                                                    let v48: bool = v1 == 1;
                                                                    if v48 {
                                                                        1073741382
                                                                    } else {
                                                                        1073741823
                                                                    }
                                                                }
                                                            } else {
                                                                let v51: bool = v0 == 11;
                                                                if v51 {
                                                                    let v52: bool = v1 == 0;
                                                                    if v52 {
                                                                        1043702401
                                                                    } else {
                                                                        1073741823
                                                                    }
                                                                } else {
                                                                    let v54: bool = v0 == 12;
                                                                    if v54 {
                                                                        let v55: bool = v1 == 0;
                                                                        if v55 {
                                                                            621959002
                                                                        } else {
                                                                            let v56: bool = v1 == 1;
                                                                            if v56 {
                                                                                1073722824
                                                                            } else {
                                                                                1073741823
                                                                            }
                                                                        }
                                                                    } else {
                                                                        let v59: bool = v1 == 0;
                                                                        if v59 {
                                                                            145901402
                                                                        } else {
                                                                            let v60: bool = v1 == 1;
                                                                            if v60 {
                                                                                1020480
                                                                            } else {
                                                                                1073741823
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

#[must_use]
pub fn eoie_toolchain_argument_count(first: i32, second: i32) -> i32 {
    toolchain_argument_count_binding0(first, second)
}

#[must_use]
pub fn eoie_toolchain_argument_token_low(first: i32, second: i32) -> i32 {
    toolchain_argument_token_low_binding1(first, second)
}

#[must_use]
pub fn eoie_toolchain_argument_token_chunk(first: i32, second: i32) -> i32 {
    toolchain_argument_token_chunk_binding2(first, second)
}
