// Generated by the Spiral compiler (TypeScript backend). Run: node --experimental-strip-types main.ts, or bun main.ts.
export function main(): number {
    let v0: number = 250;
    let v1: number = 10;
    let v2: number = 4294967295;
    let v3: bigint = 18446744073709551615n;
    let v4: number = 127;
    let v5: number = 1;
    let v6: number = 7;
    let v7: number = 2;
    let v8: bigint = 9223372036854775807n;
    let v9: number = (-v6) | 0;
    let v10: bigint = BigInt.asIntN(64, -v8);
    let v11: number = (v0 + v1) & 0xff;
    let v12: boolean = v11 === 4;
    if (v12) {
        let v13: number = (v2 + 1) >>> 0;
        let v14: boolean = v13 === 0;
        if (v14) {
            let v15: number = Math.imul(v2, v2) >>> 0;
            let v16: boolean = v15 === 1;
            if (v16) {
                let v17: bigint = BigInt.asUintN(64, v3 + 1n);
                let v18: boolean = v17 === 0n;
                if (v18) {
                    let v19: bigint = BigInt.asUintN(64, v3 * v3);
                    let v20: boolean = v19 === 1n;
                    if (v20) {
                        let v21: bigint = BigInt.asUintN(64, v3 / 3n);
                        let v22: boolean = v21 === 6148914691236517205n;
                        if (v22) {
                            let v23: number = (v4 + v5) << 24 >> 24;
                            let v24: boolean = v23 < 0;
                            if (v24) {
                                let v25: number = (v9 / v7) | 0;
                                let v26: boolean = v25 === (-3);
                                if (v26) {
                                    let v27: number = (v9 % v7) | 0;
                                    let v28: boolean = v27 === (-1);
                                    if (v28) {
                                        let v29: bigint = BigInt.asIntN(64, v10 % 10n);
                                        let v30: boolean = v29 === (-7n);
                                        if (v30) {
                                            let v31: number = v2 >>> 28;
                                            let v32: boolean = v31 === 15;
                                            if (v32) {
                                                let v33: number = v9 >> 1;
                                                let v34: boolean = v33 === (-4);
                                                if (v34) {
                                                    return 0;
                                                } else {
                                                    return 12;
                                                }
                                            } else {
                                                return 11;
                                            }
                                        } else {
                                            return 10;
                                        }
                                    } else {
                                        return 9;
                                    }
                                } else {
                                    return 8;
                                }
                            } else {
                                return 7;
                            }
                        } else {
                            return 6;
                        }
                    } else {
                        return 5;
                    }
                } else {
                    return 4;
                }
            } else {
                return 3;
            }
        } else {
            return 2;
        }
    } else {
        return 1;
    }
}
process.exitCode = main();
