#![allow(unused_mut, non_snake_case, dead_code, clippy::needless_return, clippy::too_many_arguments)]
// Generated by Spiral portable Rust backend.

use std::rc::Rc;

fn SpiralStringIndex(value: &Rc<str>, index: i32) -> u8 {
    assert!(index >= 0, "negative Spiral string index");
    let bytes = value.as_bytes();
    let index = index as usize;
    assert!(index < bytes.len(), "Spiral string index out of bounds");
    bytes[index]
}

fn SpiralStringSlice(value: &Rc<str>, from_index: i32, to_index: i32) -> Rc<str> {
    assert!(from_index >= 0, "negative Spiral string slice start");
    let bytes = value.as_bytes();
    let length = bytes.len() as i32;
    assert!(from_index <= length, "Spiral string slice start out of bounds");
    assert!(to_index >= from_index - 1, "invalid Spiral string slice range");
    assert!(to_index < length, "Spiral string slice end out of bounds");
    if to_index < from_index { return Rc::<str>::from(""); }
    let from_index = from_index as usize;
    let to_index = to_index as usize;
    let slice = &bytes[from_index..=to_index];
    Rc::<str>::from(std::str::from_utf8(slice).expect("Spiral string slice must preserve UTF-8 boundaries"))
}

fn SpiralStringConcat(left: &Rc<str>, right: &Rc<str>) -> Rc<str> {
    let mut value = String::with_capacity(left.len() + right.len());
    value.push_str(left);
    value.push_str(right);
    Rc::<str>::from(value.into_boxed_str())
}

#[derive(Clone)]
struct Tuple0 {
    v0: Rc<str>,
    v1: i32,
    v2: bool,
}

fn TupleCreate0(v0: Rc<str>, v1: i32, v2: bool) -> Tuple0 {
    Tuple0 { v0, v1, v2 }
}

fn codec_runtime_char2(v0: Rc<str>) -> u8 {
    let v1: u8 = SpiralStringIndex(&v0, 0);
    v1
}

fn find_char_loop3(mut v0: Rc<str>, mut v1: i32, mut v2: i32, mut v3: u8) -> i32 {
    'spiral_tail: loop {
        let v4: bool = v1 == v2;
        if v4 {
            return v2;
        } else {
            let v5: u8 = SpiralStringIndex(&v0, v1);
            let v6: bool = v5 == v3;
            if v6 {
                return v1;
            } else {
                let v7: i32 = v1 + 1;
                let __spiral_tail_arg0: Rc<str> = v0.clone();
                let __spiral_tail_arg1: i32 = v7;
                let __spiral_tail_arg2: i32 = v2;
                let __spiral_tail_arg3: u8 = v3;
                v0 = __spiral_tail_arg0;
                v1 = __spiral_tail_arg1;
                v2 = __spiral_tail_arg2;
                v3 = __spiral_tail_arg3;
                continue 'spiral_tail;
            }
        }
    }
}

fn method5() -> Rc<str> {
    let v0: Rc<str> = Rc::<str>::from("");
    v0
}

fn codec_empty4() -> Rc<str> {
    method5()
}

fn starts_with_loop7(mut v0: Rc<str>, mut v1: Rc<str>, mut v2: i32, mut v3: i32, mut v4: i32) -> bool {
    'spiral_tail: loop {
        let v5: bool = v3 == v4;
        if v5 {
            return true;
        } else {
            let v6: u8 = SpiralStringIndex(&v0, v2);
            let v7: u8 = SpiralStringIndex(&v1, v3);
            let v8: bool = v6 == v7;
            if v8 {
                let v9: i32 = v2 + 1;
                let v10: i32 = v3 + 1;
                let __spiral_tail_arg0: Rc<str> = v0.clone();
                let __spiral_tail_arg1: Rc<str> = v1.clone();
                let __spiral_tail_arg2: i32 = v9;
                let __spiral_tail_arg3: i32 = v10;
                let __spiral_tail_arg4: i32 = v4;
                v0 = __spiral_tail_arg0;
                v1 = __spiral_tail_arg1;
                v2 = __spiral_tail_arg2;
                v3 = __spiral_tail_arg3;
                v4 = __spiral_tail_arg4;
                continue 'spiral_tail;
            } else {
                return false;
            }
        }
    }
}

fn find_text_loop6(mut v0: Rc<str>, mut v1: Rc<str>, mut v2: i32, mut v3: i32, mut v4: i32) -> i32 {
    'spiral_tail: loop {
        let v5: i32 = v2 + v4;
        let v6: bool = v3 < v5;
        if v6 {
            return v3;
        } else {
            let v7: i32 = v0.len() as i32;
            let v8: i32 = v1.len() as i32;
            let v9: i32 = v2 + v8;
            let v10: bool = v7 < v9;
            let mut v13: bool;
            if v10 {
                v13 = false;
            } else {
                let v11: i32 = 0;
                v13 = starts_with_loop7(v0.clone(), v1.clone(), v2, v11, v8);
            }
            if v13 {
                return v2;
            } else {
                let v14: i32 = v2 + 1;
                let __spiral_tail_arg0: Rc<str> = v0.clone();
                let __spiral_tail_arg1: Rc<str> = v1.clone();
                let __spiral_tail_arg2: i32 = v14;
                let __spiral_tail_arg3: i32 = v3;
                let __spiral_tail_arg4: i32 = v4;
                v0 = __spiral_tail_arg0;
                v1 = __spiral_tail_arg1;
                v2 = __spiral_tail_arg2;
                v3 = __spiral_tail_arg3;
                v4 = __spiral_tail_arg4;
                continue 'spiral_tail;
            }
        }
    }
}

fn parse_quoted_loop8(mut v0: Rc<str>, mut v1: i32, mut v2: i32, mut v3: Rc<str>, mut v4: bool) -> Tuple0 {
    'spiral_tail: loop {
        let v5: bool = v1 == v2;
        if v5 {
            return TupleCreate0(v3.clone(), v1, false);
        } else {
            let v6: u8 = SpiralStringIndex(&v0, v1);
            if v4 {
                let v7: bool = v6 == 110;
                let mut v24: Rc<str>;
                if v7 {
                    let v8: Rc<str> = Rc::<str>::from("\n");
                    v24 = v8;
                } else {
                    let v9: bool = v6 == 114;
                    if v9 {
                        let v10: Rc<str> = Rc::<str>::from("\r");
                        v24 = v10;
                    } else {
                        let v11: bool = v6 == 116;
                        if v11 {
                            let v12: Rc<str> = Rc::<str>::from("\t");
                            v24 = v12;
                        } else {
                            let v13: Rc<str> = Rc::<str>::from("\\");
                            let v14: u8 = codec_runtime_char2(v13.clone());
                            let v15: bool = v6 == v14;
                            if v15 {
                                v24 = v13;
                            } else {
                                let v16: Rc<str> = Rc::<str>::from("\"");
                                let v17: u8 = codec_runtime_char2(v16.clone());
                                let v18: bool = v6 == v17;
                                if v18 {
                                    v24 = v16;
                                } else {
                                    v24 = codec_empty4();
                                }
                            }
                        }
                    }
                }
                let v25: Rc<str> = Rc::<str>::from("");
                let v26: bool = v24 == v25;
                if v26 {
                    return TupleCreate0(v3.clone(), v1, false);
                } else {
                    let v27: i32 = v1 + 1;
                    let v28: Rc<str> = SpiralStringConcat(&v3, &v24);
                    let v29: bool = false;
                    let __spiral_tail_arg0: Rc<str> = v0.clone();
                    let __spiral_tail_arg1: i32 = v27;
                    let __spiral_tail_arg2: i32 = v2;
                    let __spiral_tail_arg3: Rc<str> = v28.clone();
                    let __spiral_tail_arg4: bool = v29;
                    v0 = __spiral_tail_arg0;
                    v1 = __spiral_tail_arg1;
                    v2 = __spiral_tail_arg2;
                    v3 = __spiral_tail_arg3;
                    v4 = __spiral_tail_arg4;
                    continue 'spiral_tail;
                }
            } else {
                let v36: Rc<str> = Rc::<str>::from("\\");
                let v37: u8 = codec_runtime_char2(v36.clone());
                let v38: bool = v6 == v37;
                if v38 {
                    let v39: i32 = v1 + 1;
                    let v40: bool = true;
                    let __spiral_tail_arg0: Rc<str> = v0.clone();
                    let __spiral_tail_arg1: i32 = v39;
                    let __spiral_tail_arg2: i32 = v2;
                    let __spiral_tail_arg3: Rc<str> = v3.clone();
                    let __spiral_tail_arg4: bool = v40;
                    v0 = __spiral_tail_arg0;
                    v1 = __spiral_tail_arg1;
                    v2 = __spiral_tail_arg2;
                    v3 = __spiral_tail_arg3;
                    v4 = __spiral_tail_arg4;
                    continue 'spiral_tail;
                } else {
                    let v44: Rc<str> = Rc::<str>::from("\"");
                    let v45: u8 = codec_runtime_char2(v44.clone());
                    let v46: bool = v6 == v45;
                    if v46 {
                        let v47: i32 = v1 + 1;
                        return TupleCreate0(v3.clone(), v47, true);
                    } else {
                        let v48: i32 = v1 + 1;
                        let v49: Rc<str> = SpiralStringSlice(&v0, v1, v1);
                        let v50: Rc<str> = SpiralStringConcat(&v3, &v49);
                        let v51: bool = false;
                        let __spiral_tail_arg0: Rc<str> = v0.clone();
                        let __spiral_tail_arg1: i32 = v48;
                        let __spiral_tail_arg2: i32 = v2;
                        let __spiral_tail_arg3: Rc<str> = v50.clone();
                        let __spiral_tail_arg4: bool = v51;
                        v0 = __spiral_tail_arg0;
                        v1 = __spiral_tail_arg1;
                        v2 = __spiral_tail_arg2;
                        v3 = __spiral_tail_arg3;
                        v4 = __spiral_tail_arg4;
                        continue 'spiral_tail;
                    }
                }
            }
        }
    }
}

fn skip_spaces_loop9(mut v0: Rc<str>, mut v1: i32, mut v2: i32) -> i32 {
    'spiral_tail: loop {
        let v3: bool = v1 == v2;
        if v3 {
            return v2;
        } else {
            let v4: u8 = SpiralStringIndex(&v0, v1);
            let v5: bool = v4 == 32;
            if v5 {
                let v6: i32 = v1 + 1;
                let __spiral_tail_arg0: Rc<str> = v0.clone();
                let __spiral_tail_arg1: i32 = v6;
                let __spiral_tail_arg2: i32 = v2;
                v0 = __spiral_tail_arg0;
                v1 = __spiral_tail_arg1;
                v2 = __spiral_tail_arg2;
                continue 'spiral_tail;
            } else {
                let v8: Rc<str> = Rc::<str>::from("\t");
                let v9: u8 = codec_runtime_char2(v8.clone());
                let v10: bool = v4 == v9;
                if v10 {
                    let v11: i32 = v1 + 1;
                    let __spiral_tail_arg0: Rc<str> = v0.clone();
                    let __spiral_tail_arg1: i32 = v11;
                    let __spiral_tail_arg2: i32 = v2;
                    v0 = __spiral_tail_arg0;
                    v1 = __spiral_tail_arg1;
                    v2 = __spiral_tail_arg2;
                    continue 'spiral_tail;
                } else {
                    return v1;
                }
            }
        }
    }
}

fn parse_source_loop1(mut v0: Rc<str>, mut v1: i32, mut v2: i32, mut v3: Rc<str>) -> Rc<str> {
    'spiral_tail: loop {
        let v4: bool = v1 == v2;
        if v4 {
            return v3;
        } else {
            let v5: Rc<str> = Rc::<str>::from("\n");
            let v6: u8 = codec_runtime_char2(v5.clone());
            let v7: i32 = find_char_loop3(v0.clone(), v1, v2, v6);
            let v8: bool = v1 == v7;
            let mut v12: Rc<str>;
            if v8 {
                v12 = codec_empty4();
            } else {
                let v10: i32 = v7 - 1;
                let v11: Rc<str> = SpiralStringSlice(&v0, v1, v10);
                v12 = v11;
            }
            let v13: i32 = v12.len() as i32;
            let v14: Rc<str> = Rc::<str>::from("= StateCheckSnapshot ");
            let v15: i32 = 0;
            let v16: i32 = 21;
            let v17: i32 = find_text_loop6(v12.clone(), v14.clone(), v15, v13, v16);
            let v18: bool = v17 == v13;
            let mut v34: Rc<str>;
            if v18 {
                v34 = codec_empty4();
            } else {
                let v20: i32 = v17 + 21;
                let v21: Rc<str> = Rc::<str>::from("u64");
                let v22: i32 = 3;
                let v23: i32 = find_text_loop6(v12.clone(), v21.clone(), v20, v13, v22);
                let v24: bool = v23 == v13;
                if v24 {
                    v34 = codec_empty4();
                } else {
                    let v26: bool = v20 == v23;
                    let mut v30: Rc<str>;
                    if v26 {
                        v30 = codec_empty4();
                    } else {
                        let v28: i32 = v23 - 1;
                        let v29: Rc<str> = SpiralStringSlice(&v12, v20, v28);
                        v30 = v29;
                    }
                    let v31: Rc<str> = SpiralStringConcat(&v30, &Rc::<str>::from("\n"));
                    let v32: Rc<str> = SpiralStringConcat(&Rc::<str>::from("snapshot\t"), &v31);
                    v34 = v32;
                }
            }
            let v35: Rc<str> = Rc::<str>::from("");
            let v36: bool = v34 == v35;
            let mut v189: Rc<str>;
            if v36 {
                let v37: Rc<str> = Rc::<str>::from("= ModuleTypecheckReceipt (");
                let v38: i32 = 0;
                let v39: i32 = 26;
                let v40: i32 = find_text_loop6(v12.clone(), v37.clone(), v38, v13, v39);
                let v41: bool = v40 == v13;
                if v41 {
                    v189 = codec_empty4();
                } else {
                    let v43: i32 = v40 + 26;
                    let v44: bool = v43 == v13;
                    let mut v59: Rc<str>;
                    let mut v60: i32;
                    let mut v61: bool;
                    if v44 {
                        let v45: Rc<str> = codec_empty4();
                        v59 = v45;
                        v60 = v43;
                        v61 = false;
                    } else {
                        let v46: u8 = SpiralStringIndex(&v12, v43);
                        let v47: Rc<str> = Rc::<str>::from("\"");
                        let v48: u8 = codec_runtime_char2(v47.clone());
                        let v49: bool = v46 == v48;
                        if v49 {
                            let v50: i32 = v43 + 1;
                            let v51: bool = false;
                            let tmp0: Tuple0 = parse_quoted_loop8(v12.clone(), v50, v13, v35.clone(), v51);
                            v59 = tmp0.v0;
                            v60 = tmp0.v1;
                            v61 = tmp0.v2;
                        } else {
                            let v55: Rc<str> = codec_empty4();
                            v59 = v55;
                            v60 = v43;
                            v61 = false;
                        }
                    }
                    let v62: bool = !v61;
                    if v62 {
                        v189 = codec_empty4();
                    } else {
                        let v64: u8 = 44;
                        let v65: i32 = find_char_loop3(v12.clone(), v60, v13, v64);
                        let v66: bool = v65 == v13;
                        if v66 {
                            v189 = codec_empty4();
                        } else {
                            let v68: i32 = v65 + 1;
                            let v69: i32 = skip_spaces_loop9(v12.clone(), v68, v13);
                            let v70: Rc<str> = Rc::<str>::from("u64");
                            let v71: i32 = 3;
                            let v72: i32 = find_text_loop6(v12.clone(), v70.clone(), v69, v13, v71);
                            let v73: bool = v72 == v13;
                            if v73 {
                                v189 = codec_empty4();
                            } else {
                                let v75: i32 = v72 + 3;
                                let v76: u8 = 44;
                                let v77: i32 = find_char_loop3(v12.clone(), v75, v13, v76);
                                let v78: bool = v77 == v13;
                                if v78 {
                                    v189 = codec_empty4();
                                } else {
                                    let v80: i32 = v77 + 1;
                                    let v81: i32 = skip_spaces_loop9(v12.clone(), v80, v13);
                                    let v82: i32 = 3;
                                    let v83: i32 = find_text_loop6(v12.clone(), v70.clone(), v81, v13, v82);
                                    let v84: bool = v83 == v13;
                                    if v84 {
                                        v189 = codec_empty4();
                                    } else {
                                        let v86: Rc<str> = Rc::<str>::from("\t");
                                        let v87: u8 = codec_runtime_char2(v86.clone());
                                        let v88: i32 = find_char_loop3(v12.clone(), v81, v13, v87);
                                        let v89: bool = v88 < v83;
                                        let mut v90: i32;
                                        if v89 {
                                            v90 = v88;
                                        } else {
                                            v90 = v83;
                                        }
                                        let v91: bool = v69 == v72;
                                        let mut v95: Rc<str>;
                                        if v91 {
                                            v95 = codec_empty4();
                                        } else {
                                            let v93: i32 = v72 - 1;
                                            let v94: Rc<str> = SpiralStringSlice(&v12, v69, v93);
                                            v95 = v94;
                                        }
                                        let v96: bool = v81 == v90;
                                        let mut v100: Rc<str>;
                                        if v96 {
                                            v100 = codec_empty4();
                                        } else {
                                            let v98: i32 = v90 - 1;
                                            let v99: Rc<str> = SpiralStringSlice(&v12, v81, v98);
                                            v100 = v99;
                                        }
                                        let mut v112: i32;
                                        if v89 {
                                            let v101: i32 = v88 + 1;
                                            v112 = skip_spaces_loop9(v12.clone(), v101, v13);
                                        } else {
                                            let v103: i32 = v83 + 3;
                                            let v104: i32 = skip_spaces_loop9(v12.clone(), v103, v13);
                                            let v105: bool = v104 == v13;
                                            if v105 {
                                                v112 = v104;
                                            } else {
                                                let v106: u8 = SpiralStringIndex(&v12, v104);
                                                let v107: bool = v106 == 44;
                                                if v107 {
                                                    let v108: i32 = v104 + 1;
                                                    v112 = skip_spaces_loop9(v12.clone(), v108, v13);
                                                } else {
                                                    v112 = v104;
                                                }
                                            }
                                        }
                                        let v113: i32 = skip_spaces_loop9(v12.clone(), v112, v13);
                                        let v114: bool = v113 == v13;
                                        let mut v171: Rc<str>;
                                        if v114 {
                                            let v115: Rc<str> = Rc::<str>::from("runtime");
                                            v171 = v115;
                                        } else {
                                            let v116: i32 = v113 + 18;
                                            let v117: bool = v13 < v116;
                                            let mut v122: bool;
                                            if v117 {
                                                v122 = false;
                                            } else {
                                                let v118: Rc<str> = Rc::<str>::from("RuntimeAttestation");
                                                let v119: i32 = 0;
                                                let v120: i32 = 18;
                                                v122 = starts_with_loop7(v12.clone(), v118.clone(), v113, v119, v120);
                                            }
                                            if v122 {
                                                let v123: Rc<str> = Rc::<str>::from("runtime");
                                                v171 = v123;
                                            } else {
                                                let v124: i32 = v113 + 16;
                                                let v125: bool = v13 < v124;
                                                let mut v130: bool;
                                                if v125 {
                                                    v130 = false;
                                                } else {
                                                    let v126: Rc<str> = Rc::<str>::from("BuildAttestation");
                                                    let v127: i32 = 0;
                                                    let v128: i32 = 16;
                                                    v130 = starts_with_loop7(v12.clone(), v126.clone(), v113, v127, v128);
                                                }
                                                if v130 {
                                                    let v131: i32 = v113 + 16;
                                                    let v132: i32 = skip_spaces_loop9(v12.clone(), v131, v13);
                                                    let v133: i32 = 3;
                                                    let v134: i32 = find_text_loop6(v12.clone(), v70.clone(), v132, v13, v133);
                                                    let v135: bool = v134 == v13;
                                                    if v135 {
                                                        v171 = codec_empty4();
                                                    } else {
                                                        let v137: bool = v132 == v134;
                                                        let mut v141: Rc<str>;
                                                        if v137 {
                                                            v141 = codec_empty4();
                                                        } else {
                                                            let v139: i32 = v134 - 1;
                                                            let v140: Rc<str> = SpiralStringSlice(&v12, v132, v139);
                                                            v141 = v140;
                                                        }
                                                        let v142: Rc<str> = SpiralStringConcat(&Rc::<str>::from("build:"), &v141);
                                                        v171 = v142;
                                                    }
                                                } else {
                                                    let v144: i32 = v113 + 6;
                                                    let v145: bool = v13 < v144;
                                                    let mut v150: bool;
                                                    if v145 {
                                                        v150 = false;
                                                    } else {
                                                        let v146: Rc<str> = Rc::<str>::from("build:");
                                                        let v147: i32 = 0;
                                                        let v148: i32 = 6;
                                                        v150 = starts_with_loop7(v12.clone(), v146.clone(), v113, v147, v148);
                                                    }
                                                    if v150 {
                                                        let v151: i32 = v113 + 6;
                                                        let v152: i32 = 3;
                                                        let v153: i32 = find_text_loop6(v12.clone(), v70.clone(), v151, v13, v152);
                                                        let v154: bool = v153 == v13;
                                                        if v154 {
                                                            v171 = codec_empty4();
                                                        } else {
                                                            let v156: bool = v151 == v153;
                                                            let mut v160: Rc<str>;
                                                            if v156 {
                                                                v160 = codec_empty4();
                                                            } else {
                                                                let v158: i32 = v153 - 1;
                                                                let v159: Rc<str> = SpiralStringSlice(&v12, v151, v158);
                                                                v160 = v159;
                                                            }
                                                            let v161: Rc<str> = SpiralStringConcat(&Rc::<str>::from("build:"), &v160);
                                                            v171 = v161;
                                                        }
                                                    } else {
                                                        let v163: u8 = SpiralStringIndex(&v12, v113);
                                                        let v164: bool = v163 == 41;
                                                        if v164 {
                                                            let v165: Rc<str> = Rc::<str>::from("runtime");
                                                            v171 = v165;
                                                        } else {
                                                            v171 = codec_empty4();
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                        let v172: bool = v171 == v35;
                                        if v172 {
                                            v189 = codec_empty4();
                                        } else {
                                            let v174: Rc<str> = SpiralStringConcat(&v171, &Rc::<str>::from("\n"));
                                            let v175: Rc<str> = SpiralStringConcat(&Rc::<str>::from("\t"), &v174);
                                            let v176: Rc<str> = SpiralStringConcat(&v100, &v175);
                                            let v177: Rc<str> = SpiralStringConcat(&Rc::<str>::from("\t"), &v176);
                                            let v178: Rc<str> = SpiralStringConcat(&v95, &v177);
                                            let v179: Rc<str> = SpiralStringConcat(&Rc::<str>::from("\t"), &v178);
                                            let v180: Rc<str> = SpiralStringConcat(&v59, &v179);
                                            let v181: Rc<str> = SpiralStringConcat(&Rc::<str>::from("module\t"), &v180);
                                            v189 = v181;
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            } else {
                v189 = v34;
            }
            let v190: Rc<str> = SpiralStringConcat(&v3, &v189);
            let v191: bool = v7 == v2;
            let mut v193: i32;
            if v191 {
                v193 = v2;
            } else {
                let v192: i32 = v7 + 1;
                v193 = v192;
            }
            let __spiral_tail_arg0: Rc<str> = v0.clone();
            let __spiral_tail_arg1: i32 = v193;
            let __spiral_tail_arg2: i32 = v2;
            let __spiral_tail_arg3: Rc<str> = v190.clone();
            v0 = __spiral_tail_arg0;
            v1 = __spiral_tail_arg1;
            v2 = __spiral_tail_arg2;
            v3 = __spiral_tail_arg3;
            continue 'spiral_tail;
        }
    }
}

fn receipt_parse0(v0: Rc<str>) -> Rc<str> {
    let v1: i32 = 0;
    let v2: i32 = v0.len() as i32;
    let v3: Rc<str> = Rc::<str>::from("");
    parse_source_loop1(v0.clone(), v1, v2, v3.clone())
}

#[must_use]
pub fn eoie_state_receipt_parse(value: &str) -> Rc<str> {
    receipt_parse0(Rc::<str>::from(value))
}
