// Generated by Spiral typed heap_refs residual bridge.
use std::cell::{Cell, RefCell};
use std::rc::Rc;

struct SpiralHeapRefs {
    name: RefCell<String>,
    q: Cell<i32>,
    w: Cell<i32>,
}

impl Drop for SpiralHeapRefs {
    fn drop(&mut self) {
        self.name.get_mut().clear();
    }
}

fn spiral_main() -> i32 {
    let a = Rc::new(SpiralHeapRefs {
        name: RefCell::new(String::from("seed")),
        q: Cell::new(11i32),
        w: Cell::new(13i32),
    });
    if a.name.borrow().as_str() == "seed" {
        {
            let next_value = String::from("grown");
            let old_value = a.name.replace(next_value);
            drop(old_value);
        }
        a.q.set(19i32);
    } else {
        {
            let next_value = String::from("wrong");
            let old_value = a.name.replace(next_value);
            drop(old_value);
        }
        a.q.set(29i32);
    }
    let b = Rc::clone(&a);
    if b.name.borrow().as_str() == "grown" {
        b.w.set(23i32);
    } else {
        b.w.set(31i32);
    }
    (a.q.get() + b.w.get()) as i32
}

fn main() {
    std::process::exit(spiral_main());
}
