#![allow(unused_mut, non_snake_case, dead_code, clippy::needless_return, clippy::too_many_arguments, clippy::needless_late_init)]
// Generated by Spiral portable Rust backend.
fn inspection_policy_run() -> i32 {
    let path = std::env::temp_dir().join(format!("eoie-inspection-policy-{}", std::process::id()));
    let _ = std::fs::remove_file(&path);
    if std::fs::write(&path, b"abc").is_err() { return 10; }
    let hash = eoie_proxy_search::inspection_file_sha256(&path);
    let _ = std::fs::remove_file(&path);
    if hash.as_deref() == Ok("ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad") { 0 } else { 1 }
}



fn spiral_main() -> i32 {
    let v0: i32 = inspection_policy_run();
    v0
}

fn main() {
    std::process::exit(spiral_main());
}
