#![allow(clippy::needless_return, clippy::needless_late_init, clippy::clone_on_copy)]
// Generated by Spiral portable Rust backend.
#![allow(unused_mut, non_snake_case)]

fn ArrayGet9000(index: i32, v0: i32, v1: i32, v2: i32) -> i32 {
    if index == 0 {
        return v0;
    }
    if index == 1 {
        return v1;
    }
    return v2;
}

fn ArrayGet9001(index: i32, v0: i32, v1: i32) -> i32 {
    if index == 0 {
        return v0;
    }
    return v1;
}

pub fn method0(leftIndex: i32, rightIndex: i32) -> i32 {
    let v0_0: i32;
    let v0_1: i32;
    let v0_2: i32;
    v0_0 = 40;
    v0_1 = 10;
    v0_2 = 20;
    let v1_0: i32;
    let v1_1: i32;
    v1_0 = 1;
    v1_1 = 2;
    let v2: i32;
    v2 = ArrayGet9000(leftIndex, v0_0, v0_1, v0_2) + ArrayGet9001(rightIndex, v1_0, v1_1);
    return v2;
}
